export const StaticDB = {
	FilterableUnit: "filterable.unit",
	FilterableEquip: "filterable.equip",
	FilterableEnemy: "filterable.enemy",
	FilterableFacility: "filterable.facility",
	EnemyGroup: "enemygroup",
	BG: "bg",
	Consumable: "consumable",
	Gacha: "gacha",
	Sticker: "sticker",
	Exchange: "exchange",
	EW: "ew",
	Story: "story",
	Research: "research",
	Maps: "maps",
	RoguelikeLimitEffects: "roguelike/limiteffects",
	RoguelikeBuffEffects: "roguelike/buffeffects",
	RoguelikeEffects: "roguelike/effects",
	RoguelikeNode: "roguelike/node",
	RoguelikeQuest: "roguelike/quest",
	RoguelikeItem: "roguelike/item",
	Mission: "mission",
	SkillFrom: "skill-from",
	IWSeason: "iw/seasons",

	Locale: {
		KR: "!/locale/KR",
		JP: "!/locale/JP",
		EN: "!/locale/EN",
		TC: "!/locale/TC",
		SC: "!/locale/SC",
	},
};
