export default {
  "id": 25,
  "uid": "BR_Brownie",
  "rarity": 2,
  "type": 0,
  "role": 2,
  "body": 0,
  "name": "T-2 브라우니",
  "shortname": "T-2 브라우니",
  "group": "스틸 라인",
  "shortgroup": "스틸 라인",
  "groupkey": "SteelLine",
  "introduce": "헤헤. 승리! 안녕하심까! 전 T-2, 코드명으로는 브라우니를 쓰고 있는 보병임다. 명실상부 세상에서 제일 많이 만들어진 바이오로이드지 말임다. 좀 부끄럽지만 사격도 적당히 잘하고 신체 능력도 합격점인데다가 이래뵈도 성격도 무던무던하지 말임다. 마리 대장님도 우리가 충성스럽다고 좋아하기도 했고 말임다. 뭐, 바보같이 긍정적이고 단순하단 말씀도 하셨지만 말임다.\n\n우린 스틸라인 뿐 아니라 수없이 많은 전장에서 활약했지 말임다. 물론 우리가 모든 임무를 할 수 있는 건 아니었지만 적진으로 돌격하고 점령하고 전열을 유지하는 것 하나는 엄청 잘했지 말임다. 그리고 그것만 해도 회사에서도 좋아했고 칭찬도 들었지 말임다.\n\n뭐, 멸망 이후에 다시 복원된 후에도 우리는 철충과의 최전선에서 싸우고 있슴다. 미래는 보이지 않지만, 뭐 어떻슴까? 언젠가는 더 나아지지 않겠슴까? 어쩌면 우리도 세상을 되돌리는데 큰 도움이 될 수도 있고 말임다.",
  "height": "154cm",
  "weight": "41kg",
  "weapon1": "Trooper",
  "weapon2": "F2060 Assault Rifle",
  "craftable": 1800,
  "favor": {
    "present": 2,
    "clear": 1,
    "death": 1,
    "assistant": 1
  },
  "marry": true,
  "linkBonus": [
    "HP_20",
    "ATK_20",
    "SPD_2",
    "Exp_5"
  ],
  "fullLinkBonus": [
    "Cost_20",
    "Skill_15",
    "Range_1",
    "Buff_2",
    "SPD_10"
  ],
  "equip": [
    0,
    0,
    1,
    2
  ],
  "source": [
    [
      "1-4",
      "1-5",
      "1-6",
      "1-7",
      "2-1",
      "2-2",
      "2-3",
      "2-4",
      "2-5",
      "2-6",
      "2-8",
      "3-1",
      "3-2",
      "3-3",
      "3-5",
      "3-6",
      "3-7",
      "3-8",
      "3-1Ex",
      "3-2Ex",
      "3-3Ex",
      "3-4Ex",
      "4-1",
      "4-2",
      "4-3",
      "4-4",
      "4-5",
      "4-7",
      "1-3B",
      "1-4B",
      "1-5B",
      "1-6B",
      "4-1Ex",
      "4-2Ex",
      "4-3Ex",
      "4-4Ex",
      "5-1",
      "5-2",
      "5-3",
      "5-4",
      "5-1Ex",
      "5-2Ex",
      "5-3Ex",
      "5-4Ex",
      "6-4",
      "6-7",
      "6-1Ex",
      "6-2Ex",
      "6-3Ex",
      "7-2",
      "7-4",
      "7-7",
      "7-8",
      "7-1Ex",
      "7-2Ex",
      "7-3Ex",
      "7-4Ex",
      "7-8Ex",
      "8-8"
    ],
    [
      "Ev:Ev1:Ev-1",
      "Ev:Ev1:Ev-2",
      "Ev:Ev1:Ev-3",
      "Ev:Ev1:Ev-4",
      "Ev:Ev1:Ev-5",
      "Ev:Ev1:Ev-6",
      "Ev:Ev1:Ev-1B",
      "Ev:Ev1:Ev-2B",
      "Ev:Ev1:Ev-3B",
      "Ev:Ev1:Ev-4B",
      "Ev:Ev1:Ev-1Ex",
      "Ev:Ev1:Ev-2Ex",
      "Ev:Ev1:Ev-3Ex"
    ],
    [
      "Ev:Ev2:Ev-1",
      "Ev:Ev2:Ev-2",
      "Ev:Ev2:Ev2-4B",
      "Ev:Ev2:Ev2-5B",
      "Ev:Ev2:Ev3-1s",
      "Ev:Ev2:Ev3-2s",
      "Ev:Ev2:Ev3-3s",
      "Ev:Ev2:Ev3-4s",
      "Ev:Ev2:Ev3-1ep"
    ],
    [
      "Ev:Ev3:Ev-1",
      "Ev:Ev3:Ev-2",
      "Ev:Ev3:Ev-3",
      "Ev:Ev3:Ev-4",
      "Ev:Ev3:Ev-1Ex",
      "Ev:Ev3:Ev-2Ex",
      "Ev:Ev3:Ev-3Ex",
      "Ev:Ev3:Ev-4Ex",
      "Ev:Ev3:Ev-5",
      "Ev:Ev3:Ev-6",
      "Ev:Ev3:Ev-7",
      "Ev:Ev3:Ev-8",
      "Ev:Ev3:Ev-5Ex",
      "Ev:Ev3:Ev-6Ex"
    ],
    [
      "Ev:Ev4:Ev-1",
      "Ev:Ev4:Ev-1Ex",
      "Ev:Ev4:Ev-2Ex",
      "Ev:Ev4:Ev-3Ex",
      "Ev:Ev4:Ev-4Ex",
      "Ev:Ev4:Ev-5Ex",
      "Ev:Ev4:Ev-6Ex"
    ],
    [
      "Ev:Ev5:Ev-1",
      "Ev:Ev5:Ev-2",
      "Ev:Ev5:Ev-3",
      "Ev:Ev5:Ev-4",
      "Ev:Ev5:Ev-5",
      "Ev:Ev5:Ev-6",
      "Ev:Ev5:Ev-7",
      "Ev:Ev5:Ev-8",
      "Ev:Ev5:Ev-1B",
      "Ev:Ev5:Ev-2B",
      "Ev:Ev5:Ev-3B",
      "Ev:Ev5:Ev-4B",
      "Ev:Ev5:Ev-1Ex",
      "Ev:Ev5:Ev-2Ex",
      "Ev:Ev5:Ev-3Ex",
      "Ev:Ev5:Ev-4Ex",
      "Ev:Ev5:Ev-5Ex",
      "Ev:Ev5:Ev-6Ex",
      "Ev:Ev5:Ev-7Ex",
      "Ev:Ev5:Ev2-1",
      "Ev:Ev5:Ev2-2",
      "Ev:Ev5:Ev2-3",
      "Ev:Ev5:Ev2-4",
      "Ev:Ev5:Ev2-5",
      "Ev:Ev5:Ev2-6",
      "Ev:Ev5:Ev2-7",
      "Ev:Ev5:Ev2-8",
      "Ev:Ev5:Ev2-1B",
      "Ev:Ev5:Ev2-2B",
      "Ev:Ev5:Ev2-3B",
      "Ev:Ev5:Ev2-4B",
      "Ev:Ev5:Ev2-1ep",
      "Ev:Ev5:Ev2-2ep"
    ],
    [
      "Ev:Ev6:Ev-1",
      "Ev:Ev6:Ev-2",
      "Ev:Ev6:Ev-3",
      "Ev:Ev6:Ev-4",
      "Ev:Ev6:Ev-5",
      "Ev:Ev6:Ev-6",
      "Ev:Ev6:Ev-7",
      "Ev:Ev6:Ev-8",
      "Ev:Ev6:Ev-1Ex",
      "Ev:Ev6:Ev-2Ex",
      "Ev:Ev6:Ev-3Ex",
      "Ev:Ev6:Ev-4Ex",
      "Ev:Ev6:Ev-5Ex",
      "Ev:Ev6:Ev-1ep",
      "Ev:Ev6:Ev-2ep",
      "Ev:Ev6:Ev2-1",
      "Ev:Ev6:Ev2-2",
      "Ev:Ev6:Ev2-3",
      "Ev:Ev6:Ev2-4",
      "Ev:Ev6:Ev2-5",
      "Ev:Ev6:Ev2-6",
      "Ev:Ev6:Ev2-1Ex",
      "Ev:Ev6:Ev2-2Ex",
      "Ev:Ev6:Ev2-3Ex",
      "Ev:Ev6:Ev2-4Ex",
      "Ev:Ev6:Ev2-5Ex",
      "Ev:Ev6:Ev2-6Ex",
      "Ev:Ev6:Ev2-1ep",
      "Ev:Ev6:Ev2-2ep"
    ],
    [
      "Ev:Ev7:Ev1-3",
      "Ev:Ev7:Ev1-4",
      "Ev:Ev7:Ev1-5",
      "Ev:Ev7:Ev1-6",
      "Ev:Ev7:Ev1-7",
      "Ev:Ev7:Ev1-8",
      "Ev:Ev7:Ev1-1Ex",
      "Ev:Ev7:Ev2-2",
      "Ev:Ev7:Ev2-2B",
      "Ev:Ev7:Ev2-3Ex",
      "Ev:Ev7:Ev3-1s"
    ],
    [
      "Ev:Ev8:Ev1-1",
      "Ev:Ev8:Ev1-5",
      "Ev:Ev8:Ev2-3",
      "Ev:Ev8:Ev2-5"
    ],
    [
      "Ev:Ev9:Ev1-1",
      "Ev:Ev9:Ev1-4",
      "Ev:Ev9:Ev2-3",
      "Ev:Ev9:Ev2-1B",
      "Ev:Ev9:Ev3-3s"
    ],
    [
      "Ev:Ev10:Ev1-5"
    ]
  ],
  "promotions": [
    3,
    4
  ]
};