export default {
  "NightChick_N": "나이트 칙",
  "NightChick_B0108": "나이트 칙",
  "Sparrow_N": "스패로우",
  "Stalker_B0108": "스토커",
  "NightChickM_N": "나이트 칙 런처",
  "Predator_B0208": "프레데터",
  "Kidnapper_B0308": "트릭스터",
  "NightChickTT_N": "테스트용 나이트칙",
  "NightChickTT2_N": "테스트용 나이트칙2",
  "HarvesterS_N": "실드 하베스터",
  "BigChickSP_N": "강화형 빅 칙",
  "NightChick_TU": "나이트 칙",
  "NightChick_TU2": "나이트 칙",
  "NightChick_TU3": "나이트 칙",
  "NightChick_TU4": "나이트 칙",
  "NightChickM_TU": "나이트 칙 런처",
  "NightChickM_TU2": "나이트 칙 런처",
  "NightChickM_TU3": "나이트 칙 런처",
  "NightChickM_TU4": "나이트 칙 런처",
  "NightChickS_N": "나이트 칙 실더",
  "NightChickS_TU2": "나이트 칙 실더",
  "NightChickS_TU3": "나이트 칙 실더",
  "NightChickSI_N": "나이트 칙 실더 개",
  "NightChickSI_TU2": "나이트 칙 실더 개",
  "NightChickSI_TU3": "나이트 칙 실더 개",
  "NightChickSI_TU4": "나이트 칙 실더 개",
  "NightChickC_N": "나이트 칙 캐논",
  "NightChickC_TU3": "나이트 칙 캐논",
  "NightChickC_TU4": "나이트 칙 캐논",
  "NightChickC_TU5": "나이트 칙 캐논",
  "Scout_N": "스카우트",
  "Scout_TU3": "스카우트",
  "Scout_TU4": "스카우트",
  "Scout_TU5": "스카우트",
  "BigChick_N": "빅 칙",
  "BigChick_TU2": "빅 칙",
  "BigChick_TU3": "빅 칙",
  "BigChick_TU4": "빅 칙",
  "Harvester_N": "하베스터",
  "Harvester_TU3": "하베스터",
  "Harvester_TU4": "하베스터",
  "Harvester_TU5": "하베스터",
  "FABigChick_N": "풀아머 빅 칙",
  "FABigChick_TU3": "풀아머 빅 칙",
  "FABigChick_TU4": "풀아머 빅 칙",
  "FABigChick_TU5": "풀아머 빅 칙",
  "Zapper_N": "재퍼",
  "Zapper_TU4": "재퍼",
  "Zapper_TU5": "재퍼",
  "Zapper_TU6": "재퍼",
  "Legion_N": "레기온",
  "Legion_TU4": "레기온",
  "Legion_TU5": "레기온",
  "Legion_TU6": "레기온",
  "Centurion_N": "센츄리온",
  "Centurion_TU4": "센츄리온",
  "Centurion_TU5": "센츄리온",
  "Centurion_TU6": "센츄리온",
  "NightChickSP_N": "칙 스나이퍼",
  "NightChickSP_TU5": "칙 스나이퍼",
  "NightChickSP_TU6": "칙 스나이퍼",
  "NightChickSP_TU7": "칙 스나이퍼",
  "NightChickSP_TU8": "칙 스나이퍼",
  "Wasp_N": "와습",
  "Wasp_TU5": "와습",
  "Wasp_TU6": "와습",
  "Wasp_TU7": "와습",
  "Wasp_TU8": "와습",
  "Scarab_N": "스캐럽",
  "Scarab_TU5": "스캐럽",
  "Scarab_TU6": "스캐럽",
  "Scarab_TU7": "스캐럽",
  "Scarab_TU8": "스캐럽",
  "Raider_B04": "레이더",
  "LegionMine_TU4": "레기온 마인레이어",
  "LegionMine_TU5": "레기온 마인레이어",
  "LegionMine_TU6": "레기온 마인레이어",
  "LegionMine_TU7": "레기온 마인레이어",
  "TrainingDummy_N": "표적 더미",
  "NightChickDE_N": "나이트 칙 디텍터",
  "NightChickDE_TU2": "나이트 칙 디텍터",
  "NightChickDE_TU3": "나이트 칙 디텍터",
  "NightChickDE_TU4": "나이트 칙 디텍터",
  "NightChickEX_TU": "강화형 나이트 칙",
  "NightChickEX_TU2": "강화형 나이트 칙",
  "NightChickEX_TU3": "강화형 나이트 칙",
  "NightChickEX_TU4": "강화형 나이트 칙",
  "NightChickMEX_TU": "강화형 칙 런쳐",
  "NightChickMEX_TU2": "강화형 칙 런쳐",
  "NightChickMEX_TU3": "강화형 칙 런쳐",
  "NightChickMEX_TU4": "강화형 칙 런쳐",
  "BigChickEX_TU": "시작형 빅 칙",
  "BigChickEX_TU2": "시작형 빅 칙",
  "BigChickEX_TU3": "시작형 빅 칙",
  "BigChickEX_TU4": "시작형 빅 칙",
  "BigChickM_TU": "빅 칙 런쳐",
  "BigChickM_TU2": "빅 칙 런쳐",
  "BigChickM_TU3": "빅 칙 런쳐",
  "BigChickM_TU4": "빅 칙 런쳐",
  "NightChickCM_TU": "케미컬 칙",
  "NightChickCM_TU2": "케미컬 칙",
  "NightChickCM_TU3": "케미컬 칙",
  "NightChickCM_TU4": "케미컬 칙",
  "ScoutEX_TU": "강습형 스카우트",
  "ScoutEX_TU2": "강습형 스카우트",
  "ScoutEX_TU3": "강습형 스카우트",
  "ScoutEX_TU4": "강습형 스카우트",
  "HarvesterEX_TU": "아머드 하베스터",
  "HarvesterEX_TU2": "아머드 하베스터",
  "HarvesterEX_TU3": "아머드 하베스터",
  "HarvesterEX_TU4": "아머드 하베스터",
  "NightChickCEX_TU": "개량형 칙 캐논",
  "NightChickCEX_TU2": "개량형 칙 캐논",
  "NightChickCEX_TU3": "개량형 칙 캐논",
  "NightChickCEX_TU4": "개량형 칙 캐논",
  "FABigChickEX_TU": "FA 빅 칙 II",
  "FABigChickEX_TU2": "FA 빅 칙 II",
  "FABigChickEX_TU3": "FA 빅 칙 II",
  "FABigChickEX_TU4": "FA 빅 칙 II",
  "HeavyScout_TU": "헤비 스카우트",
  "HeavyScout_TU2": "헤비 스카우트",
  "HeavyScout_TU3": "헤비 스카우트",
  "HeavyScout_TU4": "헤비 스카우트",
  "Juggernaut_TU": "저거너트",
  "Juggernaut_TU2": "저거너트",
  "Juggernaut_TU3": "저거너트",
  "Juggernaut_TU4": "저거너트",
  "Phalangites_TU": "팔랑스",
  "Phalangites_TU2": "팔랑스",
  "Phalangites_TU3": "팔랑스",
  "Phalangites_TU4": "팔랑스",
  "LegionEX_TU": "정예 레기온",
  "LegionEX_TU2": "정예 레기온",
  "LegionEX_TU3": "정예 레기온",
  "LegionEX_TU4": "정예 레기온",
  "ZapperEX_TU": "강화형 재퍼",
  "ZapperEX_TU2": "강화형 재퍼",
  "ZapperEX_TU3": "강화형 재퍼",
  "ZapperEX_TU4": "강화형 재퍼",
  "CenturionEX_TU": "엘리트 센츄리온",
  "CenturionEX_TU2": "엘리트 센츄리온",
  "CenturionEX_TU3": "엘리트 센츄리온",
  "CenturionEX_TU4": "엘리트 센츄리온",
  "WaspEX_TU": "와습 HM",
  "WaspEX_TU2": "와습 HM",
  "WaspEX_TU3": "와습 HM",
  "WaspEX_TU4": "와습 HM",
  "ScarabEX_TU": "스캐럽 HC",
  "ScarabEX_TU2": "스캐럽 HC",
  "ScarabEX_TU3": "스캐럽 HC",
  "ScarabEX_TU4": "스캐럽 HC",
  "Mammoth_TU": "매머드",
  "Mammoth_TU2": "매머드",
  "Mammoth_TU3": "매머드",
  "Mammoth_TU4": "매머드",
  "Rampart_TU2": "경비용 램파트",
  "Rampart_TU3": "경비용 램파트",
  "Rampart_TU4": "경비용 램파트",
  "Rampart_TU5": "경비용 램파트",
  "Fallen_TU2": "경비용 폴른",
  "Fallen_TU3": "경비용 폴른",
  "Fallen_TU4": "경비용 폴른",
  "Fallen_TU5": "경비용 폴른",
  "PuppHead_TU2": "경비용 펍 헤드",
  "PuppHead_TU3": "경비용 펍 헤드",
  "PuppHead_TU4": "경비용 펍 헤드",
  "PuppHead_TU5": "경비용 펍 헤드",
  "Stinger_TU2": "양산형 스팅어",
  "Stinger_TU3": "양산형 스팅어",
  "Stinger_TU4": "양산형 스팅어",
  "Stinger_TU5": "양산형 스팅어",
  "AMG11_TU2": "경비용 AMG-11",
  "AMG11_TU3": "경비용 AMG-11",
  "AMG11_TU4": "경비용 AMG-11",
  "AMG11_TU5": "경비용 AMG-11",
  "Drone_TU2": "경비용 드론",
  "Drone_TU3": "경비용 드론",
  "Drone_TU4": "경비용 드론",
  "Drone_TU5": "경비용 드론",
  "Seljuq_TU2": "양산형 셀주크",
  "Seljuq_TU3": "양산형 셀주크",
  "Seljuq_TU4": "양산형 셀주크",
  "Seljuq_TU5": "양산형 셀주크",
  "Gigantes_TU2": "양산형 기간테스",
  "Gigantes_TU3": "양산형 기간테스",
  "Gigantes_TU4": "양산형 기간테스",
  "Gigantes_TU5": "양산형 기간테스",
  "Kidnapper_CH": "트릭스터",
  "UnderWatcher_B05": "언더왓쳐",
  "UnderWatcherArm_B05": "언더왓쳐 암",
  "UnderWatcherSensor_B05": "언더왓쳐 센서",
  "UnderWatcherGenerator_B05": "언더왓쳐 제네레이터",
  "NightChick_RV": "나이트 칙 Type-S",
  "Raider_CH": "광폭화 레이더",
  "Wasp_TU": "와습",
  "Mammoth_N": "매머드",
  "Stalker_TU2": "스토커",
  "UnderWatcher_TU2": "언더왓쳐",
  "UnderWatcherArm_TU2": "언더왓쳐 암",
  "UnderWatcherSensor_TU2": "언더왓쳐 센서",
  "UnderWatcherGenerator_TU2": "언더왓쳐 제네레이터",
  "CenturionCF_N": "센츄리온 치프틴",
  "CenturionCF_TU2": "센츄리온 치프틴",
  "Tortoise_N": "토터스",
  "Tortoise_TU2": "토터스",
  "NightChickQM_N": "칙 쿼터마스터",
  "NightChickQM_TU2": "칙 쿼터마스터",
  "Spector_N": "스펙터",
  "Spector_TU2": "스펙터",
  "LegionSP_N": "레기온 스나이퍼",
  "LegionSP_TU2": "레기온 스나이퍼",
  "EmperorChick_N": "칙 엠페러",
  "EmperorChick_TU2": "칙 엠페러",
  "ProgramMobTS_N": "철충 사념체 (보병)",
  "ProgramMobTS_TU2": "철충 사념체 (보병)",
  "ProgramMobTT_N": "철충 사념체 (장갑병)",
  "ProgramMobTT_TU2": "철충 사념체 (장갑병)",
  "ProgramMobMS_N": "철충 사념체 (정찰기)",
  "ProgramMobMS_TU2": "철충 사념체 (정찰기)",
  "ProgramMobMT_N": "철충 사념체 (호위기)",
  "ProgramMobMT_TU2": "철충 사념체 (호위기)",
  "ProgramMobTN_N": "철충 사념체 (저격병)",
  "ProgramMobTN_TU2": "철충 사념체 (저격병)",
  "ProgramMobAS_N": "철충 사념체 (돌격병)",
  "ProgramMobAS_TU2": "철충 사념체 (돌격병)",
  "ProgramMobMN_N": "철충 사념체 (폭격기)",
  "ProgramMobMN_TU2": "철충 사념체 (폭격기)",
  "ProgramMobAN_N": "철충 사념체 (포병)",
  "ProgramMobAN_TU2": "철충 사념체 (포병)",
  "ProgramMobAT_N": "철충 사념체 (중장갑병)",
  "ProgramMobAT_TU2": "철충 사념체 (중장갑병)",
  "ExpGoblinT_N": "실험체 고블린",
  "ExpGoblinT_TU2": "실험체 고블린",
  "ExpGoblinA_N": "실험체 고블린 파쇄병",
  "ExpGoblinA_TU2": "실험체 고블린 파쇄병",
  "ExpGenerator_N": "수상한 기계장치",
  "ExpGenerator_TU2": "수상한 기계장치",
  "ExpGenerator2_N": "수상한 실험체",
  "ExpGenerator2_TU2": "수상한 실험체",
  "NightChick_TU5": "나이트 칙",
  "NightChick_TU6": "나이트 칙",
  "NightChickM_TU5": "나이트 칙 런처",
  "NightChickM_TU6": "나이트 칙 런처",
  "Harvester_TU6": "하베스터",
  "NightChickDE_TU5": "나이트 칙 디텍터",
  "NightChickDE_TU6": "나이트 칙 디텍터",
  "NightChickSI_TU5": "나이트 칙 실더 개",
  "NightChickSI_TU6": "나이트 칙 실더 개",
  "Executioner_B06": "익스큐셔너",
  "ExecutionerLB_B06": "익스큐셔너 롱 블레이드",
  "ExecutionerRB_B06": "익스큐셔너 실드 블레이드",
  "NightChickS_TU4": "나이트 칙 실더",
  "NightChickS_TU5": "나이트 칙 실더",
  "NightChickC_EV1": "나이트 칙 캐논",
  "NightChickC_EV2": "나이트 칙 캐논",
  "NightChickC_EV3": "나이트 칙 캐논",
  "NightChickC_EV4": "나이트 칙 캐논",
  "NightChickC_EV5": "나이트 칙 캐논",
  "NightChickC_EV6": "나이트 칙 캐논",
  "NightChickC_EV7": "나이트 칙 캐논",
  "NightChickC_EV8": "나이트 칙 캐논",
  "NightChickQM_EV1": "칙 쿼터마스터",
  "NightChickQM_EV2": "칙 쿼터마스터",
  "Predator_EV1": "프레데터",
  "Predator_EV2": "프레데터",
  "NightChickSP_EV1": "칙 스나이퍼",
  "ScarabEX_EV1": "스캐럽 HC",
  "ScarabEX_EV2": "스캐럽 HC",
  "WaspEX_EV1": "와습 HM",
  "ScoutEX_EV1": "강습형 스카우트",
  "Scout_EV1": "스카우트",
  "HeavyScout_EV1": "헤비 스카우트",
  "HeavyScout_EV2": "헤비 스카우트",
  "HeavyScout_EV3": "헤비 스카우트",
  "BigChickM_EV1": "빅 칙 런쳐",
  "NightChickEX_EV1": "강화형 나이트 칙",
  "NightChickCEX_EV1": "개량형 칙 캐논",
  "LegionSP_EV1": "레기온 스나이퍼",
  "NightChickDE_EV1": "나이트 칙 디텍터",
  "Stalker_EV1": "스토커",
  "BigChickSP_EV1": "강화형 빅 칙",
  "Kidnapper_EV1": "트릭스터",
  "EmperorChick_EV1": "칙 엠페러",
  "Spector_EV1": "스펙터",
  "ZapperEX_EV1": "강화형 재퍼",
  "NightChickSI_SS1": "나이트 칙 실더 개",
  "FABigChick_SS1": "풀아머 빅 칙",
  "Phalangites_SS1": "팔랑스",
  "BigChick_SS1": "빅 칙",
  "FABigChickEX_TU5": "FA 빅 칙 II",
  "ScoutEX_TU5": "강습형 스카우트",
  "BigChickSP_TU2": "강화형 빅 칙",
  "BigChickSP_TU3": "강화형 빅 칙",
  "ZapperEX_TU5": "강화형 재퍼",
  "ZapperEX_TU6": "강화형 재퍼",
  "NightChickMEX_TU5": "강화형 칙 런쳐",
  "LegionSPEX_N": "개량형 레기온 스나이퍼",
  "LegionSPEX_TU2": "개량형 레기온 스나이퍼",
  "NightChickCEX_TU5": "개량형 칙 캐논",
  "NightChickQMEX_N": "개량형 칙 쿼터마스터",
  "NightChickQMEX_TU2": "개량형 칙 쿼터마스터",
  "NightChickDE_TU7": "나이트 칙 디텍터",
  "NightChickDE_TU8": "나이트 칙 디텍터",
  "NightChickSI_TU7": "나이트 칙 실더 개",
  "Mammoth_TU5": "매머드",
  "Mammoth_TU6": "매머드",
  "BigChickM_TU5": "빅 칙 런쳐",
  "Centurion_TU7": "센츄리온",
  "CenturionCF_TU3": "센츄리온 치프틴",
  "CenturionCF_TU4": "센츄리온 치프틴",
  "CenturionCF_TU5": "센츄리온 치프틴",
  "ScarabEX_TU5": "스캐럽 HC",
  "ScarabEX_TU6": "스캐럽 HC",
  "SpectorBS_N": "스펙터 BS",
  "SpectorMS_N": "스펙터 MS",
  "BigChickEX_TU5": "시작형 빅 칙",
  "BigChickEX_TU6": "시작형 빅 칙",
  "HarvesterEX_TU5": "아머드 하베스터",
  "CenturionEX_TU5": "엘리트 센츄리온",
  "WaspEX_TU5": "와습 HM",
  "Juggernaut_TU5": "저거너트",
  "Juggernaut_TU6": "저거너트",
  "ScoutSP_N": "지원형 스카우트",
  "ScoutSP_TU2": "지원형 스카우트",
  "NightChickSP_TU9": "칙 스나이퍼",
  "EmperorChick_TU3": "칙 엠페러",
  "EmperorChick_TU4": "칙 엠페러",
  "NightChickQM_TU3": "칙 쿼터마스터",
  "NightChickCM_TU5": "케미컬 칙",
  "Tortoise_TU3": "토터스",
  "Tortoise_TU4": "토터스",
  "Phalangites_TU5": "팔랑스",
  "Phalangites_TU6": "팔랑스",
  "FABigChick_TU6": "풀아머 빅 칙",
  "HeavyScout_TU5": "헤비 스카우트",
  "NightChickTD_TU": "썬더 칙",
  "NightChickTD_TU2": "썬더 칙",
  "NightChickTD_TU3": "썬더 칙",
  "NightChickTD_TU4": "썬더 칙",
  "NightChickAQ_TU": "아쿠아 칙",
  "NightChickAQ_TU2": "아쿠아 칙",
  "NightChickAQ_TU3": "아쿠아 칙",
  "NightChickAQ_TU4": "아쿠아 칙",
  "Chiller_TU": "칠러",
  "Chiller_TU2": "칠러",
  "Chiller_TU3": "칠러",
  "Chiller_TU4": "칠러",
  "BigChickS_TU": "빅 칙 실더",
  "BigChickS_TU2": "빅 칙 실더",
  "BigChickS_TU3": "빅 칙 실더",
  "BigChickS_TU4": "빅 칙 실더",
  "MammothP_TU": "개량형 매머드",
  "MammothP_TU2": "개량형 매머드",
  "MammothP_TU3": "개량형 매머드",
  "MammothP_TU4": "개량형 매머드",
  "NightChickDEG_TU": "나이트 칙 디텍터 G",
  "NightChickDEG_TU2": "나이트 칙 디텍터 G",
  "NightChickDEG_TU3": "나이트 칙 디텍터 G",
  "NightChickDEG_TU4": "나이트 칙 디텍터 G",
  "NightChickSPV_TU": "베테랑 칙 스나이퍼",
  "NightChickSPV_TU2": "베테랑 칙 스나이퍼",
  "NightChickSPV_TU3": "베테랑 칙 스나이퍼",
  "NightChickSPV_TU4": "베테랑 칙 스나이퍼",
  "NightChickCMP_EV1": "케미컬 칙 Type-X",
  "NightChickCMP_EV2": "케미컬 칙 Type-X",
  "HeavyScoutG_TU": "헤비 스카우트 G",
  "HeavyScoutG_TU2": "헤비 스카우트 G",
  "HeavyScoutG_TU3": "헤비 스카우트 G",
  "HeavyScoutG_TU4": "헤비 스카우트 G",
  "RampartC_EV1": "램파트 커스텀",
  "RampartC_EV2": "램파트 커스텀",
  "RampartC_EV3": "램파트 커스텀",
  "RampartC_EV4": "램파트 커스텀",
  "FallenC_EV1": "폴른 커스텀",
  "FallenC_EV2": "폴른 커스텀",
  "FallenC_EV3": "폴른 커스텀",
  "FallenC_EV4": "폴른 커스텀",
  "PuppHeadC_EV1": "펍 헤드 커스텀",
  "PuppHeadC_EV2": "펍 헤드 커스텀",
  "PuppHeadC_EV3": "펍 헤드 커스텀",
  "PuppHeadC_EV4": "펍 헤드 커스텀",
  "StingerC_EV1": "스팅어 커스텀",
  "StingerC_EV2": "스팅어 커스텀",
  "StingerC_EV3": "스팅어 커스텀",
  "StingerC_EV4": "스팅어 커스텀",
  "AMG11AA_EV1": "대공용 AMG-11",
  "AMG11AA_EV2": "대공용 AMG-11",
  "AMG11AA_EV3": "대공용 AMG-11",
  "AMG11AA_EV4": "대공용 AMG-11",
  "DroneM_EV1": "드론 커스텀",
  "DroneM_EV2": "드론 커스텀",
  "DroneM_EV3": "드론 커스텀",
  "DroneM_EV4": "드론 커스텀",
  "SeljuqA_EV1": "셀주크 커스텀",
  "SeljuqA_EV2": "셀주크 커스텀",
  "SeljuqA_EV3": "셀주크 커스텀",
  "SeljuqA_EV4": "셀주크 커스텀",
  "GigantesC_EV1": "기간테스 커스텀",
  "GigantesC_EV2": "기간테스 커스텀",
  "GigantesC_EV3": "기간테스 커스텀",
  "GigantesC_EV4": "기간테스 커스텀",
  "RocC_EV1": "로크 (최대 충전)",
  "RocC_EV2": "로크 (최대 충전)",
  "RocCGenerator_EV1": "에너지 컨덴서",
  "RocCGenerator_EV2": "에너지 컨덴서",
  "Testudo_TU": "테스투도",
  "Testudo_TU2": "테스투도",
  "Testudo_TU3": "테스투도",
  "Testudo_TU4": "테스투도",
  "LegionElite_TU": "엘리트 레기온",
  "LegionElite_TU2": "엘리트 레기온",
  "LegionElite_TU3": "엘리트 레기온",
  "LegionElite_TU4": "엘리트 레기온",
  "CenturionG_TU": "센츄리온 제네럴",
  "CenturionG_TU2": "센츄리온 제네럴",
  "CenturionG_TU3": "센츄리온 제네럴",
  "CenturionG_TU4": "센츄리온 제네럴",
  "Centurion_EV1": "센츄리온",
  "Centurion_EV2": "센츄리온",
  "NightChickC_EV9": "나이트 칙 캐논",
  "RocCGeneratorA_EV1": "강화 에너지 컨덴서",
  "RocCGeneratorA_EV2": "강화 에너지 컨덴서",
  "Undine_EV1": "까망베르",
  "Undine_EV2": "퐁 레베크",
  "Undine_EV3": "브리 드 모",
  "Undine_EV4": "그럼…요?",
  "Undine_EV5": "P-3M 운디네_적",
  "Sirene_EV1": "문제아반 반장",
  "Sirene_EV2": "그럼요~",
  "Nereid_EV1": "슈퍼 네리다!",
  "Nereid_EV2": "그럼~요!",
  "Nereid_EV3": "AG-1 네레이드_적",
  "Nereid_EV4": "AG-1 네레이드_적",
  "Nereid_EV5": "AG-1 네레이드_적",
  "AMG11AA_EV5": "네리의 부하",
  "GigantesDagon_N": "다곤씨 (대여 중)",
  "BigChickMG_N": "빅 칙 런쳐 G",
  "BigChickMG_EV1": "빅 칙 런쳐 G",
  "BigChickMG_EV2": "빅 칙 런쳐 G",
  "BigChickMG_EV3": "빅 칙 런쳐 G",
  "NightChickCMS_N": "강화형 케미컬 칙",
  "NightChickCMS_EV1": "강화형 케미컬 칙",
  "JuggernautP_N": "강화형 저거너트",
  "JuggernautP_EV1": "강화형 저거너트",
  "Stalker_EV2": "스토커",
  "ScoutEX_EW": "강습형 스카우트",
  "RocCGenerator_EW": "에너지 컨덴서",
  "UnderWatcherGenerator_EW": "언더왓쳐 제네레이터",
  "UnderWatcher_EW": "언더왓쳐",
  "UnderWatcherArm_EW": "언더왓쳐 암",
  "UnderWatcherSensor_EW": "언더왓쳐 센서",
  "Stalker_EW": "스토커",
  "Predator_EW": "프레데터",
  "Kidnapper_EW": "트릭스터",
  "Raider_EW": "레이더",
  "Executioner_EW": "익스큐셔너",
  "ExecutionerLB_EW": "익스큐셔너 롱 블레이드",
  "ExecutionerRB_EW": "익스큐셔너 실드 블레이드",
  "DoomEater_N_EW2": "둠 이터",
  "Executioner_BEW_EW2": "이모탈 익스큐셔너",
  "NightChick_EW2": "나이트 칙",
  "Tarantula_EW2": "개조된 타란튤라",
  "NightChickTD_EW": "썬더 칙",
  "ProgramMobTS_EW": "가상공간 솔져",
  "ProgramMobTT_EW": "가상공간 실더",
  "ProgramMobMS_EW": "가상공간 경보기",
  "ProgramMobMT_EW": "가상공간 파이터",
  "ProgramMobTN_EW": "가상공간 스나이퍼",
  "ProgramMobAS_EW": "가상공간 패트릭",
  "ProgramMobMN_EW": "가상공간 봄버",
  "ProgramMobAN_EW": "가상공간 캐노니어",
  "ProgramMobAT_EW": "가상공간 탱크",
  "NightChickEX_EW": "강화형 나이트 칙",
  "NightChickSI_EW": "나이트 칙 실더 개",
  "NightChickDEG_EW": "나이트 칙 디텍터 G",
  "NightChickQM_EW": "칙 쿼터마스터",
  "NightChickSP_EW": "칙 스나이퍼",
  "BigChick_EW": "빅 칙",
  "Mammoth_EW": "매머드",
  "HarvesterEX_EW": "아머드 하베스터",
  "NightChickEX_N": "강화형 나이트 칙",
  "NightChickMEX_N": "강화형 칙 런쳐",
  "BigChickEX_N": "시작형 빅 칙",
  "BigChickM_N": "빅 칙 런쳐",
  "NightChickCM_N": "케미컬 칙",
  "ScoutEX_N": "강습형 스카우트",
  "HarvesterEX_N": "아머드 하베스터",
  "NightChickCEX_N": "개량형 칙 캐논",
  "FABigChickEX_N": "FA 빅 칙 II",
  "HeavyScout_N": "헤비 스카우트",
  "Juggernaut_N": "저거너트",
  "Phalangites_N": "팔랑스",
  "LegionEX_N": "정예 레기온",
  "ZapperEX_N": "강화형 재퍼",
  "CenturionEX_N": "엘리트 센츄리온",
  "WaspEX_N": "와습 HM",
  "ScarabEX_N": "스캐럽 HC",
  "NightChickTD_N": "썬더 칙",
  "NightChickAQ_N": "아쿠아 칙",
  "Chiller_N": "칠러",
  "BigChickS_N": "빅 칙 실더",
  "NightChickDEG_N": "나이트 칙 디텍터 G",
  "NightChickCMP_N": "케미컬 칙 Type-X",
  "Testudo_N": "테스투도",
  "LegionElite_N": "엘리트 레기온",
  "CenturionG_N": "센츄리온 제네럴",
  "NightChickShEx_N": "강화형 칙 실더",
  "NightChickShEx_TU2": "강화형 칙 실더",
  "NightChickShEx_TU3": "강화형 칙 실더",
  "NightChickShEx_TU4": "강화형 칙 실더",
  "Tarantula_N": "타란튤라",
  "Tarantula_TU2": "타란튤라",
  "Tarantula_TU3": "타란튤라",
  "Tarantula_TU4": "타란튤라",
  "NightChickDEX_N": "강화형 칙 디텍터",
  "NightChickDEX_TU2": "강화형 칙 디텍터",
  "NightChickDEX_TU3": "강화형 칙 디텍터",
  "NightChickDEX_TU4": "강화형 칙 디텍터",
  "Frostbite_N": "프로스트바이트",
  "Frostbite_TU": "프로스트바이트",
  "Frostbite_TU2": "프로스트바이트",
  "Frostbite_TU3": "프로스트바이트",
  "Frostbite_TU4": "프로스트바이트",
  "Destroyer_N": "디스트로이어",
  "Destroyer_TU": "디스트로이어",
  "Destroyer_TU2": "디스트로이어",
  "Destroyer_TU3": "디스트로이어",
  "Destroyer_TU4": "디스트로이어",
  "NightChickDEAA_N": "나이트 칙 디텍터 AA",
  "NightChickDEAA_TU": "나이트 칙 디텍터 AA",
  "NightChickDEAA_TU2": "나이트 칙 디텍터 AA",
  "NightChickDEAA_TU3": "나이트 칙 디텍터 AA",
  "NightChickDEAA_TU4": "나이트 칙 디텍터 AA",
  "LegionMk2_N": "레기온 Mk.II",
  "LegionMk2_TU": "레기온 Mk.II",
  "LegionMk2_TU2": "레기온 Mk.II",
  "LegionMk2_TU3": "레기온 Mk.II",
  "LegionMk2_TU4": "레기온 Mk.II",
  "NightChickSPW_N": "한랭지형 칙 스나이퍼",
  "NightChickSPW_TU": "한랭지형 칙 스나이퍼",
  "NightChickSPW_TU2": "한랭지형 칙 스나이퍼",
  "NightChickSPW_TU3": "한랭지형 칙 스나이퍼",
  "NightChickSPW_TU4": "한랭지형 칙 스나이퍼",
  "MammothW_N": "한랭지형 매머드",
  "MammothW_TU": "한랭지형 매머드",
  "MammothW_TU2": "한랭지형 매머드",
  "MammothW_TU3": "한랭지형 매머드",
  "MammothW_TU4": "한랭지형 매머드",
  "NightChick_C": "나이트 칙?",
  "NightChickM_C": "나이트 칙 런처??",
  "NightChickS_C": "나이트 칙 실더???",
  "NightChickC_C": "나이트 칙 캐논?",
  "NightChickTD_C": "썬더 칙?",
  "NightChickAQ_C": "아쿠아 칙?",
  "NightChickSpCH_N": "솔져 칙",
  "EmperorChickSpCH_N": "칙 커맨더",
  "DoomEater_N_EW": "굶주린 둠 이터",
  "Frostbite_EW": "프로스트바이트",
  "NightChickSPW_EW": "한랭지형 칙 스나이퍼",
  "EmperorChick_EW": "칙 엠페러",
  "NightChickAQ_EW": "아쿠아 칙",
  "EmperorChickSpCH_C": "칙 커맨더",
  "NightChickSpCH_C": "솔져 칙",
  "RampartC_VT2": "초코 여왕의 정예 경비병",
  "RampartC_VT3": "초코 여왕의 정예 경비병",
  "RampartC_VT4": "초코 여왕의 정예 경비병",
  "RampartC_VT5": "초코 여왕의 정예 경비병",
  "FallenC_VT2": "초코 여왕의 정예 보병",
  "FallenC_VT3": "초코 여왕의 정예 보병",
  "FallenC_VT4": "초코 여왕의 정예 보병",
  "FallenC_VT5": "초코 여왕의 정예 보병",
  "PuppHeadC_VT2": "초코 여왕의 귀여운 애완기계",
  "PuppHeadC_VT3": "초코 여왕의 귀여운 애완기계",
  "PuppHeadC_VT4": "초코 여왕의 귀여운 애완기계",
  "PuppHeadC_VT5": "초코 여왕의 귀여운 애완기계",
  "StingerC_VT2": "초코 여왕의 정예 돌격병",
  "StingerC_VT3": "초코 여왕의 정예 돌격병",
  "StingerC_VT4": "초코 여왕의 정예 돌격병",
  "StingerC_VT5": "초코 여왕의 정예 돌격병",
  "AMG11AA_VT2": "초코 여왕의 정예 감시병",
  "AMG11AA_VT3": "초코 여왕의 정예 감시병",
  "AMG11AA_VT4": "초코 여왕의 정예 감시병",
  "AMG11AA_VT5": "초코 여왕의 정예 감시병",
  "DroneM_VT2": "초코 여왕의 정예 정찰병",
  "DroneM_VT3": "초코 여왕의 정예 정찰병",
  "DroneM_VT4": "초코 여왕의 정예 정찰병",
  "DroneM_VT5": "초코 여왕의 정예 정찰병",
  "SeljuqA_VT2": "초코 여왕의 정예 포병",
  "SeljuqA_VT3": "초코 여왕의 정예 포병",
  "SeljuqA_VT4": "초코 여왕의 정예 포병",
  "SeljuqA_VT5": "초코 여왕의 정예 포병",
  "GigantesC_VT2": "초코 여왕의 정예 근위병",
  "GigantesC_VT3": "초코 여왕의 정예 근위병",
  "GigantesC_VT4": "초코 여왕의 정예 근위병",
  "GigantesC_VT5": "초코 여왕의 정예 근위병",
  "Rampart_VT2": "초코 여왕의 경비병",
  "Rampart_VT3": "초코 여왕의 경비병",
  "Rampart_VT4": "초코 여왕의 경비병",
  "Rampart_VT5": "초코 여왕의 경비병",
  "Fallen_VT2": "초코 여왕의 보병",
  "Fallen_VT3": "초코 여왕의 보병",
  "Fallen_VT4": "초코 여왕의 보병",
  "Fallen_VT5": "초코 여왕의 보병",
  "PuppHead_VT2": "초코 여왕의 애완기계",
  "PuppHead_VT3": "초코 여왕의 애완기계",
  "PuppHead_VT4": "초코 여왕의 애완기계",
  "PuppHead_VT5": "초코 여왕의 애완기계",
  "Stinger_VT2": "초코 여왕의 돌격병",
  "Stinger_VT3": "초코 여왕의 돌격병",
  "Stinger_VT4": "초코 여왕의 돌격병",
  "Stinger_VT5": "초코 여왕의 돌격병",
  "AMG11_VT2": "초코 여왕의 감시병",
  "AMG11_VT3": "초코 여왕의 감시병",
  "AMG11_VT4": "초코 여왕의 감시병",
  "AMG11_VT5": "초코 여왕의 감시병",
  "Drone_VT2": "초코 여왕의 정찰병",
  "Drone_VT3": "초코 여왕의 정찰병",
  "Drone_VT4": "초코 여왕의 정찰병",
  "Drone_VT5": "초코 여왕의 정찰병",
  "Seljuq_VT2": "초코 여왕의 포병",
  "Seljuq_VT3": "초코 여왕의 포병",
  "Seljuq_VT4": "초코 여왕의 포병",
  "Seljuq_VT5": "초코 여왕의 포병",
  "Gigantes_VT2": "초코 여왕의 근위병",
  "Gigantes_VT3": "초코 여왕의 근위병",
  "Gigantes_VT4": "초코 여왕의 근위병",
  "Gigantes_VT5": "초코 여왕의 근위병",
  "SpectorMS_EW": "양산형 스펙터",
  "Nest_B07": "네스트",
  "NestChaser_N": "네스트 체이서",
  "NestGuardian_N": "네스트 가디언",
  "NightChickShSv_N": "생존형 칙 실더",
  "NightChickShSv_TU2": "생존형 칙 실더",
  "NightChickShSv_TU3": "생존형 칙 실더",
  "NightChickShSv_TU4": "생존형 칙 실더",
  "LegionSP_TU3": "레기온 스나이퍼",
  "LegionSP_TU4": "레기온 스나이퍼",
  "LegionSP_TU5": "레기온 스나이퍼",
  "NightChickCMSv_N": "생존형 케미컬 칙",
  "NightChickCMSv_TU2": "생존형 케미컬 칙",
  "NightChickCMSv_TU3": "생존형 케미컬 칙",
  "NightChickCMSv_TU4": "생존형 케미컬 칙",
  "NightChickAQ_VT1": "아쿠아 칙",
  "NightChickAQ_VT2": "아쿠아 칙",
  "NightChickAQ_VT3": "아쿠아 칙",
  "NightChickAQ_VT4": "아쿠아 칙",
  "LightningBomber_N": "라이트닝 봄버",
  "LightningBomber_TU2": "라이트닝 봄버",
  "LightningBomber_TU3": "라이트닝 봄버",
  "LightningBomber_TU4": "라이트닝 봄버",
  "LightningBomber_TU5": "라이트닝 봄버",
  "Speaker_N": "스피커",
  "Speaker_TU2": "스피커",
  "Speaker_TU3": "스피커",
  "Speaker_TU4": "스피커",
  "Speaker_TU5": "스피커",
  "FABigChickS_N": "풀아머 빅 칙 실더",
  "FABigChickS_TU2": "풀아머 빅 칙 실더",
  "FABigChickS_TU3": "풀아머 빅 칙 실더",
  "FABigChickS_TU4": "풀아머 빅 칙 실더",
  "FABigChickS_TU5": "풀아머 빅 칙 실더",
  "NightChickSpCH_B0208": "기능 테스트용 1",
  "NightChickSpCH_B0308": "기능 테스트용 2",
  "EmperorChickSpCH_TU": "칙 커맨더",
  "EmperorChickSpCH_TU2": "칙 커맨더",
  "EmperorChickSpCH_TU3": "칙 커맨더",
  "EmperorChickSpCH_TU4": "칙 커맨더",
  "EmperorChickSpCH_TU5": "칙 커맨더",
  "EmperorChick_TU": "칙 엠페러",
  "LightningBomber_EW": "라이트닝 봄버",
  "LightningBomber_EW2": "라이트닝 봄버",
  "LightningBomber_EW3": "라이트닝 봄버",
  "LightningBomber_EW4": "라이트닝 봄버",
  "LightningBomber_EW5": "라이트닝 봄버",
  "Nest_EW": "네스트",
  "NestChaser_EW": "네스트 체이서",
  "NestGuardian_EW": "네스트 가디언",
  "Executioner_TU2": "익스큐셔너",
  "Nest_TU2": "네스트",
  "NestChaser_TU2": "네스트 체이서",
  "NestGuardian_TU2": "네스트 가디언",
  "NightChickQMSK_N": "칙 쿼터마스터SK",
  "NightChickQMSK_TU": "칙 쿼터마스터SK",
  "NightChickQMSK_TU2": "칙 쿼터마스터SK",
  "NightChickQMSK_TU3": "칙 쿼터마스터SK",
  "NightChickQMSK_TU4": "칙 쿼터마스터SK",
  "NightChickQMSK_TU5": "칙 쿼터마스터SK",
  "PhalangitesH_N": "팔랑스H",
  "PhalangitesH_TU": "팔랑스H",
  "PhalangitesH_TU2": "팔랑스H",
  "PhalangitesH_TU3": "팔랑스H",
  "PhalangitesH_TU4": "팔랑스H",
  "PhalangitesH_TU5": "팔랑스H",
  "RobertCore_N": "로버트",
  "RobertArm_N": "로버트 암",
  "Robert_N": "로버트",
  "RampartC_SA2": "램파트 커스텀",
  "RampartC_SA3": "램파트 커스텀",
  "RampartC_SA4": "램파트 커스텀",
  "RampartC_SA5": "램파트 커스텀",
  "FallenC_SA2": "폴른 커스텀",
  "FallenC_SA3": "폴른 커스텀",
  "FallenC_SA4": "폴른 커스텀",
  "FallenC_SA5": "폴른 커스텀",
  "PuppHeadC_SA2": "펍 헤드 커스텀",
  "PuppHeadC_SA3": "펍 헤드 커스텀",
  "PuppHeadC_SA4": "펍 헤드 커스텀",
  "PuppHeadC_SA5": "펍 헤드 커스텀",
  "StingerC_SA2": "스팅어 커스텀",
  "StingerC_SA3": "스팅어 커스텀",
  "StingerC_SA4": "스팅어 커스텀",
  "StingerC_SA5": "스팅어 커스텀",
  "AMG11AA_SA2": "대공용 AMG-11",
  "AMG11AA_SA3": "대공용 AMG-11",
  "AMG11AA_SA4": "대공용 AMG-11",
  "AMG11AA_SA5": "대공용 AMG-11",
  "DroneM_SA2": "드론 커스텀",
  "DroneM_SA3": "드론 커스텀",
  "DroneM_SA4": "드론 커스텀",
  "DroneM_SA5": "드론 커스텀",
  "SeljuqA_SA2": "셀주크 커스텀",
  "SeljuqA_SA3": "셀주크 커스텀",
  "SeljuqA_SA4": "셀주크 커스텀",
  "SeljuqA_SA5": "셀주크 커스텀",
  "GigantesC_SA2": "기간테스 커스텀",
  "GigantesC_SA3": "기간테스 커스텀",
  "GigantesC_SA4": "기간테스 커스텀",
  "GigantesC_SA5": "기간테스 커스텀",
  "Tyrant_N": "타이런트",
  "MrAlfred_N": "Mr 알프레드",
  "NightChickSpCH_Challenge1": "솔져 칙",
  "NightChickSpCH_Challenge2": "솔져 칙",
  "EmperorChickSpCH_Challenge1": "분노한 칙 커맨더",
  "EmperorChickSpCH_Challenge2": "분노한 칙 커맨더",
  "Robert_Challenge1": "로버트",
  "Robert_Challenge2": "로버트",
  "Tyrant_Challenge1": "폭군 타이런트",
  "Tyrant_Challenge2": "폭군 타이런트",
  "Fortress_N": "양산형 포트리스",
  "Fortress_TU2": "양산형 포트리스",
  "Fortress_TU3": "양산형 포트리스",
  "Fortress_TU4": "양산형 포트리스",
  "Fortress_TU5": "양산형 포트리스",
  "LemonadeAvatar_N": "레모네이드 아바타",
  "Predator_Challenge3": "프레데터 변종",
  "FABigChick_Challenge3": "FA 빅 칙 알파",
  "FABigChick_Challenge1": "FA 빅 칙 베타",
  "SpectorMS_EW2": "양산형 스펙터",
  "Scout_EV8": "스카우트",
  "LemonadeAvatar_EV8": "레모네이드 아바타",
  "SpectorBS_EV8": "스펙터 BS",
  "LemonadeAvatar_Challenge1": "레모네이드 아바타",
  "LemonadeAvatar_Challenge2": "레모네이드 아바타",
  "LemonadeAvatar_Challenge3": "레모네이드 아바타",
  "LemonadeAvatar_Challenge4": "레모네이드 아바타",
  "Wasp_EV8": "와습",
  "Slasher_N": "슬래셔",
  "Slasher_TU": "슬래셔",
  "Slasher_TU2": "슬래셔",
  "Slasher_TU3": "슬래셔",
  "Slasher_TU4": "슬래셔",
  "Slasher_TU5": "슬래셔",
  "Slasher_B08": "슬래셔",
  "IronPrince_B08": "철의 왕자",
  "LemonadeOmega_N": "레모네이드 오메가",
  "DroneM_B08": "드론 커스텀",
  "StingerC_B08": "스팅어 커스텀",
  "RampartC_B08": "램파트 커스텀",
  "PuppHeadC_B08": "펍 헤드 커스텀",
  "FABigChickSEX_N": "FA 빅 칙 실더 II",
  "FABigChickSEX_TU2": "FA 빅 칙 실더 II",
  "FABigChickSEX_TU3": "FA 빅 칙 실더 II",
  "FABigChickSEX_TU4": "FA 빅 칙 실더 II",
  "FABigChickSEX_TU5": "FA 빅 칙 실더 II",
  "LightningBomberMP_N": "라이트닝 봄버 Type-X",
  "LightningBomberMP_TU2": "라이트닝 봄버 Type-X",
  "LightningBomberMP_TU3": "라이트닝 봄버 Type-X",
  "LightningBomberMP_TU4": "라이트닝 봄버 Type-X",
  "LightningBomberMP_TU5": "라이트닝 봄버 Type-X",
  "SpeakerEx_N": "강화형 스피커",
  "SpeakerEx_TU2": "강화형 스피커",
  "SpeakerEx_TU3": "강화형 스피커",
  "SpeakerEx_TU4": "강화형 스피커",
  "SpeakerEx_TU5": "강화형 스피커",
  "LemonadeOmega_B08": "레모네이드 오메가",
  "FridgerHead_N": "프리져 헤드",
  "FridgerHead_TU": "프리져 헤드",
  "FridgerHead_TU2": "프리져 헤드",
  "FridgerHead_TU3": "프리져 헤드",
  "FridgerHead_TU4": "프리져 헤드",
  "FridgerHead_TU5": "프리져 헤드",
  "FridgerShooter_N": "프리져 슈터",
  "FridgerShooter_TU": "프리져 슈터",
  "FridgerShooter_TU2": "프리져 슈터",
  "FridgerShooter_TU3": "프리져 슈터",
  "FridgerShooter_TU4": "프리져 슈터",
  "FridgerShooter_TU5": "프리져 슈터",
  "FridgerShell_N": "프리져 쉘",
  "FridgerShell_TU": "프리져 쉘",
  "FridgerShell_TU2": "프리져 쉘",
  "FridgerShell_TU3": "프리져 쉘",
  "FridgerShell_TU4": "프리져 쉘",
  "FridgerShell_TU5": "프리져 쉘",
  "FryerHead_N": "프라이어 헤드",
  "FryerHead_TU": "프라이어 헤드",
  "FryerHead_TU2": "프라이어 헤드",
  "FryerHead_TU3": "프라이어 헤드",
  "FryerHead_TU4": "프라이어 헤드",
  "FryerHead_TU5": "프라이어 헤드",
  "FryerShooter_N": "프라이어 슈터",
  "FryerShooter_TU": "프라이어 슈터",
  "FryerShooter_TU2": "프라이어 슈터",
  "FryerShooter_TU3": "프라이어 슈터",
  "FryerShooter_TU4": "프라이어 슈터",
  "FryerShooter_TU5": "프라이어 슈터",
  "FryerShell_N": "프라이어 쉘",
  "FryerShell_TU": "프라이어 쉘",
  "FryerShell_TU2": "프라이어 쉘",
  "FryerShell_TU3": "프라이어 쉘",
  "FryerShell_TU4": "프라이어 쉘",
  "FryerShell_TU5": "프라이어 쉘",
  "NightChickSv_N": "생존형 나이트 칙",
  "NightChickSv_TU": "생존형 나이트 칙",
  "NightChickSv_TU2": "생존형 나이트 칙",
  "NightChickSv_TU3": "생존형 나이트 칙",
  "NightChickSv_TU4": "생존형 나이트 칙",
  "NightChickCSv_N": "생존형 나이트 칙 캐논",
  "NightChickCSv_TU": "생존형 나이트 칙 캐논",
  "NightChickCSv_TU2": "생존형 나이트 칙 캐논",
  "NightChickCSv_TU3": "생존형 나이트 칙 캐논",
  "NightChickCSv_TU4": "생존형 나이트 칙 캐논",
  "NightChickMSv_N": "생존형 나이트 칙 런처",
  "NightChickMSv_TU": "생존형 나이트 칙 런처",
  "NightChickMSv_TU2": "생존형 나이트 칙 런처",
  "NightChickMSv_TU3": "생존형 나이트 칙 런처",
  "NightChickMSv_TU4": "생존형 나이트 칙 런처",
  "NightChickAQG_N": "아쿠아 칙 G",
  "NightChickAQG_TU": "아쿠아 칙 G",
  "NightChickAQG_TU2": "아쿠아 칙 G",
  "NightChickAQG_TU3": "아쿠아 칙 G",
  "NightChickAQG_TU4": "아쿠아 칙 G",
  "ChillerEX_N": "칠러 HV",
  "ChillerEX_TU": "칠러 HV",
  "ChillerEX_TU2": "칠러 HV",
  "ChillerEX_TU3": "칠러 HV",
  "ChillerEX_TU4": "칠러 HV",
  "NightChickAQ_EV9": "아쿠아 칙 Type-X",
  "Drone_EV9": "드론 09",
  "Machina_N": "마키나",
  "Drone_Challenge1": "익스큐셔너",
  "Drone_Challenge2": "이모탈 익스큐셔너"
};