export default [
  {
    "area": "Story",
    "map": 1,
    "loc": "1",
    "spec": 3,
    "title": "비상 상황",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "CoastCity",
    "desc": "드디어 인간을 찾은 바이오로이드들은 자신들을 쫓아온 철충의 포위망을 돌파해 탈출하려 한다.",
    "filename": "Ch01Stage01"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "2",
    "spec": 3,
    "title": "등대로!",
    "face": "DS_Johanna",
    "skin": 0,
    "bg": "Cliff",
    "desc": "본부와의 교신에 실패한 바이오로이드들은 마지막 인간을 '그곳'으로 이끈다.",
    "filename": "Ch01Stage02"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "3",
    "spec": 3,
    "title": "등대 아래 비밀기지",
    "face": "PECS_LRL",
    "skin": 0,
    "bg": "SubmarineHangar",
    "desc": "마지막 인간의 안전을 위해 바이오로이드들은 등대로 향한다.",
    "filename": "Ch01Stage03"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "4",
    "spec": 3,
    "title": "구조 신호",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "Ruin",
    "desc": "구조 요청을 받은 바이오로이드들은 자매들을 구하기 위해 움직인다.",
    "filename": "Ch01Stage04"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "5",
    "spec": 3,
    "title": "동맹의 조건",
    "face": "PECS_PuppHead",
    "skin": 0,
    "bg": "1_5_3",
    "desc": "위기에 빠진 기계들을 구출하기 위해 바이오로이드들은 움직인다.",
    "filename": "Ch01Stage05"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "6",
    "spec": 3,
    "title": "미끼",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "Lobby",
    "desc": "바이오로이드들은 포위해 오는 철충을 요격하기 위해 움직인다.",
    "filename": "Ch01Stage06"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "7",
    "spec": 3,
    "title": "교살 밧줄",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "Cliff",
    "desc": "바이오로이드는 자신들을 찾는 철충들을 요격한다.",
    "filename": "Ch01Stage07"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "8",
    "spec": 3,
    "title": "위험한 미끼",
    "face": "DS_Johanna",
    "skin": 0,
    "bg": "Cliff",
    "desc": "바이오로이드들은 함정에 걸린 적을 찾기 위해 움직인다.",
    "filename": "Ch01Stage08"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "3B",
    "spec": 3,
    "title": "포츈의 의뢰 I",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "SubmarineHangar",
    "desc": "포츈은 흩어진 바이오로이드들을 찾기 위한 전투를 부탁한다.",
    "filename": "Ch01Stage03b"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "4B",
    "spec": 3,
    "title": "포츈의 의뢰 II",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "Ruin",
    "desc": "포츈은 흩어진 자매들을 찾기 위해 소형 신호 발생기 설치를 부탁한다.",
    "filename": "Ch01Stage04b"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "5B",
    "spec": 3,
    "title": "부품 수거",
    "face": "DS_Johanna",
    "skin": 0,
    "bg": "1_5_3",
    "desc": "요안나는 부서진 로봇의 부품 수거를 통해 자원 확충을 건의한다.",
    "filename": "Ch01Stage05b"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "6B",
    "spec": 3,
    "title": "독안에 든 쥐",
    "face": "DS_Johanna",
    "skin": 0,
    "bg": "Lobby",
    "desc": "요안나는 고립된 스토커의 부하들을 섬멸해 섬을 차지할 것을 건의한다.",
    "filename": "Ch01Stage06b"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "1Ex",
    "spec": 3,
    "title": "싸이클롭스의 보물",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "SubmarineHangar",
    "desc": "LRL은 자신의 숨겨진 유실물을 찾아달라고 부탁한다.",
    "filename": "Ch01Stage03e"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "2Ex",
    "spec": 3,
    "title": "또 다른 괴물",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "Ruin",
    "desc": "그리폰과 요안나는 또 다른 빅칙의 위치를 찾고 그 빅칙을 파괴할 것을 건의한다.",
    "filename": "Ch01Stage04e"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "3Ex",
    "spec": 3,
    "title": "표본 수집",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "1_5_3",
    "desc": "포츈은 철충의 감염 프로세스를 연구하기 위해 그 표본을 구해달라고 부탁한다.",
    "filename": "Ch01Stage05e"
  },
  {
    "area": "Story",
    "map": 1,
    "loc": "4Ex",
    "spec": 3,
    "title": "잔당 처치",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "Cliff",
    "desc": "그리폰은 스토커의 남은 친위대를 파괴해 이 지역에 대한 위협을 완전히 종식시키자는 부탁을 한다.",
    "filename": "Ch01Stage07e"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "1",
    "spec": 3,
    "title": "유전자 저장소",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "Ruin",
    "desc": "바이오로이드는 새로운 동료를 만들기 위해 나선다.",
    "filename": "Ch02Stage01"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "2",
    "spec": 3,
    "title": "수소 전지 저장고",
    "face": "BR_Amy",
    "skin": 0,
    "bg": "Ruin",
    "desc": "전쟁을 위해 마지막 인간과 바이오로이드는 동력을 찾기 위해 나선다.",
    "filename": "Ch02Stage02"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "3",
    "spec": 3,
    "title": "디너 파티",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "Lobby",
    "desc": "마지막 인간은 전쟁을 지속하기 위한 영양원을 찾기 위해 바이오로이드를 파견한다.",
    "filename": "Ch02Stage03"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "4",
    "spec": 3,
    "title": "그리운 옛 집",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "2_4_2",
    "desc": "녹음된 소리를 듣고 바이오로이드는 불굴의 마리를 찾기 위해 움직인다.",
    "filename": "Ch02Stage04"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "5",
    "spec": 3,
    "title": "헤파이스 철공소",
    "face": "PECS_LRL",
    "skin": 0,
    "bg": "2_5_3",
    "desc": "바이오로오이드는 불굴의 마리의 뒤를 쫓는다.",
    "filename": "Ch02Stage05"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "6",
    "spec": 3,
    "title": "오염된 공장",
    "face": "BR_Amy",
    "skin": 0,
    "bg": "2_6_3",
    "desc": "바이오로이드는 오염된 공장에서 믿을 수 없는 광경을 목격하게 된다.",
    "filename": "Ch02Stage06"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "7",
    "spec": 3,
    "title": "마리의 표식",
    "face": "PECS_CoCoWhiteShell",
    "skin": 0,
    "bg": "Lobby",
    "desc": "바이오로이드는 위급한 동료를 구하기 위해 달려간다.",
    "filename": "Ch02Stage07"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "8",
    "spec": 3,
    "title": "장군의 은신처",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "2_8_2",
    "desc": "불굴의 마리를 찾기 위해 바이오로이드는 전장으로 향한다.",
    "filename": "Ch02Stage08"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "1B",
    "spec": 3,
    "title": "배양 촉매",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "Ruin",
    "desc": "포츈은 좀 더 빠른 바이오로이드 제작을 위해 배양 촉매를 구해 줄 것을 부탁한다.",
    "filename": "Ch02Stage01b"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "3B",
    "spec": 3,
    "title": "참치를 위하여 I",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "Lobby",
    "desc": "그리폰은 참치캔이란 음식에 대한 이야기를 듣고 그 참치캔을 구해 보자는 말을 한다.",
    "filename": "Ch02Stage03b"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "4B",
    "spec": 3,
    "title": "참치를 위하여 II",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "2_4_2",
    "desc": "그리폰에게 참치를 빼앗긴 LRL은 또 다른 참치를 구해달라는 부탁을 한다.",
    "filename": "Ch02Stage04b"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "7B",
    "spec": 3,
    "title": "잔해 연구",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "Lobby",
    "desc": "포츈은 철충을 먹는 프레데터의 잔해 조사를 샘플을 부탁한다.",
    "filename": "Ch02Stage07b"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "1Ex",
    "spec": 3,
    "title": "포츈의 참치 연구 I",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "Lobby",
    "desc": "포츈은 자신의 위상을 회복하기 위해 참치를 만들려 알루미늄을 구하려 한다.",
    "filename": "Ch02Stage03e"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "2Ex",
    "spec": 3,
    "title": "포츈의 참치 연구 II",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "2_4_2",
    "desc": "포츈은 참치를 잡기 위해 어종 유도기를 원한다.",
    "filename": "Ch02Stage04e"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "3Ex",
    "spec": 3,
    "title": "참치 파티",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "2_5_3",
    "desc": "포츈은 파티를 위한 캔따개를 부탁한다.",
    "filename": "Ch02Stage05e"
  },
  {
    "area": "Story",
    "map": 2,
    "loc": "4Ex",
    "spec": 3,
    "title": "스틸라인 병사수첩",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "Lobby",
    "desc": "불굴의 마리는 부하들의 용기를 기리고 정신교육을 위한 병사 수첩 회수를 부탁한다.",
    "filename": "Ch02Stage07e"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "1",
    "spec": 3,
    "title": "마리가 본 것",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "3_1_2",
    "desc": "마리가 목격한 수상한 장소를 찾기 위해 바이오로이드는 헤맨다.",
    "filename": "Ch03Stage01"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "2",
    "spec": 3,
    "title": "에이다 통신",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "3_2_2",
    "desc": "실험장 내부에서 벌어지는 일을 위해 바이오로이드들은 실험장 내부로 향한다.",
    "filename": "Ch03Stage02"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "3",
    "spec": 3,
    "title": "81번 실험장 내부",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "3_3_3",
    "desc": "실험장 내부의 데이터를 찾기 위해 바이오로이드들은 수색한다.",
    "filename": "Ch03Stage03"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "4",
    "spec": 3,
    "title": "사라진 실험체",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "3_4_2",
    "desc": "패스파인더의 진입을 위해 바이오로이드들은 내부의 철충을 청소한다.",
    "filename": "Ch03Stage04"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "5",
    "spec": 3,
    "title": "조력자",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "3_5_2",
    "desc": "포츈이 준 단서를 확인하기 위해 바이오로이드들은 움직인다.",
    "filename": "Ch03Stage05"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "6",
    "spec": 3,
    "title": "일보후퇴",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "3_6_3",
    "desc": "갑작스럽게 증원된 적의 병력을 차단하기 위해 바이오로이드들은 고갯길 진지로 향한다",
    "filename": "Ch03Stage06"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "7",
    "spec": 3,
    "title": "철충이 찾는 것",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "3_7_2",
    "desc": "갑작스레 나타난 트릭스터를 쫓아 바이오로이드는 다시 실험장으로 향한다.",
    "filename": "Ch03Stage07"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "8",
    "spec": 3,
    "title": "트릭스터 사냥",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "3_8_2",
    "desc": "바이오로이드들은 실험체를 훔친 트릭스터를 쫓는다.",
    "filename": "Ch03Stage08"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "2B",
    "spec": 3,
    "title": "지구의 감시자",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "3_2_2",
    "desc": "코코는 인간을 위해 우주에 있는 자매들을 다시 되돌려 달라고 에이다에게 부탁한다.",
    "filename": "Ch03Stage02b"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "3B",
    "spec": 3,
    "title": "귀신 이야기",
    "face": "BR_Tomoe",
    "skin": 0,
    "bg": "3_3_3",
    "desc": "토모와 LRL은 귀신 이야기를 하다가 두려움에 떨며 야간 수색에 나선다.",
    "filename": "Ch03Stage03b"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "6B",
    "spec": 3,
    "title": "전면 공습",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "3_6_3",
    "desc": "마리는 고갯글의 진지를 보강하기 위해 입구 고개의 적을 공격하자고 건의한다.",
    "filename": "Ch03Stage06b"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "7B",
    "spec": 3,
    "title": "내부 청소",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "3_7_2",
    "desc": "마리는 내부 콘솔 자료의 보강을 위해 실험장 내부의 적들을 처리하자고 건의한다.",
    "filename": "Ch03Stage07b"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "1Ex",
    "spec": 3,
    "title": "실험 기록 (1)",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "3_3_3",
    "desc": "포츈은 남성 바이오로이드에 대한 실험 기록 수집을 부탁한다.",
    "filename": "Ch03Stage03e"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "2Ex",
    "spec": 3,
    "title": "실험 기록 (2)",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "3_4_2",
    "desc": "포츈은 폭동을 일으켜 격리된 바이오로이드들에 대한 실험 자료를 부탁한다.",
    "filename": "Ch03Stage04e"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "3Ex",
    "spec": 3,
    "title": "실험 기록 (3)",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "3_5_2",
    "desc": "포츈에게 실험 기록에 대한 보고를 받던 중 발생한 습격에 반격하기 위해 바이오로이드들은 전투에 나선다.",
    "filename": "Ch03Stage05e"
  },
  {
    "area": "Story",
    "map": 3,
    "loc": "4Ex",
    "spec": 3,
    "title": "실험 기록 (4)",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "3_7_2",
    "desc": "포츈은 실험장에 어울리지 않는 VIP 객실에 대한 자료를 통해 실험의 비밀을 알아내려 한다.",
    "filename": "Ch03Stage07e"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "1",
    "spec": 3,
    "title": "숨겨진 굴",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "4_1_2",
    "desc": "바이오로이드들은 사라진 트릭스터의 행방을 쫓는다.",
    "filename": "Ch04Stage01"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "2",
    "spec": 3,
    "title": "지하수로",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "4_2_2",
    "desc": "바이오로이드들은 트릭스터가 사라진 지하수로로의 진입을 결정한다.",
    "filename": "Ch04Stage02"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "3",
    "spec": 3,
    "title": "탐사 드론 신호기",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "4_3_2",
    "desc": "패스파인더의 신호를 받기 위한 신호기를 설치하기 위해 바이오로이드들은 내부로 향한다.",
    "filename": "Ch04Stage03"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "4",
    "spec": 3,
    "title": "차단 해소",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "4_4_2",
    "desc": "바이오로이드들은 패스파인더 출진을 위해 드론 기지를 위협하는 철충을 요격한다.",
    "filename": "Ch04Stage04"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "5",
    "spec": 3,
    "title": "안전 수송",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "Lobby",
    "desc": "패스파인더 드론의 안전한 이동을 위해 바이오로이드들은 철충을 청소한다.",
    "filename": "Ch04Stage05"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "6",
    "spec": 3,
    "title": "숨겨진 층계",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "4_6_2",
    "desc": "숨겨진 층계를 찾은 바이오로이드들은 그곳을 확인하기 위해 움직인다.",
    "filename": "Ch04Stage06"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "7",
    "spec": 3,
    "title": "지하 특급",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "4_7_2",
    "desc": "잠긴 문 앞에서 돌아선 바이오로이드들은 다시 트릭스터를 쫓기 위해 움직인다.",
    "filename": "Ch04Stage07"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "8",
    "spec": 3,
    "title": "철길 위에서",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "4_8_2",
    "desc": "철로 위에서 바이오로이드들은 습격을 받는다.",
    "filename": "Ch04Stage08"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "1B",
    "spec": 3,
    "title": "세력 재건",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "4_1_2",
    "desc": "콘스탄챠는 라비아타를 찾기 위한 수색조를 부탁한다.",
    "filename": "Ch04Stage01b"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "2B",
    "spec": 3,
    "title": "라비아타의 행보",
    "face": "3P_Vanilla",
    "skin": 0,
    "bg": "4_2_2",
    "desc": "새로 합류한 바닐라는 라비아타를 찾을 단서를 주고 그녀의 수색을 부탁한다.",
    "filename": "Ch04Stage02b"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "3B",
    "spec": 3,
    "title": "두 번째 굴",
    "face": "PECS_LRL",
    "skin": 0,
    "bg": "4_3_2",
    "desc": "LRL은 라비아타를 찾을 새로운 단서를 제시하고 바이오로이드들은 그곳으로 향한다.",
    "filename": "Ch04Stage03b"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "6B",
    "spec": 3,
    "title": "통신 재개",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "4_6_2",
    "desc": "포츈은 통신을 재개할 방법을 바이오로이드들에게 내놓는다.",
    "filename": "Ch04Stage06b"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "1Ex",
    "spec": 3,
    "title": "승리의 단서",
    "face": "3P_Labiata",
    "skin": 0,
    "bg": "4_1_2",
    "desc": "연결에 성공한 라비아타는 자신의 뒤를 끊어줄 것을 부탁한다.",
    "filename": "Ch04Stage01e"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "2Ex",
    "spec": 3,
    "title": "사라진 그녀",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "4_3_2",
    "desc": "갑자기 라비아타의 통신이 끊기고 콘스탄챠는 그곳을 수색하기 위해 나선다.",
    "filename": "Ch04Stage03e"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "3Ex",
    "spec": 3,
    "title": "대공포 설치",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "3_5_2",
    "desc": "마리는 철로와 지하 수로의 안전을 위해 대공포의 설치를 건의한다.",
    "filename": "Ch04Stage05e"
  },
  {
    "area": "Story",
    "map": 4,
    "loc": "4Ex",
    "spec": 3,
    "title": "열차 강도",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "3_7_2",
    "desc": "콘스탄챠는 열차의 안전을 위해 호위대의 편성을 건의한다.",
    "filename": "Ch04Stage07e"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "1",
    "spec": 3,
    "title": "역사 건너편",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "5_1_3",
    "desc": "건너편 역사에 도착한 바이오로이드들은 미지의 장소에 대한 수색에 나선다.",
    "filename": "Ch05Stage01"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "2",
    "spec": 3,
    "title": "적이 된 로봇",
    "face": "AGS_Aeda",
    "skin": 0,
    "bg": "Lobby",
    "desc": "갑작스럽게 우리를 공격하는 AI를 물리치기 위해 에이다는 적 AI와의 첩촉을 제안한다.",
    "filename": "Ch05Stage02"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "3",
    "spec": 3,
    "title": "1번 서버 구역",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "5_3_3",
    "desc": "포츈은 서버 해킹을 위해 서버실에 통신 연결을 부탁 한다.",
    "filename": "Ch05Stage03"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "4",
    "spec": 3,
    "title": "옆 길 데이터",
    "face": "BR_Amy",
    "skin": 0,
    "bg": "5_3_3",
    "desc": "서버를 부수고 도주한 트릭스터를 유인하기 위해 바이오로이드들은 또 다른 서버를 찾는다.",
    "filename": "Ch05Stage04"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "5",
    "spec": 3,
    "title": "전문가가 필요해!",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "5_5_2",
    "desc": "원활한 해킹을 위해 콘스탄챠는 새로운 전문가를 영입하려 움직인다.",
    "filename": "Ch05Stage05"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "6",
    "spec": 3,
    "title": "스카디",
    "face": "BR_Scathy",
    "skin": 0,
    "bg": "5_6_2",
    "desc": "바이오로이드들은 사고가 난 전문가를 구하기 위해 움직인다.",
    "filename": "Ch05Stage06"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "7",
    "spec": 3,
    "title": "해킹 시작",
    "face": "BR_Scathy",
    "skin": 0,
    "bg": "5_7_2",
    "desc": "구해온 전문가 스카디는 언더와쳐를 해킹하기 위해 움직인다.",
    "filename": "Ch05Stage07"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "8",
    "spec": 3,
    "title": "깊고 깊은 감시자",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "5_8_3",
    "desc": "가장 강력한 무기를 봉인한 언더와쳐를 처치하기 위해 바이오로이드들은 심연으로 향한다.",
    "filename": "Ch05Stage08"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "2B",
    "spec": 3,
    "title": "호환 부품",
    "face": "AGS_Aeda",
    "skin": 0,
    "bg": "Lobby",
    "desc": "에이다는 철충의 부품을 이용해 AGS 로봇을 수리할 것을 건의한다.",
    "filename": "Ch05Stage02b"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "3B",
    "spec": 3,
    "title": "퍼스널 컴퓨터",
    "face": "PECS_LRL",
    "skin": 0,
    "bg": "5_3_3",
    "desc": "LRL은 자신만의 글을 쓸 도구를 찾기 위해 서버실에서 퍼스널 컴퓨터를 구해다 달라고 요청한다.",
    "filename": "Ch05Stage03b"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "6B",
    "spec": 3,
    "title": "전문가가 되고 싶어!",
    "face": "PECS_LRL",
    "skin": 0,
    "bg": "5_6_2",
    "desc": "LRL은 컴퓨터 전문가가 되기 위해서 서적을 구한다.",
    "filename": "Ch05Stage06b"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "7B",
    "spec": 3,
    "title": "너무나 어려운 길",
    "face": "BR_Scathy",
    "skin": 0,
    "bg": "5_7_2",
    "desc": "LRL은 컴퓨터 전문가가 되기 위해서 스카디에게 배움을 요청한다.",
    "filename": "Ch05Stage07b"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "1Ex",
    "spec": 3,
    "title": "전쟁 기록 (1)",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "5_1_3",
    "desc": "콘스탄챠는 생필품 모사를 위해 거주 지역 내의 생필품을 구할 것을 요청한다.",
    "filename": "Ch05Stage01e"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "2Ex",
    "spec": 3,
    "title": "전쟁 기록 (2)",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "Lobby",
    "desc": "마리는 거주지역에서 구한 숨겨진 무기에 대한 이야기를 듣고 숨겨진 구역으로 향한다.",
    "filename": "Ch05Stage02e"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "3Ex",
    "spec": 3,
    "title": "전쟁 기록 (3)",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "5_3_3",
    "desc": "마리는 휩노스 병에 대한 자료를 구하기 위해 새로운 서버로 향한다.",
    "filename": "Ch05Stage03e"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "4Ex",
    "spec": 3,
    "title": "최초의 바이오로이드",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "5_3_3",
    "desc": "마리는 에바가 휩노스 병에 걸렸다는 기록을 읽고 그녀가 숨겨져 있던 구역으로 향한다.",
    "filename": "Ch05Stage04e"
  },
  {
    "area": "Story",
    "map": 5,
    "loc": "8Ex",
    "spec": 3,
    "title": "한 대 더!",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "5_8_3",
    "desc": "심층을 정찰 중 발견된 언더와쳐 예비기. 바이오로이드들은 움직이기 시작한 언더와쳐를 파괴하기 위해 움직인다.",
    "filename": "Ch05Stage08e"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "1",
    "spec": 3,
    "title": "봉인된 연구실",
    "face": "BR_Scathy",
    "skin": 0,
    "bg": "6_1_2",
    "desc": "스카디와 콘스탄챠는 가상현실 접속기의 정보를 찾는다.",
    "filename": "Ch06Stage01"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "2",
    "spec": 3,
    "title": "아미나 존스의 마지막 금고",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "6_2_2",
    "desc": "바이오로이드들은 금고라 불리는 유산을 찾기 위해 가상 현실 공간으로 향한다.",
    "filename": "Ch06Stage02"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "3",
    "spec": 3,
    "title": "얼음 무덤",
    "face": "PECS_Fortune",
    "skin": 0,
    "bg": "Lobby",
    "desc": "일행은 트릭스터의 흔적을 찾아 연구소로 향한다.",
    "filename": "Ch06Stage03"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "4",
    "spec": 3,
    "title": "에바의 기억 : 첫 번째",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "6_4_2",
    "desc": "라비아타가 남긴 흔적을 따라 일행은 가상현실 공간을 수색한다.",
    "filename": "Ch06Stage04"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "5",
    "spec": 3,
    "title": "에바의 기억 : 아미나",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "6_5_2",
    "desc": "일행은 에바 존스의 데이터를 수집하기 위해 출발한다.",
    "filename": "Ch06Stage05"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "6",
    "spec": 3,
    "title": "에바의 기억 : 인간의 창조",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "6_6_2",
    "desc": "콘스탄챠는 라비아타를 만나기 위해 출발한다.",
    "filename": "Ch06Stage06"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "7",
    "spec": 3,
    "title": "라비아타의 은신처",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "Lobby",
    "desc": "라비아타와 콘스탄챠는 오르카로 향한다.",
    "filename": "Ch06Stage07"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "8",
    "spec": 3,
    "title": "새로운 육체",
    "face": "3P_Labiata",
    "skin": 0,
    "bg": "6_8_2",
    "desc": "라비아타와 콘스탄챠는 또 다른 가능성을 찾아 출발한다.",
    "filename": "Ch06Stage08"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "1B",
    "spec": 3,
    "title": "남자들이란…",
    "face": "BR_NightAngel",
    "skin": 0,
    "bg": "6_1_2",
    "desc": "둠 브링어 팀은 백업을 위해 가상 현실 공간으로 향한다.",
    "filename": "Ch06Stage01b"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "2B",
    "spec": 3,
    "title": "누군가의 테스트",
    "face": "BR_NightAngel",
    "skin": 0,
    "bg": "6_2_2",
    "desc": "둠 브링어 팀은 적을 포착하기 위해 가상 현실 공간으로 향한다.",
    "filename": "Ch06Stage02b"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "5B",
    "spec": 3,
    "title": "그림자",
    "face": "BR_NightAngel",
    "skin": 0,
    "bg": "6_5_2",
    "desc": "메이는 최선의 방법을 찾기위해 고민한다.",
    "filename": "Ch06Stage05b"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "6B",
    "spec": 3,
    "title": "근접위험통보",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "6_6_2",
    "desc": "둠 브링어 팀은 위험이 될 요소를 제거하기 위해 가상 현실 공간으로 향한다.",
    "filename": "Ch06Stage06b"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "1Ex",
    "spec": 3,
    "title": "그리폰의 마음",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "6_1_2",
    "desc": "그리폰은 잃어버린 물건을 찾기 위해 단독 출격을 요청한다.",
    "filename": "Ch06Stage01e"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "2Ex",
    "spec": 3,
    "title": "보병 분대",
    "face": "BR_Brownie",
    "skin": 0,
    "bg": "6_1_2",
    "desc": "스틸라인의 분대원들은 정찰 임무를 수행하기 위해 출발한다.",
    "filename": "Ch06Stage04e"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "3Ex",
    "spec": 3,
    "title": "연구소 청소",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "6_1_2",
    "desc": "콘스탄챠는 연구소 구역 정리를 위해 출격을 요청한다.",
    "filename": "Ch06Stage05e"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "4Ex",
    "spec": 3,
    "title": "열병",
    "face": "3P_Labiata",
    "skin": 0,
    "bg": "6_1_2",
    "desc": "스카디와 라비아타는 콘스탄챠의 긴급 호출을 받고 오르카로 복귀한다.",
    "filename": "Ch06Stage08e"
  },
  {
    "area": "Story",
    "map": 6,
    "loc": "8Ex",
    "spec": 3,
    "title": "선제 공격",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "6_8_3",
    "desc": "콘스탄챠는 사령관의 의식이 없는 중에 철충의 공격을 대비한다.",
    "filename": "Ch06Stage09e"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "1",
    "spec": 3,
    "title": "심연의 악몽",
    "face": "BR_Marie",
    "skin": 0,
    "bg": "7_2",
    "desc": "바이오로이드들은 마리의 지휘 아래 작전 구역으로 향한다.",
    "filename": "Ch07Stage01"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "2",
    "spec": 3,
    "title": "심해의 부름",
    "face": "BR_DrM",
    "skin": 0,
    "bg": "7_2",
    "desc": "혼란에 빠진 마지막 인간에게 에바의 통신 요청이 들어온다.",
    "filename": "Ch07Stage02"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "3",
    "spec": 3,
    "title": "고도의 스피커",
    "face": "BR_Blackhound",
    "skin": 0,
    "bg": "Cut_7C3S_RoyalArsenal",
    "desc": "작전 구역을 정찰하던 바이오로이드들의 앞에 새로운 적이 등장한다.",
    "filename": "Ch07Stage03"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "4",
    "spec": 3,
    "title": "진실의 말",
    "face": "BR_DrM",
    "skin": 0,
    "bg": "Lobby",
    "desc": "스피커에 대한 정보를 얻기 위해 바이오로이드들은 전장으로 향한다.",
    "filename": "Ch07Stage04"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "5",
    "spec": 3,
    "title": "플리트 콜",
    "face": "BR_Scathy",
    "skin": 0,
    "bg": "7_5",
    "desc": "바이오로이드들은 철충이 보내는 신호를 추적한다.",
    "filename": "Ch07Stage05"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "6",
    "spec": 3,
    "title": "함대를 향하여!",
    "face": "BR_Leona",
    "skin": 0,
    "bg": "Cut_7C6S_Room",
    "desc": "바이오로이드들은 해군 시설의 내부로 진입한다.",
    "filename": "Ch07Stage06"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "7",
    "spec": 3,
    "title": "기다림의 시간",
    "face": "BR_May",
    "skin": 0,
    "bg": "7_7",
    "desc": "새로운 주둔지를 확보하기 위해 오르카의 포병이 출격한다.",
    "filename": "Ch07Stage07"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "8",
    "spec": 3,
    "title": "별의 아이",
    "face": "BR_Leona",
    "skin": 0,
    "bg": "7_8_2",
    "desc": "레오나의 교신을 받고 출격한 바이오로이드들은 믿을 수 없는 광경을 목격하게 된다.",
    "filename": "Ch07Stage08"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "3B",
    "spec": 3,
    "title": "실패한 정찰",
    "face": "BR_PA00EL",
    "skin": 0,
    "bg": "7_3",
    "desc": "그리폰은 작전구역의 정찰을 마치고 오르카로 귀환한다.",
    "filename": "Ch07Stage01b"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "4B",
    "spec": 3,
    "title": "제비의 일기",
    "face": "BR_Blackhound",
    "skin": 0,
    "bg": "Lobby",
    "desc": "블랙 하운드는 슬레이프니르에 관한 정보를 얻기 위해 하르페이아를 찾아간다.",
    "filename": "Ch07Stage02b"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "5B",
    "spec": 3,
    "title": "제비의 어둠",
    "face": "BR_Lindwurm",
    "skin": 0,
    "bg": "7_5",
    "desc": "스카이 나이츠 부대원들은 슬레이프니르의 흔적을 찾아 나선다.",
    "filename": "Ch07Stage03b"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "6B",
    "spec": 3,
    "title": "제비 구출",
    "face": "BR_Sleipnir",
    "skin": 0,
    "bg": "7_6_1",
    "desc": "슬레이프니르를 지원하기 위해 스카이 나이츠가 출격한다.",
    "filename": "Ch07Stage04b"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "1Ex",
    "spec": 3,
    "title": "망가진 육체",
    "face": "3P_Labiata",
    "skin": 0,
    "bg": "Lobby",
    "desc": "닥터는 라비아타의 몸에 생긴 이상 현상을 발견한다.",
    "filename": "Ch07Stage01e"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "2Ex",
    "spec": 3,
    "title": "과거의 망령",
    "face": "AGS_Aeda",
    "skin": 0,
    "bg": "7_2",
    "desc": "에이다는 닥터에게 라비아타의 육체를 정상적으로 돌릴 수 있는 방법을 알려준다.",
    "filename": "Ch07Stage02e"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "3Ex",
    "spec": 3,
    "title": "마음 깊은 곳의 병",
    "face": "BR_DrM",
    "skin": 0,
    "bg": "Lobby",
    "desc": "닥터는 라비아타의 마음을 돌릴 방법을 찾기 위해 콘스탄챠와 레아를 찾아간다.",
    "filename": "Ch07Stage03e"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "4Ex",
    "spec": 3,
    "title": "그녀를 꼼짝 못하게 하는 방법",
    "face": "3P_ConstantiaS2",
    "skin": 0,
    "bg": "Lobby",
    "desc": "콘스탄챠는 라비아타를 위한 특수 임무를 계획한다.",
    "filename": "Ch07Stage04e"
  },
  {
    "area": "Story",
    "map": 7,
    "loc": "8Ex",
    "spec": 3,
    "title": "여왕의 복수",
    "face": "BR_May",
    "skin": 0,
    "bg": "7_8_3",
    "desc": "새롭게 등장한 네스트로 인해 바이오로이드들은 큰 혼란에 빠진다.",
    "filename": "Ch07Stage05e"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "1",
    "spec": 3,
    "title": "북극의 펭귄",
    "face": "PECS_Empress",
    "skin": 0,
    "bg": "8_1",
    "desc": "남극이든 북극이든 추우면 된 거 아닐까?",
    "filename": "Ch08Stage01"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "2",
    "spec": 3,
    "title": "유적의 갈림길",
    "face": "PECS_Azaz",
    "skin": 0,
    "bg": "8_2",
    "desc": "오메가의 눈은 어디에나 있습니다.",
    "filename": "Ch08Stage02"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "3",
    "spec": 3,
    "title": "제각각의 마음",
    "face": "PECS_Audrey",
    "skin": 0,
    "bg": "8_3",
    "desc": "물자는 아껴 쓰셔야 해요.",
    "filename": "Ch08Stage03"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "4",
    "spec": 3,
    "title": "성대한 환영",
    "face": "PECS_Ignis",
    "skin": 0,
    "bg": "8_4",
    "desc": "오메가는 스스로를 되돌아보는 시간을 가질 필요가 있어보이네요.",
    "filename": "Ch08Stage04"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "5",
    "spec": 3,
    "title": "적의 적",
    "face": "PECS_LemonadeAlpha",
    "skin": 0,
    "bg": "8_5",
    "desc": "적의 적은 친구라는 말이 있죠.",
    "filename": "Ch08Stage05"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "6",
    "spec": 3,
    "title": "알파와 오메가",
    "face": "PECS_LemonadeAlpha",
    "skin": 0,
    "bg": "8_6",
    "desc": "지긋지긋한 악연을 끊기 위해 알파는 사령관에게 도움을 청합니다.",
    "filename": "Ch08Stage06"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "7",
    "spec": 3,
    "title": "재돌입",
    "face": "3P_Labiata",
    "skin": 21,
    "bg": "8_7",
    "desc": "관문 하나를 사이에 두고, 오메가는 사령관을 기다리고 있습니다.",
    "filename": "Ch08Stage07"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "8",
    "spec": 3,
    "title": "부활의 요람",
    "face": "PECS_LemonadeAlpha",
    "skin": 0,
    "bg": "8_8",
    "desc": "사건은 아직 끝나지 않았습니다.",
    "filename": "Ch08Stage08"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "2B",
    "spec": 3,
    "title": "해체자",
    "face": "BR_Miho",
    "skin": 0,
    "bg": "8_2",
    "desc": "몽구스 팀은 평소에 어떤 이야기를 나누고 있을까요?",
    "filename": "Ch08Stage01b"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "3B",
    "spec": 3,
    "title": "강행돌파",
    "face": "BR_PoniesAnger",
    "skin": 20,
    "bg": "8_4",
    "desc": "상위 바이오로이드의 성격이 어딘가 특이한건 이제 놀랄 일도 아니죠.",
    "filename": "Ch08Stage02b"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "4B",
    "spec": 3,
    "title": "합동 작전",
    "face": "PECS_Sadius",
    "skin": 0,
    "bg": "8_5",
    "desc": "공권력은 오르카에 여전히 살아 있습니다.",
    "filename": "Ch08Stage03b"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "5B",
    "spec": 3,
    "title": "포로 처분",
    "face": "BR_HongRyun",
    "skin": 0,
    "bg": "8_1",
    "desc": "누가 누굴 잡은 건지 모르겠네요.",
    "filename": "Ch08Stage04b"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "1Ex",
    "spec": 3,
    "title": "유적 조사",
    "face": "3P_Labiata",
    "skin": 0,
    "bg": "8_7",
    "desc": "유적에는 아직 쓸만한 것들이 남아 있습니다.",
    "filename": "Ch08Stage01e"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "2Ex",
    "spec": 3,
    "title": "철충의 탑",
    "face": "PECS_Leanne",
    "skin": 0,
    "bg": "8_5",
    "desc": "아무리 거대한 적이라도 심장을 찔리면 쓰러지는 법.",
    "filename": "Ch08Stage02e"
  },
  {
    "area": "Story",
    "map": 8,
    "loc": "8Ex",
    "spec": 3,
    "title": "신세계의 신",
    "face": "PECS_LemonadeAlpha",
    "skin": 0,
    "bg": "Cut_Revive",
    "desc": "메시아가 되고 싶었던 청년은, 신세계의 신이 되었다.",
    "filename": "Ch08Stage09"
  }
];