// Content automatically generated by tools/locale.js -- do not edit.
export interface LocaleChunkManifest {
	readonly files: readonly string[];
	readonly groups: Readonly<Record<string, readonly string[]>>;
	readonly prefixes: Readonly<Record<string, string>>;
}

const manifest = {
	"files": [
		"CORE",
		"UNIT",
		"UNIT_DETAIL_00",
		"UNIT_DETAIL_01",
		"SKILL_00",
		"SKILL_01",
		"SKILL_02",
		"SKILL_03",
		"EFFECT_00",
		"EFFECT_01",
		"EFFECT_02",
		"EFFECT_03",
		"EFFECT_04",
		"EFFECT_05",
		"EFFECT_06",
		"EFFECT_07",
		"EFFECT_08",
		"EFFECT_09",
		"EFFECT_10",
		"EFFECT_11",
		"CONSUMABLE_00",
		"CONSUMABLE_01",
		"CONSUMABLE_DETAIL_00",
		"CONSUMABLE_DETAIL_01",
		"CONSUMABLE_DETAIL_02",
		"CONSUMABLE_DETAIL_03",
		"EQUIP",
		"ENEMY",
		"ENEMY_DETAIL_00",
		"ENEMY_DETAIL_01",
		"WORLD",
		"WORLD_MAP_00",
		"WORLD_MAP_01",
		"STORY",
		"MODE",
		"MEDIA",
		"MISC"
	],
	"groups": {
		"CORE": [
			"CORE"
		],
		"UNIT": [
			"UNIT"
		],
		"UNIT_DETAIL": [
			"UNIT_DETAIL_00",
			"UNIT_DETAIL_01"
		],
		"SKILL": [
			"SKILL_00",
			"SKILL_01",
			"SKILL_02",
			"SKILL_03"
		],
		"EFFECT": [
			"EFFECT_00",
			"EFFECT_01",
			"EFFECT_02",
			"EFFECT_03",
			"EFFECT_04",
			"EFFECT_05",
			"EFFECT_06",
			"EFFECT_07",
			"EFFECT_08",
			"EFFECT_09",
			"EFFECT_10",
			"EFFECT_11"
		],
		"CONSUMABLE": [
			"CONSUMABLE_00",
			"CONSUMABLE_01"
		],
		"CONSUMABLE_DETAIL": [
			"CONSUMABLE_DETAIL_00",
			"CONSUMABLE_DETAIL_01",
			"CONSUMABLE_DETAIL_02",
			"CONSUMABLE_DETAIL_03"
		],
		"EQUIP": [
			"EQUIP"
		],
		"ENEMY": [
			"ENEMY"
		],
		"ENEMY_DETAIL": [
			"ENEMY_DETAIL_00",
			"ENEMY_DETAIL_01"
		],
		"WORLD": [
			"WORLD"
		],
		"WORLD_MAP": [
			"WORLD_MAP_00",
			"WORLD_MAP_01"
		],
		"STORY": [
			"STORY"
		],
		"MODE": [
			"MODE"
		],
		"MEDIA": [
			"MEDIA"
		],
		"MISC": [
			"MISC"
		]
	},
	"prefixes": {
		"SUITABILITYGROUP": "MODE",
		"SUITABILITYSTAGE": "MODE",
		"BUFFTRIGGERDESC": "EFFECT",
		"CONSUMABLE_DESC": "CONSUMABLE_DETAIL",
		"STORYGROUPNAME": "STORY",
		"UNIT_DIALOGUE": "UNIT_DETAIL",
		"BUFFOVERLAP": "EFFECT",
		"BUFFTRIGGER": "EFFECT",
		"ENEMY_INTRO": "ENEMY_DETAIL",
		"PROHIBITION": "EFFECT",
		"ANCIENTBOX": "EQUIP",
		"BUFFCHANCE": "EFFECT",
		"BUFFEFFECT": "EFFECT",
		"BUFFTARGET": "EFFECT",
		"CONSUMABLE": "CONSUMABLE",
		"UNIT_INTRO": "UNIT_DETAIL",
		"UNIT_SKILL": "SKILL",
		"BUFFERASE": "EFFECT",
		"BUFFPOINT": "EFFECT",
		"BUFFSTACK": "EFFECT",
		"CHANGELOG": "CORE",
		"LINKBONUS": "UNIT",
		"ROGUELIKE": "MODE",
		"SIMULATOR": "MODE",
		"UNIT_SKIN": "UNIT_DETAIL",
		"WORLD_MAP": "WORLD_MAP",
		"BUFFFROM": "EFFECT",
		"BUFFTYPE": "EFFECT",
		"EXCHANGE": "EQUIP",
		"FACILITY": "MISC",
		"IWSEASON": "MODE",
		"RESEARCH": "MISC",
		"SUBSTORY": "STORY",
		"ANOMALY": "MODE",
		"ENEMIES": "ENEMY",
		"EXPCALC": "MISC",
		"LOBBYBG": "MEDIA",
		"MISSION": "STORY",
		"PCSTORY": "STORY",
		"TRSTAGE": "MODE",
		"COMMON": "CORE",
		"EFFECT": "EFFECT",
		"SEARCH": "UNIT",
		"SERACH": "UNIT",
		"SUMMON": "ENEMY",
		"WORLDS": "WORLD",
		"ENEMY": "ENEMY",
		"EQUIP": "EQUIP",
		"GACHA": "MODE",
		"POPUP": "CORE",
		"SKILL": "SKILL",
		"STORY": "STORY",
		"UNITS": "UNIT",
		"WORLD": "WORLD",
		"BUFF": "EFFECT",
		"FACE": "UNIT",
		"HOME": "CORE",
		"ITEM": "EQUIP",
		"MENU": "CORE",
		"PROP": "EQUIP",
		"SKIN": "UNIT",
		"TIME": "CORE",
		"UNIT": "UNIT",
		"BGM": "MEDIA",
		"AI": "ENEMY",
		"BG": "MEDIA",
		"EW": "MODE",
		"IW": "MODE"
	}
} as const satisfies LocaleChunkManifest;

export default manifest;
