"use strict";
exports.__esModule = true;
exports.ROGUE_SKILL_TYPE = exports.ROGUEEFFECTTYPE = exports.ROGUE_CELL_TYPE = exports.ROGUE_QUEST_OBJECT_TYPE = exports.ROGUE_LIMIT_EFFECT_TYPE = exports.ROGUE_LIMIT_EFFECT_SHOW_TYPE = exports.ROGUE_LIMIT_EFFECT_OVERLAP = exports.ROGUE_LIMIT_EFFECT_CONDITION = exports.ROGUE_LIMIT_EFFECT_CATEGORY = exports.CURRENCY_TYPE = exports.INSTALL_POS_TYPE = exports.SUMMON_TYPE = exports.MONSTER_SUB_TYPE = exports.MONSTER_TYPE = exports.ITEM_USE_TYPE = exports.REQUIRED_COMBATANT_TYPE = exports.PRODUCE_TYPE = exports.PASSIVE_BUFF_TYPE = exports.FACILITY_TYPE_CATEGORY = exports.BUFF_ANNOUNCE_TYPE = exports.MULTI_ATTACK_TYPE = exports.SKILL_ATTR = exports.SKILL_SLOT_TYPE = exports.SKILL_SUB_TYPE = exports.SKILL_TYPE = exports.SKILL_LEVEL_TYPE = exports.TARGET_SUB_TYPE = exports.TARGET_TYPE = exports.NUM_OUTPUTTYPE = exports.ACTOR_GRADE = exports.ROLE_TYPE = exports.ACTOR_CLASS = exports.ACTOR_BODY_TYPE = exports.ITEM_EQUIP_TYPE = exports.ITEM_SUB_TYPE = exports.ITEM_TYPE = exports.BUFF_OVERLAP_TYPE = exports.BUFFEFFECT_TRIGGER_APPLY_CONDITION = exports.BUFF_ATTR_TYPE = exports.BUFF_USE_TYPE = exports.ACTOR_ATTR_TYPE = exports.UNIT_POSITION = void 0;
/**
 * 유닛이 위치한 열
 */
var UNIT_POSITION;
(function (UNIT_POSITION) {
    UNIT_POSITION[UNIT_POSITION["FRONT"] = 0] = "FRONT";
    UNIT_POSITION[UNIT_POSITION["MIDDLE"] = 1] = "MIDDLE";
    UNIT_POSITION[UNIT_POSITION["BACK"] = 2] = "BACK";
})(UNIT_POSITION = exports.UNIT_POSITION || (exports.UNIT_POSITION = {}));
/**
 * 장비 증감 수치 (인게임 버프 아님)
 */
var ACTOR_ATTR_TYPE;
(function (ACTOR_ATTR_TYPE) {
    /** 공격력 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["ATK"] = 0] = "ATK";
    /** 방어력 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["DEF"] = 1] = "DEF";
    /** 체력 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["HP"] = 2] = "HP";
    /** 회피 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["EVADE"] = 3] = "EVADE";
    /** 행동력 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["TURNSPEED"] = 4] = "TURNSPEED";
    /** 치명타 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["CRI"] = 5] = "CRI";
    /** 적중률 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["APPLY"] = 6] = "APPLY";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["SKILL_ATTACK_RATE"] = 7] = "SKILL_ATTACK_RATE";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["NONE"] = 8] = "NONE";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["FIRE"] = 9] = "FIRE";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["ICE"] = 10] = "ICE";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["LIGHTNING"] = 11] = "LIGHTNING";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["NONE_RESIST"] = 12] = "NONE_RESIST";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["FIRE_RESIST"] = 13] = "FIRE_RESIST";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["ICE_RESIST"] = 14] = "ICE_RESIST";
    /** ??? 사용처 없음 */
    ACTOR_ATTR_TYPE[ACTOR_ATTR_TYPE["LIGHTNING_RESIST"] = 15] = "LIGHTNING_RESIST";
    // __MAX__ = 16,
})(ACTOR_ATTR_TYPE = exports.ACTOR_ATTR_TYPE || (exports.ACTOR_ATTR_TYPE = {}));
/** 버프 사용 방식? */
var BUFF_USE_TYPE;
(function (BUFF_USE_TYPE) {
    BUFF_USE_TYPE[BUFF_USE_TYPE["TRIGGER"] = 0] = "TRIGGER";
    BUFF_USE_TYPE[BUFF_USE_TYPE["PASSIVE"] = 1] = "PASSIVE";
    // __MAX__ = 2,
})(BUFF_USE_TYPE = exports.BUFF_USE_TYPE || (exports.BUFF_USE_TYPE = {}));
/** 버프 종류 */
var BUFF_ATTR_TYPE;
(function (BUFF_ATTR_TYPE) {
    /** 버프 */
    BUFF_ATTR_TYPE[BUFF_ATTR_TYPE["BUFF"] = 0] = "BUFF";
    /** 디버프 */
    BUFF_ATTR_TYPE[BUFF_ATTR_TYPE["DEBUFF"] = 1] = "DEBUFF";
    /** 사용처 없음 */
    BUFF_ATTR_TYPE[BUFF_ATTR_TYPE["SKILLBUFF"] = 2] = "SKILLBUFF";
    /** 기타 효과 (버프/디버프 조건 충족 안함) */
    BUFF_ATTR_TYPE[BUFF_ATTR_TYPE["ETC"] = 3] = "ETC";
    /** 로그라이크(철의 탑) 버프 */
    BUFF_ATTR_TYPE[BUFF_ATTR_TYPE["ROGUEBUFF"] = 4] = "ROGUEBUFF";
    /** 로그라이크(철의 탑) 디버프 */
    BUFF_ATTR_TYPE[BUFF_ATTR_TYPE["ROGUEDEBUFF"] = 5] = "ROGUEDEBUFF";
    /** 버프 종류 상관하지 않음 */
    BUFF_ATTR_TYPE[BUFF_ATTR_TYPE["NO_MATTER"] = 6] = "NO_MATTER";
    // __MAX__ = 6,
})(BUFF_ATTR_TYPE = exports.BUFF_ATTR_TYPE || (exports.BUFF_ATTR_TYPE = {}));
/** 버프 효과의 발동 조건 */
var BUFFEFFECT_TRIGGER_APPLY_CONDITION;
(function (BUFFEFFECT_TRIGGER_APPLY_CONDITION) {
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_BUFFED_ENUM_ME"] = 0] = "IF_BUFFED_ENUM_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_BUFFED_KEY_ME"] = 1] = "IF_BUFFED_KEY_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["AT_FRONT_ROW_ME"] = 2] = "AT_FRONT_ROW_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["AT_MID_ROW_ME"] = 3] = "AT_MID_ROW_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["AT_BACK_ROW_ME"] = 4] = "AT_BACK_ROW_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["HP_RATIO_UP_ME"] = 5] = "HP_RATIO_UP_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["HP_RATIO_DOWN_ME"] = 6] = "HP_RATIO_DOWN_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["HP_RATIO_LESS_THEN_ME"] = 7] = "HP_RATIO_LESS_THEN_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["HP_RATIO_MORE_THEN_ME"] = 8] = "HP_RATIO_MORE_THEN_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IFBUFF_STACK_COUNT_ME"] = 9] = "IFBUFF_STACK_COUNT_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_BUFFED_ENUM_TARGET"] = 10] = "IF_BUFFED_ENUM_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_BUFFED_KEY_TARGET"] = 11] = "IF_BUFFED_KEY_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["HP_RATIO_UP_TARGET"] = 12] = "HP_RATIO_UP_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["HP_RATIO_DOWN_TARGET"] = 13] = "HP_RATIO_DOWN_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["SPC_CHAR_TARGET"] = 14] = "SPC_CHAR_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["SPC_CHAR_IN_BATTLE"] = 15] = "SPC_CHAR_IN_BATTLE";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["AT_FRONT_ROW_TARGET"] = 16] = "AT_FRONT_ROW_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["AT_MID_ROW_TARGET"] = 17] = "AT_MID_ROW_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["AT_BACK_ROW_TARGET"] = 18] = "AT_BACK_ROW_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_BUFFED_KEY_ME_TOGETHER"] = 19] = "IF_BUFFED_KEY_ME_TOGETHER";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_BUFFED_KEY_COUNT_ME"] = 20] = "IF_BUFFED_KEY_COUNT_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["HP_RATIO_RANGE_ME"] = 21] = "HP_RATIO_RANGE_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_NOT_BUFFED_KEY_ME"] = 22] = "IF_NOT_BUFFED_KEY_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_BUFF_STACK_COUNT_TARGET"] = 23] = "IF_BUFF_STACK_COUNT_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_NOT_BUFFED_KEY_ME_TOGETHER"] = 24] = "IF_NOT_BUFFED_KEY_ME_TOGETHER";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_OTHER_PARTY"] = 25] = "CHECK_COUNT_OTHER_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_MY_PARTY"] = 26] = "CHECK_COUNT_MY_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_ALL_PARTY"] = 27] = "CHECK_COUNT_ALL_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_ROUND_UP"] = 28] = "CHECK_COUNT_ROUND_UP";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_ROUND_DOWN"] = 29] = "CHECK_COUNT_ROUND_DOWN";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["SPC_CHAR_NOT_BATTLE"] = 30] = "SPC_CHAR_NOT_BATTLE";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IFBUFF_COUNT_ME"] = 31] = "IFBUFF_COUNT_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_ROUND"] = 32] = "CHECK_COUNT_ROUND";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_BIO_MY_PARTY"] = 33] = "CHECK_COUNT_BIO_MY_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_AGS_MY_PARTY"] = 34] = "CHECK_COUNT_AGS_MY_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_BIO_ENEMY"] = 35] = "CHECK_COUNT_BIO_ENEMY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_AGS_ENEMY"] = 36] = "CHECK_COUNT_AGS_ENEMY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_BUFFED_KEY_MY_PARTY"] = 37] = "IF_BUFFED_KEY_MY_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_ACTOR_CLASS_MY_PARTY"] = 38] = "CHECK_COUNT_ACTOR_CLASS_MY_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_ROLE_TYPE_MY_PARTY"] = 39] = "CHECK_COUNT_ROLE_TYPE_MY_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_SPC_TROOPCATEGORY_KEY_ME"] = 40] = "IF_SPC_TROOPCATEGORY_KEY_ME";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_ROUND_EVEN_NUMBER"] = 41] = "CHECK_ROUND_EVEN_NUMBER";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_ROUND_ODD_NUMBER"] = 42] = "CHECK_ROUND_ODD_NUMBER";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_ALL_NOT_BUFFED_KEY_TARGET"] = 43] = "IF_ALL_NOT_BUFFED_KEY_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["IF_NOT_BUFFED_KEY_TARGET"] = 44] = "IF_NOT_BUFFED_KEY_TARGET";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_ACTOR_CLASS_ENEMY_PARTY"] = 45] = "CHECK_COUNT_ACTOR_CLASS_ENEMY_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["CHECK_COUNT_ROLE_TYPE_ENEMY_PARTY"] = 46] = "CHECK_COUNT_ROLE_TYPE_ENEMY_PARTY";
    BUFFEFFECT_TRIGGER_APPLY_CONDITION[BUFFEFFECT_TRIGGER_APPLY_CONDITION["ALWAYS"] = 47] = "ALWAYS";
    // __MAX__ = ALWAYS,
})(BUFFEFFECT_TRIGGER_APPLY_CONDITION = exports.BUFFEFFECT_TRIGGER_APPLY_CONDITION || (exports.BUFFEFFECT_TRIGGER_APPLY_CONDITION = {}));
/** 버프 갱신 방식 */
var BUFF_OVERLAP_TYPE;
(function (BUFF_OVERLAP_TYPE) {
    /** 일회성 또는 동일 라운드 지속 버프, `STACK`과 동일하게 처리 */
    BUFF_OVERLAP_TYPE[BUFF_OVERLAP_TYPE["NONE"] = 0] = "NONE";
    /** 기존에 동일한 버프가 없을 때에만 추가 */
    BUFF_OVERLAP_TYPE[BUFF_OVERLAP_TYPE["RENEW"] = 1] = "RENEW";
    /** 기존 버프의 지속 라운드 또는 남은 횟수를 연장 */
    BUFF_OVERLAP_TYPE[BUFF_OVERLAP_TYPE["ADDTURN"] = 2] = "ADDTURN";
    /** 기존 버프를 덮어씀 (삭제 후 새로 생성) */
    BUFF_OVERLAP_TYPE[BUFF_OVERLAP_TYPE["OVERLAP"] = 3] = "OVERLAP";
    /** 기존 버프와 상관 없이 새로 추가 */
    BUFF_OVERLAP_TYPE[BUFF_OVERLAP_TYPE["STACK"] = 4] = "STACK";
    // __MAX__ = 4,
})(BUFF_OVERLAP_TYPE = exports.BUFF_OVERLAP_TYPE || (exports.BUFF_OVERLAP_TYPE = {}));
/** 장비 유형 */
var ITEM_TYPE;
(function (ITEM_TYPE) {
    /** 칩 */
    ITEM_TYPE[ITEM_TYPE["CHIP"] = 0] = "CHIP";
    /** OS */
    ITEM_TYPE[ITEM_TYPE["SPCHIP"] = 1] = "SPCHIP";
    /** 보조 장비 */
    ITEM_TYPE[ITEM_TYPE["SUBEQ"] = 2] = "SUBEQ";
    /** 전용 장비..? 혹은 코어 링크 */
    ITEM_TYPE[ITEM_TYPE["PCITEM"] = 3] = "PCITEM";
    /** 소모품 */
    ITEM_TYPE[ITEM_TYPE["CONSUMABLE"] = 4] = "CONSUMABLE";
    /** 재료 */
    ITEM_TYPE[ITEM_TYPE["MATERIAL"] = 5] = "MATERIAL";
    // __MAX__,
})(ITEM_TYPE = exports.ITEM_TYPE || (exports.ITEM_TYPE = {}));
/** 제대로 사용하지 않음, 아마도 헬키스트 던전의 잔재 */
var ITEM_SUB_TYPE;
(function (ITEM_SUB_TYPE) {
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["PC_MAKING_ROBOT"] = 0] = "PC_MAKING_ROBOT";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["EQUIP_MAKING"] = 1] = "EQUIP_MAKING";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["FAST_MAKING"] = 2] = "FAST_MAKING";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["UNLOCK_CORE"] = 3] = "UNLOCK_CORE";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["PC_MAKING_BIO"] = 4] = "PC_MAKING_BIO";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["PC_ENCHANT_INIT"] = 5] = "PC_ENCHANT_INIT";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["PC_RESTORE_FAST"] = 6] = "PC_RESTORE_FAST";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["PC_RESTORE_OPENSLOT"] = 7] = "PC_RESTORE_OPENSLOT";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["NORMAL_MODULE"] = 8] = "NORMAL_MODULE";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["ADVANCED_MODULE"] = 9] = "ADVANCED_MODULE";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["SPECIAL_MODULE"] = 10] = "SPECIAL_MODULE";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["INS_RESEARCH"] = 11] = "INS_RESEARCH";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["CHAR_SKIN"] = 12] = "CHAR_SKIN";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["FAVOR_ITEM"] = 13] = "FAVOR_ITEM";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["TACTIC_RECORD"] = 14] = "TACTIC_RECORD";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["TRAINING_MANUAL"] = 15] = "TRAINING_MANUAL";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["CHANGE_NICKNAME"] = 16] = "CHANGE_NICKNAME";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["ETC"] = 17] = "ETC";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["SMALL_PARTS"] = 18] = "SMALL_PARTS";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["MEDIUM_PARTS"] = 19] = "MEDIUM_PARTS";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["LARGE_PARTS"] = 20] = "LARGE_PARTS";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["WOOD_MATERIAL"] = 21] = "WOOD_MATERIAL";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["STONE_MATERIAL"] = 22] = "STONE_MATERIAL";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["IRON_MATERIAL"] = 23] = "IRON_MATERIAL";
    ITEM_SUB_TYPE[ITEM_SUB_TYPE["COLLECTION"] = 24] = "COLLECTION";
    // __MAX__,
})(ITEM_SUB_TYPE = exports.ITEM_SUB_TYPE || (exports.ITEM_SUB_TYPE = {}));
/** 제대로 사용하지 않음, 아마도 헬키스트 던전의 잔재 */
var ITEM_EQUIP_TYPE;
(function (ITEM_EQUIP_TYPE) {
    ITEM_EQUIP_TYPE[ITEM_EQUIP_TYPE["ALL"] = 0] = "ALL";
    ITEM_EQUIP_TYPE[ITEM_EQUIP_TYPE["NOTRANGE"] = 1] = "NOTRANGE";
    ITEM_EQUIP_TYPE[ITEM_EQUIP_TYPE["NOTMELEE"] = 2] = "NOTMELEE";
    ITEM_EQUIP_TYPE[ITEM_EQUIP_TYPE["SUMMON"] = 3] = "SUMMON";
    // __MAX__,
})(ITEM_EQUIP_TYPE = exports.ITEM_EQUIP_TYPE || (exports.ITEM_EQUIP_TYPE = {}));
/** 전투원 몸체 타입 */
var ACTOR_BODY_TYPE;
(function (ACTOR_BODY_TYPE) {
    /** 바이오로이드 */
    ACTOR_BODY_TYPE[ACTOR_BODY_TYPE["ANDROID"] = 0] = "ANDROID";
    ACTOR_BODY_TYPE[ACTOR_BODY_TYPE["BIOROID"] = 0] = "BIOROID";
    /** AGS */
    ACTOR_BODY_TYPE[ACTOR_BODY_TYPE["ROBOT"] = 1] = "ROBOT";
    ACTOR_BODY_TYPE[ACTOR_BODY_TYPE["AGS"] = 1] = "AGS";
    /** 소환물 */
    ACTOR_BODY_TYPE[ACTOR_BODY_TYPE["SUMMON"] = 2] = "SUMMON";
    /** 사용처 없음, 아마도 헬키스트 던전의 잔재 */
    ACTOR_BODY_TYPE[ACTOR_BODY_TYPE["TOTEM"] = 3] = "TOTEM";
    // __MAX__ = 4,
})(ACTOR_BODY_TYPE = exports.ACTOR_BODY_TYPE || (exports.ACTOR_BODY_TYPE = {}));
/** 전투원 유형 */
var ACTOR_CLASS;
(function (ACTOR_CLASS) {
    ACTOR_CLASS[ACTOR_CLASS["TROOPER"] = 0] = "TROOPER";
    ACTOR_CLASS[ACTOR_CLASS["LIGHT"] = 0] = "LIGHT";
    ACTOR_CLASS[ACTOR_CLASS["ARMORED"] = 1] = "ARMORED";
    ACTOR_CLASS[ACTOR_CLASS["HEAVY"] = 1] = "HEAVY";
    ACTOR_CLASS[ACTOR_CLASS["MOBILITY"] = 2] = "MOBILITY";
    ACTOR_CLASS[ACTOR_CLASS["AIR"] = 2] = "AIR";
    // __MAX__ = 3,
})(ACTOR_CLASS = exports.ACTOR_CLASS || (exports.ACTOR_CLASS = {}));
/** 전투원 역할 */
var ROLE_TYPE;
(function (ROLE_TYPE) {
    ROLE_TYPE[ROLE_TYPE["TANKER"] = 0] = "TANKER";
    ROLE_TYPE[ROLE_TYPE["DEFENDER"] = 0] = "DEFENDER";
    ROLE_TYPE[ROLE_TYPE["NUKER"] = 1] = "NUKER";
    ROLE_TYPE[ROLE_TYPE["ATTACKER"] = 1] = "ATTACKER";
    ROLE_TYPE[ROLE_TYPE["SUPPORTER"] = 2] = "SUPPORTER";
    // __MAX__ = 3,
})(ROLE_TYPE = exports.ROLE_TYPE || (exports.ROLE_TYPE = {}));
/** 전투원 등급 */
var ACTOR_GRADE;
(function (ACTOR_GRADE) {
    // D = 0,
    // C = 1,
    ACTOR_GRADE[ACTOR_GRADE["B"] = 2] = "B";
    ACTOR_GRADE[ACTOR_GRADE["A"] = 3] = "A";
    ACTOR_GRADE[ACTOR_GRADE["S"] = 4] = "S";
    ACTOR_GRADE[ACTOR_GRADE["SS"] = 5] = "SS";
    ACTOR_GRADE[ACTOR_GRADE["SSS"] = 6] = "SSS";
})(ACTOR_GRADE = exports.ACTOR_GRADE || (exports.ACTOR_GRADE = {}));
/** 설명 텍스트 값 출력 방식 */
var NUM_OUTPUTTYPE;
(function (NUM_OUTPUTTYPE) {
    /** 값을 그대로 출력 (실수 수치인 경우) */
    NUM_OUTPUTTYPE[NUM_OUTPUTTYPE["INTEGER"] = 0] = "INTEGER";
    /** 값을 100 곱하고 출력 (% 수치인 경우) */
    NUM_OUTPUTTYPE[NUM_OUTPUTTYPE["PERCENT"] = 1] = "PERCENT";
    // __MAX__ = 2,
})(NUM_OUTPUTTYPE = exports.NUM_OUTPUTTYPE || (exports.NUM_OUTPUTTYPE = {}));
/** 적용 대상 유형 */
var TARGET_TYPE;
(function (TARGET_TYPE) {
    /** 본인 */
    TARGET_TYPE[TARGET_TYPE["SELF"] = 0] = "SELF";
    /** 지정한 아군 */
    TARGET_TYPE[TARGET_TYPE["OUR"] = 1] = "OUR";
    /** 범위 내 아군 (땅찍기) */
    TARGET_TYPE[TARGET_TYPE["OUR_GRID"] = 2] = "OUR_GRID";
    /** 지정한 적군 */
    TARGET_TYPE[TARGET_TYPE["ENEMY"] = 3] = "ENEMY";
    /** 범위 내 적군 (땅찍기) */
    TARGET_TYPE[TARGET_TYPE["ENEMY_GRID"] = 4] = "ENEMY_GRID";
    /** 아군/적군 구분 없는 지정 전투원 */
    TARGET_TYPE[TARGET_TYPE["ALL_UNIT"] = 5] = "ALL_UNIT";
    /** 아군/적군 구분 없는 땅 찍기 */
    TARGET_TYPE[TARGET_TYPE["ALL_GRID"] = 6] = "ALL_GRID";
    /** 시스템 효과? */
    TARGET_TYPE[TARGET_TYPE["SYSTEM"] = 7] = "SYSTEM";
    // __MAX__ = 8,
})(TARGET_TYPE = exports.TARGET_TYPE || (exports.TARGET_TYPE = {}));
/** 적용 대상 부차 유형 */
var TARGET_SUB_TYPE;
(function (TARGET_SUB_TYPE) {
    /** 살아있는 대상 */
    TARGET_SUB_TYPE[TARGET_SUB_TYPE["ALIVE"] = 0] = "ALIVE";
    /** 사망한 대상? */
    TARGET_SUB_TYPE[TARGET_SUB_TYPE["DEAD"] = 1] = "DEAD";
    // __MAX__ = 2,
})(TARGET_SUB_TYPE = exports.TARGET_SUB_TYPE || (exports.TARGET_SUB_TYPE = {}));
/** 스킬 레벨 적용 방식 */
var SKILL_LEVEL_TYPE;
(function (SKILL_LEVEL_TYPE) {
    SKILL_LEVEL_TYPE[SKILL_LEVEL_TYPE["NORMAL"] = 0] = "NORMAL";
    SKILL_LEVEL_TYPE[SKILL_LEVEL_TYPE["DEADLY"] = 1] = "DEADLY";
    // __MAX__ = 2,
})(SKILL_LEVEL_TYPE = exports.SKILL_LEVEL_TYPE || (exports.SKILL_LEVEL_TYPE = {}));
/** 스킬의 유형 */
var SKILL_TYPE;
(function (SKILL_TYPE) {
    /** 액티브 스킬 */
    SKILL_TYPE[SKILL_TYPE["ACTIVE"] = 0] = "ACTIVE";
    /** 패시브 스킬 */
    SKILL_TYPE[SKILL_TYPE["PASSIVE"] = 1] = "PASSIVE";
    // __MAX__ = 2,
})(SKILL_TYPE = exports.SKILL_TYPE || (exports.SKILL_TYPE = {}));
/** 스킬의 부차 유형 */
var SKILL_SUB_TYPE;
(function (SKILL_SUB_TYPE) {
    SKILL_SUB_TYPE[SKILL_SUB_TYPE["NORMAL"] = 0] = "NORMAL";
    // __MAX__ = 1,
})(SKILL_SUB_TYPE = exports.SKILL_SUB_TYPE || (exports.SKILL_SUB_TYPE = {}));
/** 스킬의 슬롯 위치 */
var SKILL_SLOT_TYPE;
(function (SKILL_SLOT_TYPE) {
    /** 슬롯에 존재하지 않음 */
    SKILL_SLOT_TYPE[SKILL_SLOT_TYPE["NONE"] = 0] = "NONE";
    SKILL_SLOT_TYPE[SKILL_SLOT_TYPE["SLOT_1"] = 1] = "SLOT_1";
    SKILL_SLOT_TYPE[SKILL_SLOT_TYPE["SLOT_2"] = 2] = "SLOT_2";
    SKILL_SLOT_TYPE[SKILL_SLOT_TYPE["SLOT_3"] = 3] = "SLOT_3";
    SKILL_SLOT_TYPE[SKILL_SLOT_TYPE["SLOT_4"] = 4] = "SLOT_4";
    SKILL_SLOT_TYPE[SKILL_SLOT_TYPE["SLOT_5"] = 5] = "SLOT_5";
    // __MAX__ = 6,
})(SKILL_SLOT_TYPE = exports.SKILL_SLOT_TYPE || (exports.SKILL_SLOT_TYPE = {}));
/** 스킬의 속성 */
var SKILL_ATTR;
(function (SKILL_ATTR) {
    /** 물리 피해 */
    SKILL_ATTR[SKILL_ATTR["NONE"] = 0] = "NONE";
    SKILL_ATTR[SKILL_ATTR["PHYSICS"] = 0] = "PHYSICS";
    SKILL_ATTR[SKILL_ATTR["FIRE"] = 1] = "FIRE";
    SKILL_ATTR[SKILL_ATTR["CHILL"] = 2] = "CHILL";
    SKILL_ATTR[SKILL_ATTR["ICE"] = 2] = "ICE";
    SKILL_ATTR[SKILL_ATTR["LIGHTNING"] = 3] = "LIGHTNING";
    SKILL_ATTR[SKILL_ATTR["THUNDER"] = 3] = "THUNDER";
})(SKILL_ATTR = exports.SKILL_ATTR || (exports.SKILL_ATTR = {}));
/** 다대상 공격의 작동 방식 */
var MULTI_ATTACK_TYPE;
(function (MULTI_ATTACK_TYPE) {
    /** 특별한 작동 없음 */
    MULTI_ATTACK_TYPE[MULTI_ATTACK_TYPE["MULTIPLE"] = 0] = "MULTIPLE";
    /** 폭발 (?) */
    MULTI_ATTACK_TYPE[MULTI_ATTACK_TYPE["EXPLOSION"] = 1] = "EXPLOSION";
    /** 관통 */
    MULTI_ATTACK_TYPE[MULTI_ATTACK_TYPE["PIERCING"] = 2] = "PIERCING";
    // __MAX__ = 3,
})(MULTI_ATTACK_TYPE = exports.MULTI_ATTACK_TYPE || (exports.MULTI_ATTACK_TYPE = {}));
/** 버프 표시 유형 */
var BUFF_ANNOUNCE_TYPE;
(function (BUFF_ANNOUNCE_TYPE) {
    /** 표시하지 않음 */
    BUFF_ANNOUNCE_TYPE[BUFF_ANNOUNCE_TYPE["NONE"] = 0] = "NONE";
    /** 추가되면 바로 표시 */
    BUFF_ANNOUNCE_TYPE[BUFF_ANNOUNCE_TYPE["REALTIME"] = 1] = "REALTIME";
    /** 바로 표시하지는 않음 */
    BUFF_ANNOUNCE_TYPE[BUFF_ANNOUNCE_TYPE["NOT_REALTIME"] = 2] = "NOT_REALTIME";
    /** 추가되면 바로 표시... Emily의 리미터 해제만 존재 */
    BUFF_ANNOUNCE_TYPE[BUFF_ANNOUNCE_TYPE["INSTANT"] = 3] = "INSTANT";
    // __MAX__ = 4,
})(BUFF_ANNOUNCE_TYPE = exports.BUFF_ANNOUNCE_TYPE || (exports.BUFF_ANNOUNCE_TYPE = {}));
/** 설비 종류 */
var FACILITY_TYPE_CATEGORY;
(function (FACILITY_TYPE_CATEGORY) {
    /** 전투 결과 분석실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["TRAINIG_SUPPORT"] = 0] = "TRAINIG_SUPPORT";
    /** 합성수지 생산소 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["WOOD_MAKING"] = 1] = "WOOD_MAKING";
    /** 도료 생산소 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["STONE_MAKING"] = 2] = "STONE_MAKING";
    /** 철재 생산소 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["IRON_MAKING"] = 3] = "IRON_MAKING";
    /** 보호기 바이오로이드 제작실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["TANKER_MAKING"] = 4] = "TANKER_MAKING";
    /** 공격기 바이오로이드 제작실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["NUKER_MAKING"] = 5] = "NUKER_MAKING";
    /** 지원기 바이오로이드 제작실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["SUPPORTER_MAKING"] = 6] = "SUPPORTER_MAKING";
    /** 영양 생산 지원실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["NUTRIENT_MAKING"] = 7] = "NUTRIENT_MAKING";
    /** 부품 생산 지원실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["METAL_MAKING"] = 8] = "METAL_MAKING";
    /** 전력 생산 지원실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["POWER_MAKING"] = 9] = "POWER_MAKING";
    /** 장비 강화 효율 연구실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["EQUIP_REIN"] = 10] = "EQUIP_REIN";
    /** 장비 분해 효율 연구실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["EQUIP_DISASSEMBLE"] = 11] = "EQUIP_DISASSEMBLE";
    /** 설비 부품 제작실 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["FACILITY_PARTS_MAKING"] = 12] = "FACILITY_PARTS_MAKING";
    /** 제작 핵심 부품 생산소 */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["MATERIAL_MAKING"] = 13] = "MATERIAL_MAKING";
    /** 카페테리아  */
    FACILITY_TYPE_CATEGORY[FACILITY_TYPE_CATEGORY["CAFETERIA"] = 14] = "CAFETERIA";
    // __MAX__ = 15,
})(FACILITY_TYPE_CATEGORY = exports.FACILITY_TYPE_CATEGORY || (exports.FACILITY_TYPE_CATEGORY = {}));
/** 설비 패시브 기능 종류 */
var PASSIVE_BUFF_TYPE;
(function (PASSIVE_BUFF_TYPE) {
    /** 패시브 없음 */
    PASSIVE_BUFF_TYPE[PASSIVE_BUFF_TYPE["NONE"] = 0] = "NONE";
    /** 전투 경험치 증가 */
    PASSIVE_BUFF_TYPE[PASSIVE_BUFF_TYPE["STAGE_EXP_UP"] = 1] = "STAGE_EXP_UP";
    /** 장비 강화 비용 감소 */
    PASSIVE_BUFF_TYPE[PASSIVE_BUFF_TYPE["ENCHANTCOST_DOWN"] = 2] = "ENCHANTCOST_DOWN";
    /** 장비 분해 비용 증가 */
    PASSIVE_BUFF_TYPE[PASSIVE_BUFF_TYPE["DISASSEMBLE_UP"] = 3] = "DISASSEMBLE_UP";
    /** 영양 생산 증가 */
    PASSIVE_BUFF_TYPE[PASSIVE_BUFF_TYPE["NUTRIENT_CHANGE_UP"] = 4] = "NUTRIENT_CHANGE_UP";
    /** 부품 생산 증가 */
    PASSIVE_BUFF_TYPE[PASSIVE_BUFF_TYPE["METAL_CHANGE_UP"] = 5] = "METAL_CHANGE_UP";
    /** 전력 생산 증가 */
    PASSIVE_BUFF_TYPE[PASSIVE_BUFF_TYPE["POWER_CHANGE_UP"] = 6] = "POWER_CHANGE_UP";
    /** 설비 부품 생산 시간 감소 */
    PASSIVE_BUFF_TYPE[PASSIVE_BUFF_TYPE["FACILITY_MAKING_TIME_DOWN"] = 7] = "FACILITY_MAKING_TIME_DOWN";
    // __MAX__ = 8,
})(PASSIVE_BUFF_TYPE = exports.PASSIVE_BUFF_TYPE || (exports.PASSIVE_BUFF_TYPE = {}));
/** 설비 생산품 종류 */
var PRODUCE_TYPE;
(function (PRODUCE_TYPE) {
    /** 생산품 없음 */
    PRODUCE_TYPE[PRODUCE_TYPE["NONE"] = 0] = "NONE";
    /** 소모품 생산 */
    PRODUCE_TYPE[PRODUCE_TYPE["ITEM_CONSUMABLE"] = 1] = "ITEM_CONSUMABLE";
    /** 전투원 생산 */
    PRODUCE_TYPE[PRODUCE_TYPE["FACILITY_TYPE_BIOROID"] = 2] = "FACILITY_TYPE_BIOROID";
    // __MAX__ = 3,
})(PRODUCE_TYPE = exports.PRODUCE_TYPE || (exports.PRODUCE_TYPE = {}));
/** 필요한 전투원 구분 */
var REQUIRED_COMBATANT_TYPE;
(function (REQUIRED_COMBATANT_TYPE) {
    /** 구분 없음 */
    REQUIRED_COMBATANT_TYPE[REQUIRED_COMBATANT_TYPE["NONE"] = 0] = "NONE";
    /** 전투원 유형 (경장/기동/중장) */
    REQUIRED_COMBATANT_TYPE[REQUIRED_COMBATANT_TYPE["ACTOR_TYPE"] = 1] = "ACTOR_TYPE";
    /** 전투원 역할 (공격/보호/지원) */
    REQUIRED_COMBATANT_TYPE[REQUIRED_COMBATANT_TYPE["ROLE_TYPE"] = 2] = "ROLE_TYPE";
    /** 전투원 몸체 (바이오로이드/AGS) */
    REQUIRED_COMBATANT_TYPE[REQUIRED_COMBATANT_TYPE["ACTOR_BODY_TYPE"] = 3] = "ACTOR_BODY_TYPE";
    /** 전투원 등급 */
    REQUIRED_COMBATANT_TYPE[REQUIRED_COMBATANT_TYPE["GRADE_TYPE"] = 4] = "GRADE_TYPE";
    /** 특정 전투원 */
    REQUIRED_COMBATANT_TYPE[REQUIRED_COMBATANT_TYPE["SPECIFIC_COMBAT"] = 5] = "SPECIFIC_COMBAT";
    // __MAX__ = 6,
})(REQUIRED_COMBATANT_TYPE = exports.REQUIRED_COMBATANT_TYPE || (exports.REQUIRED_COMBATANT_TYPE = {}));
var ITEM_USE_TYPE;
(function (ITEM_USE_TYPE) {
    ITEM_USE_TYPE[ITEM_USE_TYPE["CREATE"] = 0] = "CREATE";
    ITEM_USE_TYPE[ITEM_USE_TYPE["USE"] = 1] = "USE";
    // __MAX__ = 2,
})(ITEM_USE_TYPE = exports.ITEM_USE_TYPE || (exports.ITEM_USE_TYPE = {}));
var MONSTER_TYPE;
(function (MONSTER_TYPE) {
    MONSTER_TYPE[MONSTER_TYPE["NORMAL"] = 0] = "NORMAL";
    MONSTER_TYPE[MONSTER_TYPE["BOSS"] = 1] = "BOSS";
    // __MAX__ = 2,
})(MONSTER_TYPE = exports.MONSTER_TYPE || (exports.MONSTER_TYPE = {}));
var MONSTER_SUB_TYPE;
(function (MONSTER_SUB_TYPE) {
    MONSTER_SUB_TYPE[MONSTER_SUB_TYPE["NORMAL"] = 0] = "NORMAL";
    MONSTER_SUB_TYPE[MONSTER_SUB_TYPE["BOSS"] = 1] = "BOSS";
    MONSTER_SUB_TYPE[MONSTER_SUB_TYPE["NIGHTCHICK"] = 2] = "NIGHTCHICK";
    MONSTER_SUB_TYPE[MONSTER_SUB_TYPE["SHIELD"] = 3] = "SHIELD";
    MONSTER_SUB_TYPE[MONSTER_SUB_TYPE["BEETLE"] = 4] = "BEETLE";
    // __MAX__ = 5,
})(MONSTER_SUB_TYPE = exports.MONSTER_SUB_TYPE || (exports.MONSTER_SUB_TYPE = {}));
var SUMMON_TYPE;
(function (SUMMON_TYPE) {
    SUMMON_TYPE[SUMMON_TYPE["INSTALLATION"] = 0] = "INSTALLATION";
    SUMMON_TYPE[SUMMON_TYPE["ENVIRONMENTAL"] = 1] = "ENVIRONMENTAL";
    SUMMON_TYPE[SUMMON_TYPE["AUTOPILOT"] = 2] = "AUTOPILOT";
    // __MAX__ = 3,
})(SUMMON_TYPE = exports.SUMMON_TYPE || (exports.SUMMON_TYPE = {}));
var INSTALL_POS_TYPE;
(function (INSTALL_POS_TYPE) {
    INSTALL_POS_TYPE[INSTALL_POS_TYPE["PC"] = 0] = "PC";
    INSTALL_POS_TYPE[INSTALL_POS_TYPE["MONSTER"] = 1] = "MONSTER";
    // __MAX__ = 2,
})(INSTALL_POS_TYPE = exports.INSTALL_POS_TYPE || (exports.INSTALL_POS_TYPE = {}));
var CURRENCY_TYPE;
(function (CURRENCY_TYPE) {
    CURRENCY_TYPE[CURRENCY_TYPE["METAL"] = 0] = "METAL";
    CURRENCY_TYPE[CURRENCY_TYPE["NUTRIENT"] = 1] = "NUTRIENT";
    CURRENCY_TYPE[CURRENCY_TYPE["POWER"] = 2] = "POWER";
    CURRENCY_TYPE[CURRENCY_TYPE["TRAINING_TICKET"] = 3] = "TRAINING_TICKET";
    CURRENCY_TYPE[CURRENCY_TYPE["CASH"] = 4] = "CASH";
    CURRENCY_TYPE[CURRENCY_TYPE["BUYCASH"] = 5] = "BUYCASH";
    CURRENCY_TYPE[CURRENCY_TYPE["CHALLENGESTAGE_TICKET"] = 6] = "CHALLENGESTAGE_TICKET";
    // __MAX__ = 7,
})(CURRENCY_TYPE = exports.CURRENCY_TYPE || (exports.CURRENCY_TYPE = {}));
var ROGUE_LIMIT_EFFECT_CATEGORY;
(function (ROGUE_LIMIT_EFFECT_CATEGORY) {
    ROGUE_LIMIT_EFFECT_CATEGORY[ROGUE_LIMIT_EFFECT_CATEGORY["NONE"] = 0] = "NONE";
    ROGUE_LIMIT_EFFECT_CATEGORY[ROGUE_LIMIT_EFFECT_CATEGORY["DIFFICULT_INCREASE"] = 1] = "DIFFICULT_INCREASE";
    ROGUE_LIMIT_EFFECT_CATEGORY[ROGUE_LIMIT_EFFECT_CATEGORY["DEBUFF"] = 2] = "DEBUFF";
    ROGUE_LIMIT_EFFECT_CATEGORY[ROGUE_LIMIT_EFFECT_CATEGORY["BUFF"] = 3] = "BUFF";
    ROGUE_LIMIT_EFFECT_CATEGORY[ROGUE_LIMIT_EFFECT_CATEGORY["ENEMY_BUFF"] = 4] = "ENEMY_BUFF";
})(ROGUE_LIMIT_EFFECT_CATEGORY = exports.ROGUE_LIMIT_EFFECT_CATEGORY || (exports.ROGUE_LIMIT_EFFECT_CATEGORY = {}));
var ROGUE_LIMIT_EFFECT_CONDITION;
(function (ROGUE_LIMIT_EFFECT_CONDITION) {
    ROGUE_LIMIT_EFFECT_CONDITION[ROGUE_LIMIT_EFFECT_CONDITION["NONE"] = 0] = "NONE";
    ROGUE_LIMIT_EFFECT_CONDITION[ROGUE_LIMIT_EFFECT_CONDITION["CELL_MOVE_LIMIT"] = 1] = "CELL_MOVE_LIMIT";
    ROGUE_LIMIT_EFFECT_CONDITION[ROGUE_LIMIT_EFFECT_CONDITION["STAGE_CLEAR_LIMIT"] = 2] = "STAGE_CLEAR_LIMIT";
    ROGUE_LIMIT_EFFECT_CONDITION[ROGUE_LIMIT_EFFECT_CONDITION["FLOOR_CLEAR_LIMIT"] = 3] = "FLOOR_CLEAR_LIMIT";
})(ROGUE_LIMIT_EFFECT_CONDITION = exports.ROGUE_LIMIT_EFFECT_CONDITION || (exports.ROGUE_LIMIT_EFFECT_CONDITION = {}));
var ROGUE_LIMIT_EFFECT_OVERLAP;
(function (ROGUE_LIMIT_EFFECT_OVERLAP) {
    ROGUE_LIMIT_EFFECT_OVERLAP[ROGUE_LIMIT_EFFECT_OVERLAP["NONE"] = 0] = "NONE";
    ROGUE_LIMIT_EFFECT_OVERLAP[ROGUE_LIMIT_EFFECT_OVERLAP["CONDITION_VALUE_INC"] = 1] = "CONDITION_VALUE_INC";
})(ROGUE_LIMIT_EFFECT_OVERLAP = exports.ROGUE_LIMIT_EFFECT_OVERLAP || (exports.ROGUE_LIMIT_EFFECT_OVERLAP = {}));
var ROGUE_LIMIT_EFFECT_SHOW_TYPE;
(function (ROGUE_LIMIT_EFFECT_SHOW_TYPE) {
    ROGUE_LIMIT_EFFECT_SHOW_TYPE[ROGUE_LIMIT_EFFECT_SHOW_TYPE["NONE"] = 0] = "NONE";
    ROGUE_LIMIT_EFFECT_SHOW_TYPE[ROGUE_LIMIT_EFFECT_SHOW_TYPE["SHOW_EFFECT_APPLY"] = 1] = "SHOW_EFFECT_APPLY";
})(ROGUE_LIMIT_EFFECT_SHOW_TYPE = exports.ROGUE_LIMIT_EFFECT_SHOW_TYPE || (exports.ROGUE_LIMIT_EFFECT_SHOW_TYPE = {}));
var ROGUE_LIMIT_EFFECT_TYPE;
(function (ROGUE_LIMIT_EFFECT_TYPE) {
    ROGUE_LIMIT_EFFECT_TYPE[ROGUE_LIMIT_EFFECT_TYPE["NONE"] = 0] = "NONE";
    ROGUE_LIMIT_EFFECT_TYPE[ROGUE_LIMIT_EFFECT_TYPE["DIFFICULT_INCREASE"] = 1] = "DIFFICULT_INCREASE";
    ROGUE_LIMIT_EFFECT_TYPE[ROGUE_LIMIT_EFFECT_TYPE["CELL_MOVE_HP_DOWN"] = 2] = "CELL_MOVE_HP_DOWN";
    ROGUE_LIMIT_EFFECT_TYPE[ROGUE_LIMIT_EFFECT_TYPE["BUFF_SPC_KEY_GIVE"] = 3] = "BUFF_SPC_KEY_GIVE";
    ROGUE_LIMIT_EFFECT_TYPE[ROGUE_LIMIT_EFFECT_TYPE["TRAP_OBJECT_IGNORE"] = 4] = "TRAP_OBJECT_IGNORE";
    ROGUE_LIMIT_EFFECT_TYPE[ROGUE_LIMIT_EFFECT_TYPE["DEBUFF_TRAP_OBJECT_IGNORE"] = 5] = "DEBUFF_TRAP_OBJECT_IGNORE";
    ROGUE_LIMIT_EFFECT_TYPE[ROGUE_LIMIT_EFFECT_TYPE["STEALTH_MONSTER_OBJECT_IGNORE"] = 6] = "STEALTH_MONSTER_OBJECT_IGNORE";
    ROGUE_LIMIT_EFFECT_TYPE[ROGUE_LIMIT_EFFECT_TYPE["ROGUE_POINT_RATE_INC"] = 7] = "ROGUE_POINT_RATE_INC";
})(ROGUE_LIMIT_EFFECT_TYPE = exports.ROGUE_LIMIT_EFFECT_TYPE || (exports.ROGUE_LIMIT_EFFECT_TYPE = {}));
var ROGUE_QUEST_OBJECT_TYPE;
(function (ROGUE_QUEST_OBJECT_TYPE) {
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["NONE"] = 0] = "NONE";
    /** 특정 타입의 노드 삭제 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_OBJECT_SPC_TYPE_REMOVE"] = 1] = "ROGUE_OBJECT_SPC_TYPE_REMOVE";
    /** 특정 타입의 아이템 획득 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_ITEM_SPC_TYPE_GAIN"] = 2] = "ROGUE_ITEM_SPC_TYPE_GAIN";
    /** 층 돌파 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_FLOOR_CLEAR"] = 3] = "ROGUE_FLOOR_CLEAR";
    /** 특정 패시브 이펙트 획득 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_EFFECT_SPC_TYPE_GAIN"] = 4] = "ROGUE_EFFECT_SPC_TYPE_GAIN";
    /** 특정 등급 패시브 이펙트 획득 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_EFFECT_SPC_GRADE_GAIN"] = 5] = "ROGUE_EFFECT_SPC_GRADE_GAIN";
    /** 전투 완료 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_STAGE_CLEAR"] = 6] = "ROGUE_STAGE_CLEAR";
    /** 적 처리 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_KILL_MONSTER"] = 7] = "ROGUE_KILL_MONSTER";
    /** 특정 적 처리 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_KILL_MONSTER_SPC"] = 8] = "ROGUE_KILL_MONSTER_SPC";
    /** 특정 유형 적 처리 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_KILL_MONSTER_TYPE"] = 9] = "ROGUE_KILL_MONSTER_TYPE";
    /** 특정 역할 적 처리 */
    ROGUE_QUEST_OBJECT_TYPE[ROGUE_QUEST_OBJECT_TYPE["ROGUE_KILL_MONSTER_ROLE"] = 10] = "ROGUE_KILL_MONSTER_ROLE";
})(ROGUE_QUEST_OBJECT_TYPE = exports.ROGUE_QUEST_OBJECT_TYPE || (exports.ROGUE_QUEST_OBJECT_TYPE = {}));
var ROGUE_CELL_TYPE;
(function (ROGUE_CELL_TYPE) {
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["NONE"] = 0] = "NONE";
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["BLANK"] = 1] = "BLANK";
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["STARTPOINT"] = 2] = "STARTPOINT";
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["BOSSMOB"] = 3] = "BOSSMOB";
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["MOB"] = 4] = "MOB";
    /** 아군 신호 탐색 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["ACTOR"] = 5] = "ACTOR";
    /** 오염된 군수 공장 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["EFFECT"] = 6] = "EFFECT";
    /** 긴급 수복 스테이션 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["RECOVERY"] = 7] = "RECOVERY";
    /** 예상치 못한 사고 (물리, 지뢰지대) */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["TRAP"] = 8] = "TRAP";
    /** 관측소 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["OBSERVE"] = 9] = "OBSERVE";
    /** 삼안 물자취급소 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["SHOP"] = 10] = "SHOP";
    /** 지휘 결심 체계 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["QUEST"] = 11] = "QUEST";
    /** 특수 밀봉 컨테이너 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["TREASURE"] = 12] = "TREASURE";
    /** 공기 정화 시설 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["THOUSE"] = 13] = "THOUSE";
    /** PECS 방문 카드 습득 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["KEY"] = 14] = "KEY";
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["TRACKER"] = 15] = "TRACKER";
    /** 고준위 방사능 오염 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["POISON"] = 16] = "POISON";
    /** 혼돈 엔트로피 */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["DEBUFF"] = 17] = "DEBUFF";
    /** 예상치 못한 사고 (화염, 소이탄 저장고) */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["FIRE_TRAP"] = 18] = "FIRE_TRAP";
    /** 예상치 못한 사고 (냉기, 냉매 보관소) */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["ICE_TRAP"] = 19] = "ICE_TRAP";
    /** 예상치 못한 사고 (전기, 고전류 발전 시설) */
    ROGUE_CELL_TYPE[ROGUE_CELL_TYPE["LIGHTNING_TRAP"] = 20] = "LIGHTNING_TRAP";
})(ROGUE_CELL_TYPE = exports.ROGUE_CELL_TYPE || (exports.ROGUE_CELL_TYPE = {}));
var ROGUEEFFECTTYPE;
(function (ROGUEEFFECTTYPE) {
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["NONE"] = 0] = "NONE";
    /** 강습의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["AMP"] = 1] = "AMP";
    /** 장사정의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["OBSERVE"] = 2] = "OBSERVE";
    /** 철갑의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["ARMOR"] = 3] = "ARMOR";
    /** 방공의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["BARRIER"] = 4] = "BARRIER";
    /** 요새의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["GIFT"] = 5] = "GIFT";
    /** 기갑의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["RAPID"] = 6] = "RAPID";
    /** 기만의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["PREDICT"] = 7] = "PREDICT";
    /** 유도의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["DETAIL"] = 8] = "DETAIL";
    /** 섬멸의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["RESPONSE"] = 9] = "RESPONSE";
    /** 대구경의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["PENETRATE"] = 10] = "PENETRATE";
    /** 전천후의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["COATING"] = 11] = "COATING";
    /** 제독의 */
    ROGUEEFFECTTYPE[ROGUEEFFECTTYPE["VACCINE"] = 12] = "VACCINE";
})(ROGUEEFFECTTYPE = exports.ROGUEEFFECTTYPE || (exports.ROGUEEFFECTTYPE = {}));
var ROGUE_SKILL_TYPE;
(function (ROGUE_SKILL_TYPE) {
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["NONE"] = 0] = "NONE";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["SCOUT"] = 1] = "SCOUT";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["SUPPORT_ATK"] = 2] = "SUPPORT_ATK";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["TREASURE_HUNTER"] = 3] = "TREASURE_HUNTER";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["TRAP_DIS"] = 4] = "TRAP_DIS";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["DEBUFF_DIS"] = 5] = "DEBUFF_DIS";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["BOMB"] = 6] = "BOMB";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["STEALTH"] = 7] = "STEALTH";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["SCOUTER"] = 8] = "SCOUTER";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["CREATOR"] = 9] = "CREATOR";
    ROGUE_SKILL_TYPE[ROGUE_SKILL_TYPE["ROGUE_POINT_RATE_INC"] = 10] = "ROGUE_POINT_RATE_INC";
})(ROGUE_SKILL_TYPE = exports.ROGUE_SKILL_TYPE || (exports.ROGUE_SKILL_TYPE = {}));
