import { BGMAlbum } from "@/types/BGM";

const BGMAlbums: BGMAlbum[] = [
	{
		id: "album01",
		title: "LastOrigin Original Sound Track",
		author: "LastOrigin",
		image: "album01",
		songs: [
			{
				type: "audio",
				id: "track_title",
				title: "Title",
				duration: 61,
				filename: "Album01/Title.mp3",
				lyrics: [{ time: 0, text: "Title" }],
			},

			{
				type: "audio",
				id: "track_lobby",
				title: "Lobby",
				duration: 61,
				filename: "Album01/Lobby.mp3",
				lyrics: [{ time: 0, text: "Lobby" }],
			},
			{
				type: "audio",
				id: "track_valentine",
				title: "Valentine Day (Lobby)",
				duration: 62,
				filename: "Album01/Valentine.mp3",
				lyrics: [{ time: 0, text: "Valentine" }],
			},

			{
				type: "audio",
				id: "track_talk_01",
				title: "Talk A",
				duration: 61,
				filename: "Album01/Talk_01.mp3",
				lyrics: [{ time: 0, text: "Talk 01" }],
			},
			{
				type: "audio",
				id: "track_talk_02",
				title: "Talk B",
				duration: 59,
				filename: "Album01/Talk_02.mp3",
				lyrics: [{ time: 0, text: "Talk 02" }],
			},
			{
				type: "audio",
				id: "track_talk_03",
				title: "Talk C",
				duration: 63,
				filename: "Album01/Talk_03.mp3",
				lyrics: [{ time: 0, text: "Talk 03" }],
			},
			{
				type: "audio",
				id: "track_talk_04",
				title: "Talk D",
				duration: 61,
				filename: "Album01/Talk_04.mp3",
				lyrics: [{ time: 0, text: "Talk 04" }],
			},
			{
				type: "audio",
				id: "track_talk_05",
				title: "Talk E",
				duration: 65,
				filename: "Album01/Talk_05.mp3",
				lyrics: [{ time: 0, text: "Talk 05" }],
			},
			{
				type: "audio",
				id: "track_talk_06",
				title: "Talk F",
				duration: 94,
				filename: "Album01/Talk_06.mp3",
				lyrics: [{ time: 0, text: "Talk 06" }],
			},
			{
				type: "audio",
				id: "track_talk_07",
				title: "Talk G",
				duration: 93,
				filename: "Album01/Talk_07.mp3",
				lyrics: [{ time: 0, text: "Talk 07" }],
			},
			{
				type: "audio",
				id: "track_talk_08",
				title: "Talk H - Thrill",
				duration: 75,
				filename: "Album01/Thrill_01.mp3",
				lyrics: [{ time: 0, text: "Thrill 01" }],
			},

			{
				type: "audio",
				id: "track_marriage_01",
				title: "Marriage - Elevator",
				duration: 11,
				filename: "Album01/Marriage_01.mp3",
				lyrics: [{ time: 0, text: "Marriage 01" }],
			},
			{
				type: "audio",
				id: "track_marriage_02",
				title: "Marriage - Deck",
				duration: 33,
				filename: "Album01/Marriage_02.mp3",
				lyrics: [{ time: 0, text: "Marriage 02" }],
			},

			{
				type: "audio",
				id: "track_battle_01",
				title: "Battle A",
				duration: 67,
				filename: "Album01/Battle_01.mp3",
				lyrics: [{ time: 0, text: "Battle 01" }],
			},
			{
				type: "audio",
				id: "track_battle_01_old",
				title: "Battle A (Old)",
				duration: 67,
				filename: "Album01/Battle_01b.mp3",
				lyrics: [{ time: 0, text: "Battle 01 (Old)" }],
			},
			{
				type: "audio",
				id: "track_battle_02",
				title: "Battle B",
				duration: 60,
				filename: "Album01/Battle_02.mp3",
				lyrics: [{ time: 0, text: "Battle 02" }],
			},
			{
				type: "audio",
				id: "track_battle_04",
				title: "Battle C",
				duration: 91,
				filename: "Album01/Battle_04.mp3",
				lyrics: [{ time: 0, text: "Battle 04" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_01",
				title: "Boss Battle A",
				duration: 62,
				filename: "Album01/Battle_Boss_01.mp3",
				lyrics: [{ time: 0, text: "Battle Boss 01" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_02",
				title: "Boss Battle B",
				duration: 58,
				filename: "Album01/Battle_Boss_02.mp3",
				lyrics: [{ time: 0, text: "Battle Boss 02" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_03",
				title: "Boss Battle C",
				duration: 67,
				filename: "Album01/Battle_Boss_03.mp3",
				lyrics: [{ time: 0, text: "Battle Boss 03" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_04",
				title: "Boss Battle D - Iron Prince",
				duration: 100,
				filename: "Album01/IronPrince.mp3",
				lyrics: [{ time: 0, text: "Iron Prince" }],
			},

			{
				type: "audio",
				id: "track_irontower",
				title: "Iron Tower",
				duration: 101,
				filename: "Album01/Sanctum.mp3",
				lyrics: [{ time: 0, text: "Sanctum" }],
			},
			{
				type: "audio",
				id: "track_irontower_battle",
				title: "Iron Tower Battle",
				duration: 67,
				filename: "Album01/Battle_05.mp3",
				lyrics: [{ time: 0, text: "Battle 05" }],
			},
			{
				type: "audio",
				id: "track_irontower_battle_boss",
				title: "Iron Tower Boss Battle",
				duration: 67,
				filename: "Album01/Battle_Boss_03b.mp3",
				lyrics: [{ time: 0, text: "Battle Boss 03b" }],
			},

			{
				type: "audio",
				id: "track_battle_10stage",
				title: "Battle Stage 10",
				duration: 121,
				filename: "Album01/Battle_10Stage.mp3",
				lyrics: [{ time: 0, text: "Battle Stage 10" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_10stage",
				title: "Boss Battle Stage 10",
				duration: 146,
				filename: "Album01/Battle_Boss_10Stage.mp3",
				lyrics: [{ time: 0, text: "Battle Boss Stage 10" }],
			},
			{
				type: "audio",
				id: "track_funeral_for_mom",
				title: "Funeral for Mom",
				duration: 123,
				filename: "Album01/Funeral_For_Mom.mp3",
				lyrics: [{ time: 0, text: "Funeral for Mom" }],
			},
		],
	},
	{
		id: "album02",
		title: "@WORLD_Ev3", // 만월의 야상곡
		author: "LastOrigin",
		image: "album02",
		songs: [
			{
				type: "audio",
				id: "track_battle_03",
				title: "Battle",
				duration: 60,
				filename: "Album02/Battle_03.mp3",
				lyrics: [{ time: 0, text: "Battle 03" }],
			},
		],
	},
	{
		id: "album03",
		title: "@WORLD_Ev5", // 세인트 오르카의 비밀작전
		author: "LastOrigin",
		image: "album03",
		songs: [
			{
				type: "audio",
				id: "track_christmas_01",
				title: "Christmas A",
				duration: 64,
				filename: "Album03/Christmas_01.mp3",
				lyrics: [{ time: 0, text: "Christmas 01" }],
			},
			{
				type: "audio",
				id: "track_christmas_02",
				title: "Christmas B (Lobby)",
				duration: 62,
				filename: "Album03/Christmas_02.mp3",
				lyrics: [{ time: 0, text: "Christmas 02" }],
			},
		],
	},
	{
		id: "album04",
		title: "@WORLD_Ev7", // 요정 마을의 아리아
		author: "LastOrigin",
		image: "album04",
		songs: [
			{
				type: "audio",
				id: "track_summer_01",
				title: "Summer A",
				duration: 79,
				filename: "Album04/Summer_01.mp3",
				lyrics: [{ time: 0, text: "Summer 01" }],
			},
			{
				type: "audio",
				id: "track_summer_02",
				title: "Summer B",
				duration: 79,
				filename: "Album04/Summer_02.mp3",
				lyrics: [{ time: 0, text: "Summer 02" }],
			},
			{
				type: "audio",
				id: "track_forest_of_elves",
				title: "Forest of Elves",
				duration: 94,
				filename: "Album04/Forest_of_Elves.mp3",
				lyrics: [{ time: 0, text: "Forest of Elves" }],
			},
		],
	},
	{
		id: "album05",
		title: "@WORLD_Ev8", // 흐린 기억 속의 나라
		author: "LastOrigin",
		image: "album05",
		songs: [
			{
				type: "audio",
				id: "track_noire_01",
				title: "Noire A",
				duration: 104,
				filename: "Album05/Noire_01.mp3",
				lyrics: [{ time: 0, text: "Noire 01" }],
			},
			{
				type: "audio",
				id: "track_noire_02",
				title: "Noire B",
				duration: 104,
				filename: "Album05/Noire_02.mp3",
				lyrics: [{ time: 0, text: "Noire 02" }],
			},
			{
				type: "audio",
				id: "track_mystic",
				title: "Mystic",
				duration: 95,
				filename: "Album05/Mystic.mp3",
				lyrics: [{ time: 0, text: "Mystic" }],
			},
		],
	},
	{
		id: "album06",
		title: "@WORLD_Ev11", // Project ORCA
		author: "LastOrigin",
		image: "album06",
		songs: [
			{
				type: "audio",
				id: "track_starlight",
				title: "Lover Lover (MR)",
				duration: 89,
				filename: "Album06/LoverLover.mp3",
				lyrics: [{ time: 0, text: "Lover Lover (MR)" }],
			},
			{
				type: "audio",
				id: "track_heartbeatome",
				title: "두근☆두근 반짝★반짝 (MR)",
				duration: 103,
				filename: "Album06/HeartbeatOME.mp3",
				lyrics: [{ time: 0, text: "두근☆두근 반짝★반짝 (MR)" }],
			},
			{
				type: "audio",
				id: "track_starlight",
				title: "외로운 별의 노래 (MR)",
				duration: 114,
				filename: "Album06/Starlight.mp3",
				lyrics: [{ time: 0, text: "외로운 별의 노래 (MR)" }],
			},
			{
				type: "audio",
				id: "track_songforyou",
				title: "그대는 나에게 (MR)",
				duration: 68,
				filename: "Album06/SongForYou.mp3",
				lyrics: [{ time: 0, text: "그대는 나에게 (MR)" }],
			},
			{
				type: "audio",
				id: "track_withyou_01",
				title: "With You (MR) A",
				duration: 80,
				filename: "Album06/WithYou_01.mp3",
				lyrics: [{ time: 0, text: "With You (MR) 01" }],
			},
			{
				type: "audio",
				id: "track_withyou_02",
				title: "With You (MR) B",
				duration: 164,
				filename: "Album06/WithYou_02.mp3",
				lyrics: [{ time: 0, text: "With You (MR) 02" }],
			},
		],
	},
	{
		id: "album07",
		title: "@WORLD_Ev12", // 빛이 들지 않는 성역
		author: "LastOrigin",
		image: "album07",
		songs: [
			{
				type: "audio",
				id: "track_moment",
				title: "잠시 (MR)",
				duration: 158,
				filename: "Album07/Moment.mp3",
				lyrics: [{ time: 0, text: "잠시 (MR)" }],
			},
		],
	},
	{
		id: "album08",
		title: "@WORLD_Ev14", // 영원한 겨울의 방주
		author: "LastOrigin",
		image: "album08",
		songs: [
			{
				type: "audio",
				id: "track_noire_01",
				title: "Memory of Time",
				duration: 109,
				filename: "Album08/MemoryofTime.mp3",
				lyrics: [{ time: 0, text: "Memory of Time" }],
			},
			{
				type: "audio",
				id: "track_noire_02",
				title: "Ark of Memory A",
				duration: 88,
				filename: "Album08/ArkofMemory_01.mp3",
				lyrics: [{ time: 0, text: "Ark of Memory 01" }],
			},
			{
				type: "audio",
				id: "track_mystic",
				title: "Ark of Memory B",
				duration: 89,
				filename: "Album08/ArkofMemory_02.mp3",
				lyrics: [{ time: 0, text: "Ark of Memory 02" }],
			},
		],
	},

	{
		id: "album_projectorca_kr",
		title: "Project ORCA",
		author: "스카이나이츠 & 뮤즈",
		image: "album_projectorca",
		songs: [
			{
				type: "youtube",
				id: "track1",
				title: "Lover Lover",
				duration: 201,
				url: "WVm7nZ9wz3M",
				lyrics: [
					{ time: 0, text: "Lover Lover - 스카이나이츠" },
					{ time: 0, text: "" },
					{ time: 0.13, text: "Oh oh oh oh oh 나나나나" },
					{ time: 3.21, text: "Oh oh oh oh oh 나나나나" },
					{ time: 7.08, text: "저 하늘 끝까지 갈게" },
					{ time: 10.17, text: "빛나는 이 길을 따라" },
					{ time: 14.05, text: "One Two Spotlight" },
					{ time: 18, text: "" },
					{ time: 36.22, text: "어쩜 이렇게 반짝일까" },
					{ time: 40.1, text: "저기 구름도 멈춰볼걸" },
					{ time: 43.21, text: "그래 반짝반짝이는" },
					{ time: 48, text: "우리를 봐줄래" },
					{ time: 50.19, text: "무대 위의 린티는 어때" },
					{ time: 54.09, text: "자꾸자꾸만 보고 싶지 (인정)" },
					{ time: 57.19, text: "빛날거야" },
					{ time: 60.21, text: "또 반짝 반짝 반짝" },
					{ time: 62.14, text: "또 두근 두근 두근" },
					{ time: 64.08, text: "함께 춤출거야 (예 예 예)" },
					{ time: 68.02, text: "Lover Lover Lover" },
					{ time: 69.13, text: "저 하늘 넘어 높이" },
					{ time: 71.18, text: "날아갈게 그대를 따라서" },
					{ time: 75.04, text: "끝없이 펼쳐진 하늘 위로" },
					{ time: 78.15, text: "Oh oh oh oh oh 날아갈게 (예 예)" },
					{ time: 82.04, text: "Lover Lover 밤하늘 별처럼" },
					{ time: 86.22, text: "날 향해 비춰줘" },
					{ time: 89.02, text: "당신과 함께 해피엔딩을" },
					{ time: 92.15, text: "Oh oh oh oh oh 나나" },
					{ time: 96, text: "Oh oh oh oh oh 예" },
					{ time: 100, text: "" },
					{ time: 102.14, text: "마법소녀 모모처럼 상큼하게" },
					{ time: 109.12, text: "그댈 위해 웃을거야" },
					{ time: 113.05, text: "계속 지켜봐 줄래요" },
					{ time: 116.21, text: "무대 위의 린티는 어때" },
					{ time: 120.09, text: "자꾸 자꾸만 보고 싶지 (인정)" },
					{ time: 123.21, text: "빛날거야" },
					{ time: 126.21, text: "또 반짝 반짝 반짝" },
					{ time: 128.15, text: "또 두근 두근 두근" },
					{ time: 130.1, text: "함께 춤출거야 (예 예 예)" },
					{ time: 134.06, text: "Lover Lover Lover" },
					{ time: 135.16, text: "저 하늘 넘어 높이" },
					{ time: 137.19, text: "날아갈게 그대를 따라서" },
					{ time: 141.04, text: "끝없이 펼쳐진 하늘 위로" },
					{ time: 144.17, text: "Oh oh oh oh oh 날아갈게 (예 예)" },
					{ time: 148.05, text: "Lover Lover 밤하늘 별처럼" },
					{ time: 152.24, text: "날 향해 비춰줘" },
					{ time: 155.04, text: "당신과 함께 해피엔딩을" },
					{ time: 158.16, text: "꿈 꿀꺼니까" },
					{ time: 162.04, text: "Lover Lover 약속해 줄래요" },
					{ time: 165.15, text: "Lover Lover 함께해 주기를" },
					{ time: 169.04, text: "이 세상을 우리의 색으로" },
					{ time: 172.12, text: "채울 테니까 (예 예)" },
					{ time: 176.01, text: "Lover Lover 저 하늘 넘어 높이" },
					{ time: 179.12, text: "날아갈게 그대를 따라서" },
					{ time: 183, text: "끝없이 펼쳐진 하늘 위로" },
					{ time: 186.11, text: "Oh oh oh oh oh 예 예" },
					{ time: 189.22, text: "Oh oh oh oh oh 예" },
					{ time: 195.83, text: "(스카이나이츠)" },
					{ time: 198, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track2",
				title: "두근☆두근 반짝★반짝",
				duration: 227,
				url: "1aTx4aofCbg",
				lyrics: [
					{ time: 0, text: "두근☆두근 반짝★반짝 - 민트초코쉐이크" },
					{ time: 1, text: "" },
					{ time: 2.09, text: "이건 내 비밀 이야기" },
					{ time: 4.21, text: "잘 들어줄래 Yo Boy" },
					{ time: 8.11, text: "Listen my first secret story (들어봐)" },
					{ time: 12.11, text: "들어줄래 우리의 얘기" },
					{ time: 15.04, text: "그대와 나 사이의 얘기" },
					{ time: 17.22, text: "좋아 좋아 시작해볼까" },
					{ time: 20.06, text: "우리의 첫 걸음" },
					{ time: 25.12, text: "(예)" },
					{ time: 26.08, text: "그래 그대 그대는 내게" },
					{ time: 28.21, text: "챙기고픈 유일한 사랑" },
					{ time: 31.14, text: "그래 그대는 내게" },
					{ time: 34.06, text: "빛나 빛나는 태양" },
					{ time: 37, text: "단순하고 아주 가끔은" },
					{ time: 39.19, text: "철이 없어 보이긴해도" },
					{ time: 42.11, text: "Love Love 사랑스러워" },
					{ time: 45.03, text: "Love Love 사랑스러워" },
					{ time: 47.2, text: "우 그대는 내 마음을 눈치챈걸까" },
					{ time: 52.22, text: "오 이런 내 마음을 들켜버릴 것 같은데" },
					{ time: 58.07, text: "꾸 꾸 꾸 꿈을 꿨죠" },
					{ time: 60.21, text: "그 그 그 그대가 내게" },
					{ time: 63.14, text: "바 바 바 반했다고" },
					{ time: 66.08, text: "고백하는 그런 꿈을" },
					{ time: 69.02, text: "꼭 꼭 꼭 그럴거야" },
					{ time: 71.18, text: "Love Love Love 그대는 내게" },
					{ time: 74.13, text: "Fall in love Love me babe" },
					{ time: 77.06, text: "Love me babe Love me babe" },
					{ time: 81.03, text: "" },
					{ time: 91.03, text: "결심했어 보여줄거야" },
					{ time: 93.23, text: "반짝반짝 귀여운 모습" },
					{ time: 96.17, text: "첫번째는 그대를 향해" },
					{ time: 99.06, text: "아이컨택트 (예)" },
					{ time: 101.94, text: "두번째는 자연스럽게" },
					{ time: 104.19, text: "옷깃 위에 먼지를 털기" },
					{ time: 107.14, text: "세번째는 실수를 한 척" },
					{ time: 109.63, text: "안기는거야 어때" },
					{ time: 112.15, text: "우 그대는 내 마음을 눈치챈걸까" },
					{ time: 117.72, text: "오 이런 내 마음을 들켜버릴 것 같은데" },
					{ time: 123.05, text: "꾸 꾸 꾸 꿈을 꿨죠" },
					{ time: 125.54, text: "그 그 그 그대가 내게" },
					{ time: 128.48, text: "바 바 바 반했다고" },
					{ time: 131.1, text: "고백하는 그런 꿈을" },
					{ time: 134.05, text: "꼭 꼭 꼭 그럴거야" },
					{ time: 136.21, text: "Love Love Love 그대는 내게" },
					{ time: 139.16, text: "Fall in love Love me babe" },
					{ time: 142.11, text: "Love me babe Love me babe" },
					{ time: 145, text: "머리부터 발끝까지 꽃 향기로 뿜뿜" },
					{ time: 147.39, text: "내 마음도 봄봄 사랑인거야 boy" },
					{ time: 150.14, text: "솔직히 대답해 줄래요" },
					{ time: 153.08, text: "그대에게 맞는 그런 내가 맞나요" },
					{ time: 156.37, text: "그댄 나를 어떻게 생각해" },
					{ time: 159, text: "(빙빙 돌지 말고 솔직하게 말해줘)" },
					{ time: 161.19, text: "그댄 내게 정말 소중한데" },
					{ time: 166.2, text: "오 그대에게 이런 내 마음을 말할래" },
					{ time: 172, text: "오 그대에게 나의 속마음을 꼭 말할거야" },
					{ time: 177.11, text: "꾸 꾸 꾸 꿈을 꿨죠" },
					{ time: 180.04, text: "그 그 그 그대가 내게" },
					{ time: 182.22, text: "바 바 바 반했다고" },
					{ time: 185.15, text: "고백하는 그런 꿈을" },
					{ time: 188.09, text: "꼭 꼭 꼭 그럴거야" },
					{ time: 191.04, text: "Love Love Love 그대는 내게" },
					{ time: 193.61, text: "Fall in love Love me babe" },
					{ time: 196.13, text: "Love me babe Love me babe" },
					{ time: 199.36, text: "그댄 나를 어떻게 생각해" },
					{ time: 202.28, text: "(빙빙 돌지 말고 솔직하게 말해줘)" },
					{ time: 205.02, text: "그댄 내게 정말 소중한데" },
					{ time: 210.08, text: "나 좋아하니까" },
					{ time: 214.08, text: "좋아하니까" },
					{ time: 216.24, text: "이런 내게 반해줄래요" },
					{ time: 222, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track3",
				title: "외로운 별의 노래",
				duration: 261,
				url: "gCpaVcP_QA0",
				lyrics: [
					{ time: 0, text: "외로운 별의 노래 - Blooming Heart" },
					{ time: 8, text: "" },
					{ time: 11.01, text: "올려다본 저 밤하늘 늘 반짝이던 별무리" },
					{ time: 16.02, text: "멀기만 하던 저 별이 내 곁에 내려왔죠" },
					{ time: 21.05, text: "외톨이인 나에게 따뜻한 손을 내밀어" },
					{ time: 26.09, text: "준 너의 온기를 느껴 You're my Shining Star" },
					{ time: 32.01, text: "우리들의 마음 속 가장 아름다운 별이 되어" },
					{ time: 37.05, text: "비춰주는 그대에게" },
					{ time: 40.13, text: "그대에게 전하는 별들의 노래" },
					{ time: 46.11, text: "저 은하수 너머 밝게 비추는 네 품에 안겨" },
					{ time: 51.06, text: "차갑고 어두운 밤 외롭게 빛나는" },
					{ time: 56.08, text: "상냥한 그대의 곁을 지켜줄게" },
					{ time: 60.18, text: "별빛처럼 빛나는 사랑의 노래" },
					{ time: 66.2, text: "강한 척 눈웃음 짓는 그대를 감싸안고서" },
					{ time: 71.07, text: "까만 밤을 밝게 비추는 별자리가 되어" },
					{ time: 77.02, text: "샛별처럼 빛나는 너의 곁에 있을게" },
					{ time: 92.1, text: "밝아오지 않는 밤엔 네 목소리를 들려줘" },
					{ time: 97.2, text: "어둠 속에서 길을 헤매일 땐 내 손을 잡아" },
					{ time: 102.22, text: "둘만의 하늘 아래 에서라면 두렵지 않아" },
					{ time: 108.01, text: "내가 너를 비춰줄게 I'm your Shining Star" },
					{ time: 113.16, text: "우리 둘의 마음 속 가장 아름다운 별이 되어" },
					{ time: 118.21, text: "비춰주는 그대에게" },
					{ time: 122.02, text: "그대에게 전하는 별들의 노래" },
					{ time: 128.02, text: "저 은하수 너머 밝게 비추는 네 품에 안겨" },
					{ time: 132.23, text: "차갑고 어두운 밤 외롭게 빛나는" },
					{ time: 138.02, text: "상냥한 그대의 곁을 지켜줄게" },
					{ time: 142.13, text: "별빛처럼 빛나는 사랑의 노래" },
					{ time: 148.14, text: "강한 척 눈웃음 짓는 그대를 감싸안고서" },
					{ time: 153, text: "까만 밤을 밝게 비추는 별자리가 되어" },
					{ time: 159.02, text: "샛별처럼 빛나는 너의 곁에 있을게" },
					{ time: 184.16, text: "영원의 끝에서 날 비추는 Your Starlight" },
					{ time: 189.17, text: "그 빛만을 따라서 저 하늘 저 너머까지" },
					{ time: 194.21, text: "약속의 혜성처럼 그대를 향해" },
					{ time: 199.23, text: "까만 밤을 날아서" },
					{ time: 203.18, text: "그대에게 전하는 사랑의 노래" },
					{ time: 210.02, text: "하늘 높이 날아 너에게 안기고 싶어" },
					{ time: 214.15, text: "별이 빛나는 밤 나만을 비추는" },
					{ time: 219.19, text: "외로운 나를 안아준 그대에게" },
					{ time: 225.03, text: "하루하루 커져만 가는 내 마음 햇살처럼 따뜻해져" },
					{ time: 230.09, text: "자꾸자꾸 커져만 가는 이 말" },
					{ time: 232.86, text: "너를 사랑해" },
					{ time: 234.15, text: "이 세상에 가장 눈부신 별빛이 되어서" },
					{ time: 240.19, text: "영원처럼 빛나는 수호성이 돼 줄게" },
					{ time: 249, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track4",
				title: "그대는 나에게",
				duration: 247,
				url: "WNx0wMHZY5I",
				lyrics: [
					{ time: 0, text: "그대는 나에게 - 뮤즈" },
					{ time: 16, text: "" },
					{ time: 19.2, text: "어두운 내 방엔 작은 빛이 있죠" },
					{ time: 28.09, text: "그건 모니터 속 무대" },
					{ time: 34.24, text: "그댈 보면서 덧없이 꿈꿨죠" },
					{ time: 43.12, text: "내가 노래하는 모습을" },
					{ time: 50.03, text: "언제나 나에게 두 손을 내밀어 준 널" },
					{ time: 58.2, text: "위해서 용기내보려 해" },
					{ time: 64.11, text: "들어 줄래요 조금은 어색해도" },
					{ time: 72.17, text: "마음을 전하는 내 노랠 들어줄래" },
					{ time: 79.2, text: "그대는 나의 나의 별빛이니까" },
					{ time: 87.24, text: "내 마음 가득히 담아 노래 할게요 꼭" },
					{ time: 116.24, text: "지난 날 기억 다 지워 버릴거야" },
					{ time: 125.12, text: "모두를 위해서 노래 할거야" },
					{ time: 131.04, text: "내 맘 담아서 너만을 위한 노래 부를테니까" },
					{ time: 142.17, text: "들어 줄래요 조금은 어색해도" },
					{ time: 150.21, text: "두렵지 않아 난 이제는 달라졌어" },
					{ time: 157.19, text: "그대는 나의 나의 별빛이니까" },
					{ time: 167.09, text: "내 마음 속 빛나는 별" },
					{ time: 177.12, text: "캄캄한 내 맘 밝게 비춰준 널" },
					{ time: 185.1, text: "안고 싶어" },
					{ time: 191, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track5",
				title: "With You",
				duration: 270,
				url: "WSkk61cBSTM",
				lyrics: [
					{ time: 0, text: "With You - 스카이나이츠 & 뮤즈" },
					{ time: 0, text: "" },
					{ time: 0.5, text: "빛나는 꿈과 함께" },
					{ time: 2.22, text: "화려한 스테이지 위로" },
					{ time: 6.1, text: "채워가는 우리의 Story" },
					{ time: 9.1, text: "이제 시작해 With you" },
					{ time: 15, text: "" },
					{ time: 23.03, text: "밤하늘 고개 들어 바라봐" },
					{ time: 28.16, text: "내 모습 비춰주는 빛 (너라는 별빛)" },
					{ time: 34.02, text: "저 구름 사이 속에 감춰져 흐려져도" },
					{ time: 39.13, text: "언제까지나 함께 있을 거라고 해줘" },
					{ time: 45.03, text: "희미했던 내 캔버스 위에" },
					{ time: 48.01, text: "하나둘씩 그려지는 네 마음" },
					{ time: 50.2, text: "그건 마치 무지개빛 사랑" },
					{ time: 56.01, text: "반짝반짝 그 온기를 따라" },
					{ time: 59, text: "채워지는 나의 팔레트로" },
					{ time: 61.13, text: "너와 내가 함께 만드는 미래 그리자" },
					{ time: 66.07, text: "I sing you 널 위한 노래" },
					{ time: 68.18, text: "저 멀리 울려 퍼지면" },
					{ time: 72.07, text: "하늘 너머 내 목소리가" },
					{ time: 75.06, text: "너에게 닿을까" },
					{ time: 77.06, text: "빛나는 꿈과 함께" },
					{ time: 79.17, text: "모두의 사랑을 담아" },
					{ time: 83.05, text: "채워가는 우리의 Story" },
					{ time: 86.06, text: "지금 이곳에 With you" },
					{ time: 92, text: "" },
					{ time: 99.21, text: "내 가슴속에 잠든 소망은" },
					{ time: 105.11, text: "이 작은 노랫소리로 (커져 가는걸)" },
					{ time: 110.21, text: "뜻대로 되지 않아 다가올 불안함도" },
					{ time: 116.09, text: "우리가 함께라면 이겨나갈 수 있어" },
					{ time: 121.2, text: "힘이 나는 네 주문 앞에서" },
					{ time: 124.2, text: "사라지는 망설임과 두려움" },
					{ time: 127.15, text: "그건 마치 마법 같은 사랑" },
					{ time: 132.2, text: "네가 그린 동화 같은 미래로" },
					{ time: 135.2, text: "눈부시는 날개 힘껏 펼쳐" },
					{ time: 138.09, text: "함께 가자 좀 더 밝은 저 빛을 향해서" },
					{ time: 143.02, text: "I sing you 널 위한 노래" },
					{ time: 145.13, text: "저 멀리 울려 퍼지면" },
					{ time: 149, text: "하늘 너머 내 목소리가" },
					{ time: 152.02, text: "너에게 닿을까" },
					{ time: 154.02, text: "빛나는 꿈과 함께" },
					{ time: 156.12, text: "모두의 사랑을 담아" },
					{ time: 159.24, text: "채워가는 우리의 Story" },
					{ time: 162.24, text: "지금 이곳에 With you" },
					{ time: 168, text: "" },
					{ time: 187.08, text: "어떤 사람들에겐" },
					{ time: 190.16, text: "힘없고 하찮은" },
					{ time: 193.11, text: "사랑 노래처럼 들리겠지만" },
					{ time: 198.16, text: "너와 나의 소중한 추억들" },
					{ time: 201.15, text: "퍼즐처럼 하나 된 멜로디" },
					{ time: 204.04, text: "이 노래를 저 우주 끝까지 들리게 외칠게" },
					{ time: 214.06, text: "I sing you 널 위한 노래" },
					{ time: 216.21, text: "저 멀리 울려펴지면" },
					{ time: 220.08, text: "하늘 너머 내 목소리가" },
					{ time: 223.09, text: "너에게 닿을까" },
					{ time: 225.09, text: "빛나는 꿈과 함께" },
					{ time: 227.2, text: "모두의 사랑을 담아" },
					{ time: 231.07, text: "채워가는 우리의 Story" },
					{ time: 234.09, text: "영원히 함께 With you" },
					{ time: 241.21, text: "For you" },
					{ time: 244, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track6",
				title: "잠시",
				duration: 295,
				url: "FJHuhO77YWU",
				lyrics: [
					{ time: 0, text: "잠시 - 뮤즈" },
					{ time: 0, text: "" },
					{ time: 1, text: "사실은 아직도 잘 모르는 길처럼 헤매이고 있어" },
					{ time: 16, text: "여전히 나에게는 해야만 한 것들을 짊어진 채 서있어" },
					{ time: 30, text: "" },
					{ time: 32, text: "가끔은 서러운 마음에 부딪쳐서" },
					{ time: 41, text: "아픈 기억들이 눈앞에 다가오면" },
					{ time: 51.5, text: "알 수 없는 현실이 내게 상처를 주곤해" },
					{ time: 62.5, text: "" },
					{ time: 63.5, text: "떨어지는 소나기에 오랜 시간 버텨왔던" },
					{ time: 70.5, text: "내 눈물로 물들어가 나를 지켜주던 " },
					{ time: 78.5, text: "너의 모습마저 희미해져" },
					{ time: 83.5, text: "그럴 땐 눈을 감아 슬픈 기억 속에서" },
					{ time: 94, text: "잠시 쉬어도 돼" },
					{ time: 102, text: "" },
					{ time: 128, text: "차가운 바람이 찾아오는 슬픔에 문득 혼자 있어" },
					{ time: 143, text: "한없이 외로운 걸 너무나 잘 알아서" },
					{ time: 153.5, text: "무너지는 어느 날" },
					{ time: 158.5, text: "" },
					{ time: 160, text: "떨어지는 소나기에 오랜 시간 버텨왔던" },
					{ time: 167, text: "내 눈물로 물들어가 나를 지켜주던" },
					{ time: 175.5, text: "너의 모습마저 희미해져" },
					{ time: 180, text: "그럴 땐 눈을 감아 슬픈 기억 속에서" },
					{ time: 189, text: "잠시 넘어질 듯이 힘겹게 내딛어" },
					{ time: 198, text: "한 걸음 한 걸음 그대로 나아가" },
					{ time: 205, text: "" },
					{ time: 206.5, text: "더 이상은 주저하지마" },
					{ time: 211, text: "고여버린 마음 위에 돌아가도" },
					{ time: 218, text: "놓치지는 않아" },
					{ time: 220.5, text: "" },
					{ time: 222, text: "행복했던 추억 바라보며" },
					{ time: 227, text: "그대로 눈을 감아" },
					{ time: 233, text: "모든 바램속에서" },
					{ time: 239, text: "멈춰 잠시" },
					{ time: 245, text: "" },
				],
			},
		],
	},
	{
		id: "album_missorca_2nd",
		title: "MISS ORCA 2nd season",
		author: "B-11 나이트앤젤 & 멸망의 메이 & 천향의 히루메",
		image: "album_missorca_2nd",
		songs: [
			{
				type: "placeholder",
				id: "track1",
				title: "호접지몽",
				duration: 348,
				lyrics: [
					{ time: 0, text: "호접지몽 - 천향의 히루메" },
					{ time: 19.6, text: "" },
					{ time: 22.43, text: "달님이 계신 하얀 언덕 너머에" },
					{ time: 28.26, text: "파란빛을 비추며 춤을 추었네" },
					{ time: 33.74, text: "나래짓 하며 길을 그린 자리엔" },
					{ time: 39.47, text: "그대의 흔적만 남았네" },
					{ time: 44.83, text: "다래꽃 송아리 열린 가람길 따라" },
					{ time: 50.46, text: "펼쳐진 꽃구름 아래서" },
					{ time: 56.09, text: "소첩을 감싸 안아준 그대 손길이" },
					{ time: 61.95, text: "이제는 아스라하구나" },
					{ time: 67.23, text: "" },
					{ time: 70.57, text: "한 번 더 날 안아주거라" },
					{ time: 76.18, text: "온 세상 빛나던 날처럼" },
					{ time: 81.87, text: "꽃바람에 흩날리는 작은 나래로" },
					{ time: 87.43, text: "그대를 나 맞이하노라" },
					{ time: 93.07, text: "희 여울 가람을 넘어서" },
					{ time: 98.73, text: "오색 빛 다남 길 지난 곳" },
					{ time: 104.37, text: "살사리꽃 인사하는 하얀 언덕에" },
					{ time: 110.06, text: "도닐며 나 기다릴 테니" },
					{ time: 115.47, text: "피워 내는 꽃망울처럼" },
					{ time: 121.17, text: "" },
					{ time: 143.88, text: "여우비 내려 보슬거린 소리에" },
					{ time: 149.58, text: "눈뜨면 쌓인 추억이 흘러갈때면" },
					{ time: 155.26, text: "서투른 그대 눈물 같아 보여서" },
					{ time: 160.91, text: "소첩도 마음이 아리네" },
					{ time: 166.34, text: "한아름 따다 엮은 꽃 타래처럼" },
					{ time: 172.11, text: "해맑던 그대의 모습을" },
					{ time: 177.55, text: "함초롬히 마음속에 담아뒀지만" },
					{ time: 183.49, text: "점점 더 아득해지노라" },
					{ time: 192.1, text: "다시 한번 웃어주거라" },
					{ time: 197.67, text: "미리내 꽃피던 날에는" },
					{ time: 203.14, text: "달무리 속 꼬리별이 손짓하듯이" },
					{ time: 208.89, text: "그리며 나 바라볼테니" },
					{ time: 214.48, text: "희 여울 가람을 넘어서" },
					{ time: 220.22, text: "오색 빛 다남 길 있던 곳" },
					{ time: 225.95, text: "도라지 꽃 피어나는 푸른 언덕에" },
					{ time: 231.57, text: "올라서 나 서약하노라" },
					{ time: 237.05, text: "그대와 나 이제 영원히" },
					{ time: 243.15, text: "" },
					{ time: 269.41, text: "돋을볕이 비추는 시에" },
					{ time: 275.18, text: "오색 빛 다남 길 지난 곳" },
					{ time: 280.86, text: "살사리꽃 인사하던 하얀 언덕에" },
					{ time: 286.71, text: "또 다시 나 돌아왔노라" },
					{ time: 292.2, text: "물 비늘 목소리 따라서" },
					{ time: 297.6, text: "저 멀리 그대가 보이네" },
					{ time: 303.3, text: "여전히 날 향해 누그럽게 웃노니" },
					{ time: 309.1, text: "이제는 떠나지 않으리" },
					{ time: 314.59, text: "영원히 그대의 품속에" },
					{ time: 320.33, text: "" },
					{ time: 337.38, text: "영원히 그대 꿈 속에" },
					{ time: 343.17, text: "" },
				],
			},
			{
				type: "placeholder",
				id: "track2",
				title: "MY LOVE",
				duration: 238,
				lyrics: [
					{ time: 0, text: "My Love - 멸망의 메이" },
					{ time: 9.22, text: "" },
					{ time: 13.39, text: "유난히 빛난 너의 웃는 모습" },
					{ time: 20.66, text: "내겐 처음 느끼는 감정에" },
					{ time: 27.36, text: "창가에 비친 햇살처럼 따스한" },
					{ time: 34.32, text: "내 마음 너에게 어떻게 전할까" },
					{ time: 41.12, text: "파란 하늘에 너를 떠올려보고" },
					{ time: 45.39, text: "그 옆에는 나를 그려보는 걸" },
					{ time: 48.91, text: "하얀 구름 사이 속에 들어가" },
					{ time: 52.6, text: "우리만의 세상을 만들어" },
					{ time: 55.85, text: "너와 마주치는 그 순간들이" },
					{ time: 59.44, text: "내게는 너무나도 떨리는 걸" },
					{ time: 62.99, text: "아직 조금 서툰 나의 마음을" },
					{ time: 66.62, text: "언제쯤 너에게 고백할까" },
					{ time: 70.01, text: "My Love" },
					{ time: 76.23, text: "" },
					{ time: 98.07, text: "어느새 나는 널 바라만 봐도" },
					{ time: 104.75, text: "어쩜 이리도 설레이는지" },
					{ time: 111.84, text: "소중한 추억 하나둘 쌓여가는" },
					{ time: 119.25, text: "이 마음 너에게 표현해도 될까" },
					{ time: 125.78, text: "나도 모르게 웃음이 새어 나와" },
					{ time: 130.07, text: "커져 버린 마음이 자꾸만 날" },
					{ time: 133.56, text: "하루 온 종일 네 생각뿐인걸" },
					{ time: 137.43, text: "이제는 네게 말해도 될까" },
					{ time: 140.63, text: "바보처럼 망설이다 지나간" },
					{ time: 144.22, text: "긴긴 하루의 저녁 노을빛이" },
					{ time: 147.7, text: "어서 너에게 말을 건네라며" },
					{ time: 151.34, text: "환하게 나를 비춰주네" },
					{ time: 154.68, text: "My Love" },
					{ time: 156.21, text: "너도 날 같은 마음일까" },
					{ time: 161.61, text: "오직 너 하나뿐인 사랑" },
					{ time: 166.95, text: "My Love" },
					{ time: 170.26, text: "널 생각할 때마다 보고 싶은걸" },
					{ time: 174.14, text: "커져 버린 마음에 용기 내어" },
					{ time: 177.75, text: "하루 온종일 네 생각뿐인걸" },
					{ time: 181.38, text: "이제는 네게 말하고 싶어" },
					{ time: 184.64, text: "항상 너와 나 함께 있을 때면" },
					{ time: 188.2, text: "모든 세상을 다 가진 것 같아" },
					{ time: 191.84, text: "눈을 감아도 너만 보이는 걸" },
					{ time: 195.59, text: "살며시 너에게 다가갈게" },
					{ time: 199, text: "My Love" },
					{ time: 202.15, text: "" },
				],
			},
			{
				type: "placeholder",
				id: "track3",
				title: "FLIGHT AGAIN",
				duration: 262,
				lyrics: [
					{ time: 0, text: "FLIGHT AGAIN - B-11 나이트앤젤" },
					{ time: 0.83, text: "" },
					{ time: 1.35, text: "끝없는 어둠이 펼쳐져도" },
					{ time: 6.16, text: "힘에 한계는 없어" },
					{ time: 8.91, text: "이 출력은 OVER DRIVE" },
					{ time: 14.28, text: "" },
					{ time: 24.77, text: "바람이 잠드는 새벽에" },
					{ time: 29.03, text: "수많은 이들이 구원을 외치네" },
					{ time: 35.86, text: "희망을 갈구하던 불씨는" },
					{ time: 39.58, text: "빛을 서서히 잃어가지만" },
					{ time: 42.49, text: "시간은 기다리지 않네" },
					{ time: 46.11, text: "검게 물든 신념과 지쳐 버린 마음은" },
					{ time: 51.28, text: "제트 불길 속에 태워버리고" },
					{ time: 56.98, text: "이제 창공을 향해" },
					{ time: 59.92, text: "철의 날개 펼치며" },
					{ time: 62.2, text: "최고로 풀 스로틀" },
					{ time: 65.55, text: "끝없는 비상" },
					{ time: 67.74, text: "끓어오르는 열정으로" },
					{ time: 71.36, text: "타오르는 해처럼 빛처럼 박차 나아가" },
					{ time: 76.67, text: "성층권을 넘어 피워내는 붉은 불꽃은" },
					{ time: 82.36, text: "단 하나뿐인 무한한 의지" },
					{ time: 86.52, text: "이정표의 끝까지 Fly Away" },
					{ time: 93.93, text: "" },
					{ time: 96.55, text: "노을에 그을린 비행운" },
					{ time: 101.28, text: "은빛 바다 위를, 뒤따라 바라봐" },
					{ time: 107.72, text: "타오르는 마음 품에 안고" },
					{ time: 111.89, text: "이글거리는 결의의 눈빛" },
					{ time: 114.44, text: "기세로는 절대 지지 않아" },
					{ time: 118.18, text: "반복되는 쟁명은 악몽 같은 신기루" },
					{ time: 123.31, text: "제트 엔진 속에 부숴 버리고" },
					{ time: 128.76, text: "지평선 끝을 향해" },
					{ time: 131.89, text: "활주로를 달리며" },
					{ time: 134.23, text: "전력으로 Take Off" },
					{ time: 137.71, text: "끝없는 비상" },
					{ time: 140.09, text: "넘쳐흐르는 에너지로" },
					{ time: 143.51, text: "타오르는 해처럼 빛처럼 박차 나아가" },
					{ time: 149.04, text: "빨라지는 고동 슈퍼노바처럼 눈부신" },
					{ time: 154.34, text: "단 하나뿐인 확고한 맹세" },
					{ time: 158.81, text: "하늘 끝에 맺히는 Burning Star" },
					{ time: 168.11, text: "" },
					{ time: 184.62, text: "간절한 소망과 절망 속에서" },
					{ time: 189.51, text: "유성처럼 사라지는 마지막 그날까지" },
					{ time: 195.71, text: "잠긴 열쇠를 부숴" },
					{ time: 198.17, text: "초월한 속력으로 소리쳐라 소닉붐" },
					{ time: 204.23, text: "고요한 새벽 가끔 길 잃어 헤매지만" },
					{ time: 210.15, text: "다시 한번 일어서 털어내 계속 나아가" },
					{ time: 215.55, text: "어릴 적의 꿈이 멈춰버린 풍경이라면" },
					{ time: 221.27, text: "더 늦기 전에 Fly to the Sky" },
					{ time: 225.39, text: "더 높은 비상" },
					{ time: 227.74, text: "저 먼빛의 궤적을 따라서" },
					{ time: 232.98, text: "강하고 굳세게 박차 나아가" },
					{ time: 236.53, text: "깊은 어둠 뒤에 종말의 불꽃이 피어도" },
					{ time: 242.63, text: "멈추지 않는 염원의 서약" },
					{ time: 246.84, text: "이뤄지는 날까지 FLIGHT AGAIN" },
					{ time: 254.93, text: "" }

				],
			},
		],
	},
];
export default BGMAlbums;
