import { BGMAlbum } from "@/types/BGM";

const BGMAlbums: BGMAlbum[] = [
	{
		id: "album01",
		title: "LastOrigin Sound Track",
		author: "LastOrigin",
		image: "album01",
		songs: [
			{
				type: "audio",
				id: "track_title",
				title: "Title",
				duration: 61,
				filename: "Album01/Title.mp3",
				lyrics: [{ time: 0, text: "Title" }],
			},

			{
				type: "audio",
				id: "track_lobby",
				title: "Lobby",
				duration: 61,
				filename: "Album01/Lobby.mp3",
				lyrics: [{ time: 0, text: "Lobby" }],
			},
			{
				type: "audio",
				id: "track_valentine_01",
				title: "Valentine Day (Lobby)",
				duration: 62,
				filename: "Album01/Valentine_01.mp3",
				lyrics: [{ time: 0, text: "Valentine Day (Lobby)" }],
			},

			{
				type: "audio",
				id: "track_talk_01",
				title: "Talk A",
				duration: 61,
				filename: "Album01/Talk_01.mp3",
				lyrics: [{ time: 0, text: "Talk 01" }],
			},
			{
				type: "audio",
				id: "track_talk_02",
				title: "Talk B",
				duration: 59,
				filename: "Album01/Talk_02.mp3",
				lyrics: [{ time: 0, text: "Talk 02" }],
			},
			{
				type: "audio",
				id: "track_talk_03",
				title: "Talk C",
				duration: 63,
				filename: "Album01/Talk_03.mp3",
				lyrics: [{ time: 0, text: "Talk 03" }],
			},
			{
				type: "audio",
				id: "track_talk_04",
				title: "Talk D",
				duration: 61,
				filename: "Album01/Talk_04.mp3",
				lyrics: [{ time: 0, text: "Talk 04" }],
			},
			{
				type: "audio",
				id: "track_talk_05",
				title: "Talk E",
				duration: 65,
				filename: "Album01/Talk_05.mp3",
				lyrics: [{ time: 0, text: "Talk 05" }],
			},
			{
				type: "audio",
				id: "track_talk_06",
				title: "Talk F",
				duration: 94,
				filename: "Album01/Talk_06.mp3",
				lyrics: [{ time: 0, text: "Talk 06" }],
			},
			{
				type: "audio",
				id: "track_talk_07",
				title: "Talk G",
				duration: 93,
				filename: "Album01/Talk_07.mp3",
				lyrics: [{ time: 0, text: "Talk 07" }],
			},
			{
				type: "audio",
				id: "track_talk_08",
				title: "Talk H",
				duration: 162,
				filename: "Album01/Talk_08.mp3",
				lyrics: [{ time: 0, text: "Talk 08" }],
			},
			{
				type: "audio",
				id: "track_thrill_01",
				title: "Talk H - Thrill",
				duration: 75,
				filename: "Album01/Thrill_01.mp3",
				lyrics: [{ time: 0, text: "Thrill 01" }],
			},
			{
				type: "audio",
				id: "track_love_01",
				title: "Love A",
				duration: 156,
				filename: "Album01/Love_01.mp3",
				lyrics: [{ time: 0, text: "Love 01" }],
			},
			{
				type: "audio",
				id: "track_love_02",
				title: "Love B",
				duration: 127,
				filename: "Album01/Love_02.mp3",
				lyrics: [{ time: 0, text: "Love 02" }],
			},

			{
				type: "audio",
				id: "track_marriage_01",
				title: "Marriage - Elevator",
				duration: 11,
				filename: "Album01/Marriage_01.mp3",
				lyrics: [{ time: 0, text: "Marriage 01" }],
			},
			{
				type: "audio",
				id: "track_marriage_02",
				title: "Marriage - Deck",
				duration: 33,
				filename: "Album01/Marriage_02.mp3",
				lyrics: [{ time: 0, text: "Marriage 02" }],
			},

			{
				type: "audio",
				id: "track_battle_01",
				title: "Battle A",
				duration: 67,
				filename: "Album01/Battle_01.mp3",
				lyrics: [{ time: 0, text: "Battle 01" }],
			},
			{
				type: "audio",
				id: "track_battle_01_old",
				title: "Battle A (Old)",
				duration: 67,
				filename: "Album01/Battle_01b.mp3",
				lyrics: [{ time: 0, text: "Battle 01 (Old)" }],
			},
			{
				type: "audio",
				id: "track_battle_02",
				title: "Battle B",
				duration: 60,
				filename: "Album01/Battle_02.mp3",
				lyrics: [{ time: 0, text: "Battle 02" }],
			},
			{
				type: "audio",
				id: "track_battle_04",
				title: "Battle C",
				duration: 91,
				filename: "Album01/Battle_04.mp3",
				lyrics: [{ time: 0, text: "Battle 04" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_01",
				title: "Boss Battle A",
				duration: 62,
				filename: "Album01/Battle_Boss_01.mp3",
				lyrics: [{ time: 0, text: "Battle Boss 01" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_02",
				title: "Boss Battle B",
				duration: 58,
				filename: "Album01/Battle_Boss_02.mp3",
				lyrics: [{ time: 0, text: "Battle Boss 02" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_04",
				title: "Boss Battle D - Iron Prince",
				duration: 100,
				filename: "Album01/IronPrince.mp3",
				lyrics: [{ time: 0, text: "Iron Prince" }],
			},

			{
				type: "audio",
				id: "track_irontower",
				title: "Iron Tower",
				duration: 101,
				filename: "Album01/Sanctum.mp3",
				lyrics: [{ time: 0, text: "Sanctum" }],
			},
			{
				type: "audio",
				id: "track_irontower_battle",
				title: "Iron Tower Battle",
				duration: 67,
				filename: "Album01/Battle_05.mp3",
				lyrics: [{ time: 0, text: "Battle 05" }],
			},
			{
				type: "audio",
				id: "track_irontower_battle_boss",
				title: "Iron Tower Boss Battle",
				duration: 67,
				filename: "Album01/Battle_Boss_03.mp3",
				lyrics: [{ time: 0, text: "Battle Boss 03" }],
			},

			{
				type: "audio",
				id: "track_battle_10stage",
				title: "Battle Stage 10",
				duration: 121,
				filename: "Album01/Battle_10Stage.mp3",
				lyrics: [{ time: 0, text: "Battle Stage 10" }],
			},
			{
				type: "audio",
				id: "track_battle_boss_10stage",
				title: "Boss Battle Stage 10",
				duration: 146,
				filename: "Album01/Battle_Boss_10Stage.mp3",
				lyrics: [{ time: 0, text: "Battle Boss Stage 10" }],
			},
			{
				type: "audio",
				id: "track_funeral_for_mom",
				title: "Funeral for Mom",
				duration: 123,
				filename: "Album01/Funeral_For_Mom.mp3",
				lyrics: [{ time: 0, text: "Funeral for Mom" }],
			},
			{
				type: "audio",
				id: "track_missing_sisters",
				title: "Missing Sisters",
				duration: 142,
				filename: "Album01/Missing_Sisters.mp3",
				lyrics: [{ time: 0, text: "Missing Sisters" }],
			},
			{
				type: "audio",
				id: "track_stronghold_march",
				title: "Stronghold March",
				duration: 124,
				filename: "Album01/Stronghold_March.mp3",
				lyrics: [{ time: 0, text: "Stronghold March" }],
			},
			{
				type: "audio",
				id: "track_horror",
				title: "Horror",
				duration: 140,
				filename: "Album01/Horror.mp3",
				lyrics: [{ time: 0, text: "Horror" }],
			},
			{
				type: "audio",
				id: "track_beta",
				title: "Beta",
				duration: 127,
				filename: "Album01/Beta.mp3",
				lyrics: [{ time: 0, text: "Beta" }],
			},
			{
				type: "audio",
				id: "track_boss_beta",
				title: "Boss Beta",
				duration: 136,
				filename: "Album01/Boss_Beta.mp3",
				lyrics: [{ time: 0, text: "Boss Beta" }],
			},
			{
				type: "audio",
				id: "track_horror2",
				title: "Horror 2",
				duration: 138,
				filename: "Album01/Horror2.mp3",
				lyrics: [{ time: 0, text: "Horror 2" }],
			},
			{
				type: "audio",
				id: "track_coldwind",
				title: "Cold Wind",
				duration: 55,
				filename: "Album01/ColdWind.mp3",
				lyrics: [{ time: 0, text: "Cold Wind" }],
			},
			{
				type: "audio",
				id: "track_a_warm_world",
				title: "A Warm World",
				duration: 101,
				filename: "Album01/A_Warm_World.mp3",
				lyrics: [{ time: 0, text: "A Warm World" }],
			},
			{
				type: "audio",
				id: "track_tension01",
				title: "tension01",
				duration: 121,
				filename: "Album01/tension01.mp3",
				lyrics: [{ time: 0, text: "tension01" }],
			},
			{
				type: "audio",
				id: "track_tension02",
				title: "tension02",
				duration: 147,
				filename: "Album01/tension02.mp3",
				lyrics: [{ time: 0, text: "tension02" }],
			},
			{
				type: "audio",
				id: "track_a_warm_world",
				title: "A Warm World",
				duration: 101,
				filename: "Album01/A_Warm_World.mp3",
				lyrics: [{ time: 0, text: "A Warm World" }],
			},
			{
				type: "audio",
				id: "track_northern_front",
				title: "Northern Front",
				duration: 123,
				filename: "Album01/Northern_Front.mp3",
				lyrics: [{ time: 0, text: "Northern Front" }],
			},
			{
				type: "audio",
				id: "track_zeta_boss",
				title: "Zeta Boss",
				duration: 142,
				filename: "Album01/Zeta_Boss.mp3",
				lyrics: [{ time: 0, text: "Zeta Boss" }],
			},

			// 카테고리 없음 (외전 스토리)
			{
				type: "audio",
				id: "track_broken_heart",
				title: "Broken Heart (MR)",
				duration: 147,
				filename: "Album01/Broken_Heart.mp3",
				lyrics: [{ time: 0, text: "Broken Heart (MR)" }],
			},
		],
	},
	{
		id: "album02",
		title: "@WORLD_Ev3", // 만월의 야상곡
		author: "LastOrigin",
		image: "album02",
		songs: [
			{
				type: "audio",
				id: "track_battle_03",
				title: "Battle",
				duration: 60,
				filename: "Album02/Battle_03.mp3",
				lyrics: [{ time: 0, text: "Battle 03" }],
			},
		],
	},
	{
		id: "album03",
		title: "@WORLD_Ev5", // 세인트 오르카의 비밀작전
		author: "LastOrigin",
		image: "album03",
		songs: [
			{
				type: "audio",
				id: "track_christmas_01",
				title: "Christmas 01",
				duration: 64,
				filename: "Album03/Christmas_01.mp3",
				lyrics: [{ time: 0, text: "Christmas 01" }],
			},
			{
				type: "audio",
				id: "track_christmas_02",
				title: "Christmas 02 (Lobby)",
				duration: 62,
				filename: "Album03/Christmas_02.mp3",
				lyrics: [{ time: 0, text: "Christmas 02 (Lobby)" }],
			},
		],
	},
	{
		id: "album04",
		title: "@WORLD_Ev7", // 요정 마을의 아리아
		author: "LastOrigin",
		image: "album04",
		songs: [
			{
				type: "audio",
				id: "track_summer_01",
				title: "Summer 01",
				duration: 79,
				filename: "Album04/Summer_01.mp3",
				lyrics: [{ time: 0, text: "Summer 01" }],
			},
			{
				type: "audio",
				id: "track_summer_02",
				title: "Summer 02",
				duration: 79,
				filename: "Album04/Summer_02.mp3",
				lyrics: [{ time: 0, text: "Summer 02" }],
			},
			{
				type: "audio",
				id: "track_forest_of_elves",
				title: "Forest of Elves",
				duration: 94,
				filename: "Album04/Forest_of_Elves.mp3",
				lyrics: [{ time: 0, text: "Forest of Elves" }],
			},
		],
	},
	{
		id: "album05",
		title: "@WORLD_Ev8", // 흐린 기억 속의 나라
		author: "LastOrigin",
		image: "album05",
		songs: [
			{
				type: "audio",
				id: "track_noire_01",
				title: "Noire 01",
				duration: 104,
				filename: "Album05/Noire_01.mp3",
				lyrics: [{ time: 0, text: "Noire 01" }],
			},
			{
				type: "audio",
				id: "track_noire_02",
				title: "Noire 02",
				duration: 104,
				filename: "Album05/Noire_02.mp3",
				lyrics: [{ time: 0, text: "Noire 02" }],
			},
			{
				type: "audio",
				id: "track_mystic",
				title: "Mystic",
				duration: 95,
				filename: "Album05/Mystic.mp3",
				lyrics: [{ time: 0, text: "Mystic" }],
			},
		],
	},
	{
		id: "album06",
		title: "@WORLD_Ev11", // Project ORCA
		author: "LastOrigin",
		image: "album06",
		songs: [
			{
				type: "audio",
				id: "track_starlight",
				title: "Lover Lover (MR)",
				duration: 89,
				filename: "Album06/LoverLover.mp3",
				lyrics: [{ time: 0, text: "Lover Lover (MR)" }],
			},
			{
				type: "audio",
				id: "track_heartbeatome",
				title: "두근☆두근 반짝★반짝 (MR)",
				duration: 103,
				filename: "Album06/HeartbeatOME.mp3",
				lyrics: [{ time: 0, text: "두근☆두근 반짝★반짝 (MR)" }],
			},
			{
				type: "audio",
				id: "track_starlight",
				title: "외로운 별의 노래 (MR)",
				duration: 114,
				filename: "Album06/Starlight.mp3",
				lyrics: [{ time: 0, text: "외로운 별의 노래 (MR)" }],
			},
			{
				type: "audio",
				id: "track_songforyou",
				title: "그대는 나에게 (MR)",
				duration: 68,
				filename: "Album06/SongForYou.mp3",
				lyrics: [{ time: 0, text: "그대는 나에게 (MR)" }],
			},
			{
				type: "audio",
				id: "track_withyou_01",
				title: "With You (MR) 01",
				duration: 80,
				filename: "Album06/WithYou_01.mp3",
				lyrics: [{ time: 0, text: "With You (MR) 01" }],
			},
			{
				type: "audio",
				id: "track_withyou_02",
				title: "With You (MR) 02",
				duration: 164,
				filename: "Album06/WithYou_02.mp3",
				lyrics: [{ time: 0, text: "With You (MR) 02" }],
			},
		],
	},
	{
		id: "album07",
		title: "@WORLD_Ev12", // 빛이 들지 않는 성역
		author: "LastOrigin",
		image: "album07",
		songs: [
			{
				type: "audio",
				id: "track_moment",
				title: "잠시 (MR)",
				duration: 158,
				filename: "Album07/Moment.mp3",
				lyrics: [{ time: 0, text: "잠시 (MR)" }],
			},
		],
	},
	{
		id: "album08",
		title: "@WORLD_Ev14", // 영원한 겨울의 방주
		author: "LastOrigin",
		image: "album08",
		songs: [
			{
				type: "audio",
				id: "track_noire_01",
				title: "Memory of Time",
				duration: 109,
				filename: "Album08/MemoryofTime.mp3",
				lyrics: [{ time: 0, text: "Memory of Time" }],
			},
			{
				type: "audio",
				id: "track_noire_02",
				title: "Ark of Memory 01",
				duration: 88,
				filename: "Album08/ArkofMemory_01.mp3",
				lyrics: [{ time: 0, text: "Ark of Memory 01" }],
			},
			{
				type: "audio",
				id: "track_mystic",
				title: "Ark of Memory 02",
				duration: 89,
				filename: "Album08/ArkofMemory_02.mp3",
				lyrics: [{ time: 0, text: "Ark of Memory 02" }],
			},
			{
				type: "audio",
				id: "track_endoffarewell_01",
				title: "이별의 끝 (MR) 01",
				duration: 89,
				filename: "Album08/EndofFarewell_01.mp3",
				lyrics: [{ time: 0, text: "이별의 끝 (MR) 01" }],
			},
			{
				type: "audio",
				id: "track_endoffarewell_02",
				title: "이별의 끝 (MR) 02",
				duration: 89,
				filename: "Album08/EndofFarewell_02.mp3",
				lyrics: [{ time: 0, text: "이별의 끝 (MR) 02" }],
			},
			{
				type: "audio",
				id: "track_grayclouds",
				title: "Gray Clouds (MR)",
				duration: 89,
				filename: "Album08/GrayClouds.mp3",
				lyrics: [{ time: 0, text: "Gray Clouds (MR)" }],
			},
			{
				type: "audio",
				id: "track_farfaitlove_01",
				title: "사랑은 파르페처럼 (MR) 01",
				duration: 89,
				filename: "Album08/ParfaitLOVE_01.mp3",
				lyrics: [{ time: 0, text: "사랑은 파르페처럼 (MR) 01" }],
			},
			{
				type: "audio",
				id: "track_farfaitlove_02",
				title: "사랑은 파르페처럼 (MR) 02",
				duration: 89,
				filename: "Album08/ParfaitLOVE_02.mp3",
				lyrics: [{ time: 0, text: "사랑은 파르페처럼 (MR) 02" }],
			},
		],
	},
	{
		id: "album09",
		title: "@WORLD_Ev24", // 우주에서 온 황금
		author: "LastOrigin",
		image: "album09",
		songs: [
			{
				type: "audio",
				id: "track_out_of_control",
				title: "Out Of Control",
				duration: 136,
				filename: "Album09/Out_Of_Control.mp3",
				lyrics: [{ time: 0, text: "Out Of Control" }],
			},
			{
				type: "audio",
				id: "track_uneager",
				title: "Uneager",
				duration: 119,
				filename: "Album09/Uneager.mp3",
				lyrics: [{ time: 0, text: "Uneager" }],
			},
			{
				type: "audio",
				id: "track_dreamagain",
				title: "Dream Again",
				duration: 129,
				filename: "Album09/DreamAgain.mp3",
				lyrics: [{ time: 0, text: "Dream Again" }],
			},
		],
	},
	{
		id: "album10",
		title: "@WORLD_Ev25", // 제로 베이스
		author: "LastOrigin",
		image: "album10",
		songs: [
			{
				type: "audio",
				id: "track_medical_sound",
				title: "Medical Sound",
				duration: 30,
				filename: "Album10/Medical_Sound.mp3",
				lyrics: [{ time: 0, text: "Medical Sound" }],
			},
			{
				type: "audio",
				id: "track_medical_stop",
				title: "Medical Stop",
				duration: 8,
				filename: "Album10/Medical_Stop.mp3",
				lyrics: [{ time: 0, text: "Medical Stop" }],
			},
			{
				type: "audio",
				id: "track_horror2",
				title: "Horror2",
				duration: 138,
				filename: "Album10/Horror2.mp3",
				lyrics: [{ time: 0, text: "Horror2" }],
			},
		],
	},

	{
		id: "album_missorca_1st",
		title: "MISS ORCA 1st season",
		author: "뽀끄루 대마왕",
		image: "album_missorca_1st",
		songs: [
			{
				type: "youtube",
				id: "track1",
				title: "New Page",
				duration: 262,
				url: "Hh2cWKGjGO8",
				lyrics: [
					{ time: 0, text: "New Page - 뽀끄루 대마왕" },
					{ time: 0, text: "" },
					{ time: 0.01, text: "여기에서 노래할게" },
					{ time: 2.87, text: "하나뿐인 목소리로" },
					{ time: 7.87, text: "" },
					{ time: 18.46, text: "오래 전 어딘가에서 들려왔던" },
					{ time: 23.93, text: "노래에 두근거렸던 걸 기억해" },
					{ time: 29.46, text: "그 날의 그 순간부터 지금까지" },
					{ time: 35.16, text: "혼자서 매일매일 그려왔어" },
					{ time: 40.71, text: "나, 지쳐 쓰러지고 싶은" },
					{ time: 45.31, text: "날이 찾아올 때마다" },
					{ time: 48.23, text: "무대 위의 내 모습을 상상해 다시" },
					{ time: 52.54, text: "몇 번이고 다시" },
					{ time: 54.34, text: "일어날 수 있도록" },
					{ time: 56.61, text: "두근대는 이 마음이" },
					{ time: 59.41, text: "날 부르고 있잖아" },
					{ time: 62.73, text: "여기에서 노래할게" },
					{ time: 65.69, text: "단 하나뿐인 목소리로" },
					{ time: 68.46, text: "지금 이 세상으로" },
					{ time: 70.38, text: "울려 퍼지는 멜로디" },
					{ time: 73.89, text: "여기에서 약속할게" },
					{ time: 76.86, text: "나는 절대 멈추지 않아" },
					{ time: 79.26, text: "그러니 써 내려가자" },
					{ time: 81.96, text: "나만을 위한" },
					{ time: 84.4, text: "New Page를" },
					{ time: 89.4, text: "" },
					{ time: 98.02, text: "이 꿈이 멀리에 있는 것만 같아" },
					{ time: 103.46, text: "가끔은 힘든 순간도 있었지만" },
					{ time: 109.07, text: "아직은 누구에게도 하지 못한" },
					{ time: 114.71, text: "숨겨온 마음이 여기에 있어" },
					{ time: 120.3, text: "나, 주저앉고 싶어지는" },
					{ time: 124.98, text: "순간이 찾아올 때도" },
					{ time: 127.79, text: "눈부시게 빛날 나를 떠올리면서" },
					{ time: 132.07, text: "몇 번이고 다시" },
					{ time: 133.88, text: "일어날 수 있다고" },
					{ time: 136.15, text: "지금까지 그려왔던" },
					{ time: 138.99, text: "꿈이 곁에 있잖아" },
					{ time: 142.26, text: "여기에서 노래할게" },
					{ time: 145.27, text: "단 하나뿐인 목소리로" },
					{ time: 148.03, text: "지금 이 세상으로" },
					{ time: 149.95, text: "울려 퍼지는 멜로디" },
					{ time: 153.46, text: "여기에서 약속할게" },
					{ time: 156.38, text: "이제 내 맘 속이지 않아 그러니" },
					{ time: 160.09, text: "이제부터 나 열어볼 거야" },
					{ time: 163.73, text: "새로운 페이지를" },
					{ time: 168.73, text: "" },
					{ time: 187.27, text: "알았어, 사실 난 알았어" },
					{ time: 192.32, text: "멀리에 있어도" },
					{ time: 194.8, text: "선명하게 느껴" },
					{ time: 196.17, text: "분명 이 마음이" },
					{ time: 197.98, text: "나를, 다시 일어나게 하지" },
					{ time: 200.89, text: "꿈을, 계속 이어가게 하지" },
					{ time: 204.04, text: "날 비출 내일이 기다리고 있잖아" },
					{ time: 209.27, text: "나를 위해 노래할게" },
					{ time: 212.19, text: "하나뿐인 목소리로" },
					{ time: 216.18, text: "여기에서 노래할게" },
					{ time: 219.21, text: "단 하나뿐인 목소리로" },
					{ time: 221.97, text: "지금 이 세상으로" },
					{ time: 223.88, text: "울려 퍼지는 멜로디" },
					{ time: 227.39, text: "여기에서 노래할게" },
					{ time: 230.35, text: "하나뿐인 목소리로" },
					{ time: 232.41, text: "지금 여기 불러내는" },
					{ time: 235.12, text: "나의 이야기를" },
					{ time: 238.56, text: "새로 써 내려가는" },
					{ time: 240.95, text: "나를 위한, New Page를" }
				],
			},
		],
	},
	{
		id: "album_projectorca_kr",
		title: "Project ORCA",
		author: "스카이나이츠 & 뮤즈",
		image: "album_projectorca",
		songs: [
			{
				type: "youtube",
				id: "track1",
				title: "Lover Lover",
				duration: 201,
				url: "WVm7nZ9wz3M",
				lyrics: [
					{ time: 0, text: "Lover Lover - 스카이나이츠" },
					{ time: 0, text: "" },
					{ time: 0.13, text: "Oh oh oh oh oh 나나나나" },
					{ time: 3.21, text: "Oh oh oh oh oh 나나나나" },
					{ time: 7.08, text: "저 하늘 끝까지 갈게" },
					{ time: 10.17, text: "빛나는 이 길을 따라" },
					{ time: 14.05, text: "One Two Spotlight" },
					{ time: 18, text: "" },
					{ time: 36.22, text: "어쩜 이렇게 반짝일까" },
					{ time: 40.1, text: "저기 구름도 멈춰볼걸" },
					{ time: 43.21, text: "그래 반짝반짝이는" },
					{ time: 48, text: "우리를 봐줄래" },
					{ time: 50.19, text: "무대 위의 린티는 어때" },
					{ time: 54.09, text: "자꾸자꾸만 보고 싶지 (인정)" },
					{ time: 57.19, text: "빛날거야" },
					{ time: 60.21, text: "또 반짝 반짝 반짝" },
					{ time: 62.14, text: "또 두근 두근 두근" },
					{ time: 64.08, text: "함께 춤출거야 (예 예 예)" },
					{ time: 68.02, text: "Lover Lover Lover" },
					{ time: 69.13, text: "저 하늘 넘어 높이" },
					{ time: 71.18, text: "날아갈게 그대를 따라서" },
					{ time: 75.04, text: "끝없이 펼쳐진 하늘 위로" },
					{ time: 78.15, text: "Oh oh oh oh oh 날아갈게 (예 예)" },
					{ time: 82.04, text: "Lover Lover 밤하늘 별처럼" },
					{ time: 86.22, text: "날 향해 비춰줘" },
					{ time: 89.02, text: "당신과 함께 해피엔딩을" },
					{ time: 92.15, text: "Oh oh oh oh oh 나나" },
					{ time: 96, text: "Oh oh oh oh oh 예" },
					{ time: 100, text: "" },
					{ time: 102.14, text: "마법소녀 모모처럼 상큼하게" },
					{ time: 109.12, text: "그댈 위해 웃을거야" },
					{ time: 113.05, text: "계속 지켜봐 줄래요" },
					{ time: 116.21, text: "무대 위의 린티는 어때" },
					{ time: 120.09, text: "자꾸 자꾸만 보고 싶지 (인정)" },
					{ time: 123.21, text: "빛날거야" },
					{ time: 126.21, text: "또 반짝 반짝 반짝" },
					{ time: 128.15, text: "또 두근 두근 두근" },
					{ time: 130.1, text: "함께 춤출거야 (예 예 예)" },
					{ time: 134.06, text: "Lover Lover Lover" },
					{ time: 135.16, text: "저 하늘 넘어 높이" },
					{ time: 137.19, text: "날아갈게 그대를 따라서" },
					{ time: 141.04, text: "끝없이 펼쳐진 하늘 위로" },
					{ time: 144.17, text: "Oh oh oh oh oh 날아갈게 (예 예)" },
					{ time: 148.05, text: "Lover Lover 밤하늘 별처럼" },
					{ time: 152.24, text: "날 향해 비춰줘" },
					{ time: 155.04, text: "당신과 함께 해피엔딩을" },
					{ time: 158.16, text: "꿈 꿀꺼니까" },
					{ time: 162.04, text: "Lover Lover 약속해 줄래요" },
					{ time: 165.15, text: "Lover Lover 함께해 주기를" },
					{ time: 169.04, text: "이 세상을 우리의 색으로" },
					{ time: 172.12, text: "채울 테니까 (예 예)" },
					{ time: 176.01, text: "Lover Lover 저 하늘 넘어 높이" },
					{ time: 179.12, text: "날아갈게 그대를 따라서" },
					{ time: 183, text: "끝없이 펼쳐진 하늘 위로" },
					{ time: 186.11, text: "Oh oh oh oh oh 예 예" },
					{ time: 189.22, text: "Oh oh oh oh oh 예" },
					{ time: 195.83, text: "(스카이나이츠)" },
					{ time: 198, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track2",
				title: "두근☆두근 반짝★반짝",
				duration: 227,
				url: "1aTx4aofCbg",
				lyrics: [
					{ time: 0, text: "두근☆두근 반짝★반짝 - 민트초코쉐이크" },
					{ time: 1, text: "" },
					{ time: 2.09, text: "이건 내 비밀 이야기" },
					{ time: 4.21, text: "잘 들어줄래 Yo Boy" },
					{ time: 8.11, text: "Listen my first secret story (들어봐)" },
					{ time: 12.11, text: "들어줄래 우리의 얘기" },
					{ time: 15.04, text: "그대와 나 사이의 얘기" },
					{ time: 17.22, text: "좋아 좋아 시작해볼까" },
					{ time: 20.06, text: "우리의 첫 걸음" },
					{ time: 25.12, text: "(예)" },
					{ time: 26.08, text: "그래 그대 그대는 내게" },
					{ time: 28.21, text: "챙기고픈 유일한 사랑" },
					{ time: 31.14, text: "그래 그대는 내게" },
					{ time: 34.06, text: "빛나 빛나는 태양" },
					{ time: 37, text: "단순하고 아주 가끔은" },
					{ time: 39.19, text: "철이 없어 보이긴해도" },
					{ time: 42.11, text: "Love Love 사랑스러워" },
					{ time: 45.03, text: "Love Love 사랑스러워" },
					{ time: 47.2, text: "우 그대는 내 마음을 눈치챈걸까" },
					{ time: 52.22, text: "오 이런 내 마음을 들켜버릴 것 같은데" },
					{ time: 58.07, text: "꾸 꾸 꾸 꿈을 꿨죠" },
					{ time: 60.21, text: "그 그 그 그대가 내게" },
					{ time: 63.14, text: "바 바 바 반했다고" },
					{ time: 66.08, text: "고백하는 그런 꿈을" },
					{ time: 69.02, text: "꼭 꼭 꼭 그럴거야" },
					{ time: 71.18, text: "Love Love Love 그대는 내게" },
					{ time: 74.13, text: "Fall in love Love me babe" },
					{ time: 77.06, text: "Love me babe Love me babe" },
					{ time: 81.03, text: "" },
					{ time: 91.03, text: "결심했어 보여줄거야" },
					{ time: 93.23, text: "반짝반짝 귀여운 모습" },
					{ time: 96.17, text: "첫번째는 그대를 향해" },
					{ time: 99.06, text: "아이컨택트 (예)" },
					{ time: 101.94, text: "두번째는 자연스럽게" },
					{ time: 104.19, text: "옷깃 위에 먼지를 털기" },
					{ time: 107.14, text: "세번째는 실수를 한 척" },
					{ time: 109.63, text: "안기는거야 어때" },
					{ time: 112.15, text: "우 그대는 내 마음을 눈치챈걸까" },
					{ time: 117.72, text: "오 이런 내 마음을 들켜버릴 것 같은데" },
					{ time: 123.05, text: "꾸 꾸 꾸 꿈을 꿨죠" },
					{ time: 125.54, text: "그 그 그 그대가 내게" },
					{ time: 128.48, text: "바 바 바 반했다고" },
					{ time: 131.1, text: "고백하는 그런 꿈을" },
					{ time: 134.05, text: "꼭 꼭 꼭 그럴거야" },
					{ time: 136.21, text: "Love Love Love 그대는 내게" },
					{ time: 139.16, text: "Fall in love Love me babe" },
					{ time: 142.11, text: "Love me babe Love me babe" },
					{ time: 145, text: "머리부터 발끝까지 꽃 향기로 뿜뿜" },
					{ time: 147.39, text: "내 마음도 봄봄 사랑인거야 boy" },
					{ time: 150.14, text: "솔직히 대답해 줄래요" },
					{ time: 153.08, text: "그대에게 맞는 그런 내가 맞나요" },
					{ time: 156.37, text: "그댄 나를 어떻게 생각해" },
					{ time: 159, text: "(빙빙 돌지 말고 솔직하게 말해줘)" },
					{ time: 161.19, text: "그댄 내게 정말 소중한데" },
					{ time: 166.2, text: "오 그대에게 이런 내 마음을 말할래" },
					{ time: 172, text: "오 그대에게 나의 속마음을 꼭 말할거야" },
					{ time: 177.11, text: "꾸 꾸 꾸 꿈을 꿨죠" },
					{ time: 180.04, text: "그 그 그 그대가 내게" },
					{ time: 182.22, text: "바 바 바 반했다고" },
					{ time: 185.15, text: "고백하는 그런 꿈을" },
					{ time: 188.09, text: "꼭 꼭 꼭 그럴거야" },
					{ time: 191.04, text: "Love Love Love 그대는 내게" },
					{ time: 193.61, text: "Fall in love Love me babe" },
					{ time: 196.13, text: "Love me babe Love me babe" },
					{ time: 199.36, text: "그댄 나를 어떻게 생각해" },
					{ time: 202.28, text: "(빙빙 돌지 말고 솔직하게 말해줘)" },
					{ time: 205.02, text: "그댄 내게 정말 소중한데" },
					{ time: 210.08, text: "나 좋아하니까" },
					{ time: 214.08, text: "좋아하니까" },
					{ time: 216.24, text: "이런 내게 반해줄래요" },
					{ time: 222, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track3",
				title: "외로운 별의 노래",
				duration: 261,
				url: "gCpaVcP_QA0",
				lyrics: [
					{ time: 0, text: "외로운 별의 노래 - Blooming Heart" },
					{ time: 8, text: "" },
					{ time: 11.01, text: "올려다본 저 밤하늘 늘 반짝이던 별무리" },
					{ time: 16.02, text: "멀기만 하던 저 별이 내 곁에 내려왔죠" },
					{ time: 21.05, text: "외톨이인 나에게 따뜻한 손을 내밀어" },
					{ time: 26.09, text: "준 너의 온기를 느껴 You're my Shining Star" },
					{ time: 32.01, text: "우리들의 마음 속 가장 아름다운 별이 되어" },
					{ time: 37.05, text: "비춰주는 그대에게" },
					{ time: 40.13, text: "그대에게 전하는 별들의 노래" },
					{ time: 46.11, text: "저 은하수 너머 밝게 비추는 네 품에 안겨" },
					{ time: 51.06, text: "차갑고 어두운 밤 외롭게 빛나는" },
					{ time: 56.08, text: "상냥한 그대의 곁을 지켜줄게" },
					{ time: 60.18, text: "별빛처럼 빛나는 사랑의 노래" },
					{ time: 66.2, text: "강한 척 눈웃음 짓는 그대를 감싸안고서" },
					{ time: 71.07, text: "까만 밤을 밝게 비추는 별자리가 되어" },
					{ time: 77.02, text: "샛별처럼 빛나는 너의 곁에 있을게" },
					{ time: 92.1, text: "밝아오지 않는 밤엔 네 목소리를 들려줘" },
					{ time: 97.2, text: "어둠 속에서 길을 헤매일 땐 내 손을 잡아" },
					{ time: 102.22, text: "둘만의 하늘 아래 에서라면 두렵지 않아" },
					{ time: 108.01, text: "내가 너를 비춰줄게 I'm your Shining Star" },
					{ time: 113.16, text: "우리 둘의 마음 속 가장 아름다운 별이 되어" },
					{ time: 118.21, text: "비춰주는 그대에게" },
					{ time: 122.02, text: "그대에게 전하는 별들의 노래" },
					{ time: 128.02, text: "저 은하수 너머 밝게 비추는 네 품에 안겨" },
					{ time: 132.23, text: "차갑고 어두운 밤 외롭게 빛나는" },
					{ time: 138.02, text: "상냥한 그대의 곁을 지켜줄게" },
					{ time: 142.13, text: "별빛처럼 빛나는 사랑의 노래" },
					{ time: 148.14, text: "강한 척 눈웃음 짓는 그대를 감싸안고서" },
					{ time: 153, text: "까만 밤을 밝게 비추는 별자리가 되어" },
					{ time: 159.02, text: "샛별처럼 빛나는 너의 곁에 있을게" },
					{ time: 184.16, text: "영원의 끝에서 날 비추는 Your Starlight" },
					{ time: 189.17, text: "그 빛만을 따라서 저 하늘 저 너머까지" },
					{ time: 194.21, text: "약속의 혜성처럼 그대를 향해" },
					{ time: 199.23, text: "까만 밤을 날아서" },
					{ time: 203.18, text: "그대에게 전하는 사랑의 노래" },
					{ time: 210.02, text: "하늘 높이 날아 너에게 안기고 싶어" },
					{ time: 214.15, text: "별이 빛나는 밤 나만을 비추는" },
					{ time: 219.19, text: "외로운 나를 안아준 그대에게" },
					{ time: 225.03, text: "하루하루 커져만 가는 내 마음 햇살처럼 따뜻해져" },
					{ time: 230.09, text: "자꾸자꾸 커져만 가는 이 말" },
					{ time: 232.86, text: "너를 사랑해" },
					{ time: 234.15, text: "이 세상에 가장 눈부신 별빛이 되어서" },
					{ time: 240.19, text: "영원처럼 빛나는 수호성이 돼 줄게" },
					{ time: 249, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track4",
				title: "그대는 나에게",
				duration: 247,
				url: "WNx0wMHZY5I",
				lyrics: [
					{ time: 0, text: "그대는 나에게 - 뮤즈" },
					{ time: 16, text: "" },
					{ time: 19.2, text: "어두운 내 방엔 작은 빛이 있죠" },
					{ time: 28.09, text: "그건 모니터 속 무대" },
					{ time: 34.24, text: "그댈 보면서 덧없이 꿈꿨죠" },
					{ time: 43.12, text: "내가 노래하는 모습을" },
					{ time: 50.03, text: "언제나 나에게 두 손을 내밀어 준 널" },
					{ time: 58.2, text: "위해서 용기내보려 해" },
					{ time: 64.11, text: "들어 줄래요 조금은 어색해도" },
					{ time: 72.17, text: "마음을 전하는 내 노랠 들어줄래" },
					{ time: 79.2, text: "그대는 나의 나의 별빛이니까" },
					{ time: 87.24, text: "내 마음 가득히 담아 노래 할게요 꼭" },
					{ time: 116.24, text: "지난 날 기억 다 지워 버릴거야" },
					{ time: 125.12, text: "모두를 위해서 노래 할거야" },
					{ time: 131.04, text: "내 맘 담아서 너만을 위한 노래 부를테니까" },
					{ time: 142.17, text: "들어 줄래요 조금은 어색해도" },
					{ time: 150.21, text: "두렵지 않아 난 이제는 달라졌어" },
					{ time: 157.19, text: "그대는 나의 나의 별빛이니까" },
					{ time: 167.09, text: "내 마음 속 빛나는 별" },
					{ time: 177.12, text: "캄캄한 내 맘 밝게 비춰준 널" },
					{ time: 185.1, text: "안고 싶어" },
					{ time: 191, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track5",
				title: "With You",
				duration: 270,
				url: "WSkk61cBSTM",
				lyrics: [
					{ time: 0, text: "With You - 스카이나이츠 & 뮤즈" },
					{ time: 0, text: "" },
					{ time: 0.5, text: "빛나는 꿈과 함께" },
					{ time: 2.22, text: "화려한 스테이지 위로" },
					{ time: 6.1, text: "채워가는 우리의 Story" },
					{ time: 9.1, text: "이제 시작해 With you" },
					{ time: 15, text: "" },
					{ time: 23.03, text: "밤하늘 고개 들어 바라봐" },
					{ time: 28.16, text: "내 모습 비춰주는 빛 (너라는 별빛)" },
					{ time: 34.02, text: "저 구름 사이 속에 감춰져 흐려져도" },
					{ time: 39.13, text: "언제까지나 함께 있을 거라고 해줘" },
					{ time: 45.03, text: "희미했던 내 캔버스 위에" },
					{ time: 48.01, text: "하나둘씩 그려지는 네 마음" },
					{ time: 50.2, text: "그건 마치 무지개빛 사랑" },
					{ time: 56.01, text: "반짝반짝 그 온기를 따라" },
					{ time: 59, text: "채워지는 나의 팔레트로" },
					{ time: 61.13, text: "너와 내가 함께 만드는 미래 그리자" },
					{ time: 66.07, text: "I sing you 널 위한 노래" },
					{ time: 68.18, text: "저 멀리 울려 퍼지면" },
					{ time: 72.07, text: "하늘 너머 내 목소리가" },
					{ time: 75.06, text: "너에게 닿을까" },
					{ time: 77.06, text: "빛나는 꿈과 함께" },
					{ time: 79.17, text: "모두의 사랑을 담아" },
					{ time: 83.05, text: "채워가는 우리의 Story" },
					{ time: 86.06, text: "지금 이곳에 With you" },
					{ time: 92, text: "" },
					{ time: 99.21, text: "내 가슴속에 잠든 소망은" },
					{ time: 105.11, text: "이 작은 노랫소리로 (커져 가는걸)" },
					{ time: 110.21, text: "뜻대로 되지 않아 다가올 불안함도" },
					{ time: 116.09, text: "우리가 함께라면 이겨나갈 수 있어" },
					{ time: 121.2, text: "힘이 나는 네 주문 앞에서" },
					{ time: 124.2, text: "사라지는 망설임과 두려움" },
					{ time: 127.15, text: "그건 마치 마법 같은 사랑" },
					{ time: 132.2, text: "네가 그린 동화 같은 미래로" },
					{ time: 135.2, text: "눈부시는 날개 힘껏 펼쳐" },
					{ time: 138.09, text: "함께 가자 좀 더 밝은 저 빛을 향해서" },
					{ time: 143.02, text: "I sing you 널 위한 노래" },
					{ time: 145.13, text: "저 멀리 울려 퍼지면" },
					{ time: 149, text: "하늘 너머 내 목소리가" },
					{ time: 152.02, text: "너에게 닿을까" },
					{ time: 154.02, text: "빛나는 꿈과 함께" },
					{ time: 156.12, text: "모두의 사랑을 담아" },
					{ time: 159.24, text: "채워가는 우리의 Story" },
					{ time: 162.24, text: "지금 이곳에 With you" },
					{ time: 168, text: "" },
					{ time: 187.08, text: "어떤 사람들에겐" },
					{ time: 190.16, text: "힘없고 하찮은" },
					{ time: 193.11, text: "사랑 노래처럼 들리겠지만" },
					{ time: 198.16, text: "너와 나의 소중한 추억들" },
					{ time: 201.15, text: "퍼즐처럼 하나 된 멜로디" },
					{ time: 204.04, text: "이 노래를 저 우주 끝까지 들리게 외칠게" },
					{ time: 214.06, text: "I sing you 널 위한 노래" },
					{ time: 216.21, text: "저 멀리 울려펴지면" },
					{ time: 220.08, text: "하늘 너머 내 목소리가" },
					{ time: 223.09, text: "너에게 닿을까" },
					{ time: 225.09, text: "빛나는 꿈과 함께" },
					{ time: 227.2, text: "모두의 사랑을 담아" },
					{ time: 231.07, text: "채워가는 우리의 Story" },
					{ time: 234.09, text: "영원히 함께 With you" },
					{ time: 241.21, text: "For you" },
					{ time: 244, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track6",
				title: "잠시",
				duration: 295,
				url: "FJHuhO77YWU",
				lyrics: [
					{ time: 0, text: "잠시 - 뮤즈" },
					{ time: 0, text: "" },
					{ time: 1, text: "사실은 아직도 잘 모르는 길처럼 헤매이고 있어" },
					{ time: 16, text: "여전히 나에게는 해야만 한 것들을 짊어진 채 서있어" },
					{ time: 30, text: "" },
					{ time: 32, text: "가끔은 서러운 마음에 부딪쳐서" },
					{ time: 41, text: "아픈 기억들이 눈앞에 다가오면" },
					{ time: 51.5, text: "알 수 없는 현실이 내게 상처를 주곤해" },
					{ time: 62.5, text: "" },
					{ time: 63.5, text: "떨어지는 소나기에 오랜 시간 버텨왔던" },
					{ time: 70.5, text: "내 눈물로 물들어가 나를 지켜주던 " },
					{ time: 78.5, text: "너의 모습마저 희미해져" },
					{ time: 83.5, text: "그럴 땐 눈을 감아 슬픈 기억 속에서" },
					{ time: 94, text: "잠시 쉬어도 돼" },
					{ time: 102, text: "" },
					{ time: 128, text: "차가운 바람이 찾아오는 슬픔에 문득 혼자 있어" },
					{ time: 143, text: "한없이 외로운 걸 너무나 잘 알아서" },
					{ time: 153.5, text: "무너지는 어느 날" },
					{ time: 158.5, text: "" },
					{ time: 160, text: "떨어지는 소나기에 오랜 시간 버텨왔던" },
					{ time: 167, text: "내 눈물로 물들어가 나를 지켜주던" },
					{ time: 175.5, text: "너의 모습마저 희미해져" },
					{ time: 180, text: "그럴 땐 눈을 감아 슬픈 기억 속에서" },
					{ time: 189, text: "잠시 넘어질 듯이 힘겹게 내딛어" },
					{ time: 198, text: "한 걸음 한 걸음 그대로 나아가" },
					{ time: 205, text: "" },
					{ time: 206.5, text: "더 이상은 주저하지마" },
					{ time: 211, text: "고여버린 마음 위에 돌아가도" },
					{ time: 218, text: "놓치지는 않아" },
					{ time: 220.5, text: "" },
					{ time: 222, text: "행복했던 추억 바라보며" },
					{ time: 227, text: "그대로 눈을 감아" },
					{ time: 233, text: "모든 바램속에서" },
					{ time: 239, text: "멈춰 잠시" },
					{ time: 245, text: "" },
				],
			},
		],
	},
	{
		id: "album_missorca_2nd",
		title: "MISS ORCA 2nd season",
		author: "B-11 나이트앤젤 & 멸망의 메이 & 천향의 히루메",
		image: "album_missorca_2nd",
		songs: [
			{
				type: "youtube",
				id: "track1",
				title: "호접지몽",
				duration: 348,
				url: "ffSWaF-byGw",
				lyrics: [
					{ time: 0, text: "호접지몽 - 천향의 히루메" },
					{ time: 19.6, text: "" },
					{ time: 22.43, text: "달님이 계신 하얀 언덕 너머에" },
					{ time: 28.26, text: "파란빛을 비추며 춤을 추었네" },
					{ time: 33.74, text: "나래짓 하며 길을 그린 자리엔" },
					{ time: 39.47, text: "그대의 흔적만 남았네" },
					{ time: 44.83, text: "다래꽃 송아리 열린 가람길 따라" },
					{ time: 50.46, text: "펼쳐진 꽃구름 아래서" },
					{ time: 56.09, text: "소첩을 감싸 안아준 그대 손길이" },
					{ time: 61.95, text: "이제는 아스라하구나" },
					{ time: 67.23, text: "" },
					{ time: 70.57, text: "한 번 더 날 안아주거라" },
					{ time: 76.18, text: "온 세상 빛나던 날처럼" },
					{ time: 81.87, text: "꽃바람에 흩날리는 작은 나래로" },
					{ time: 87.43, text: "그대를 나 맞이하노라" },
					{ time: 93.07, text: "희 여울 가람을 넘어서" },
					{ time: 98.73, text: "오색 빛 다남 길 지난 곳" },
					{ time: 104.37, text: "살사리꽃 인사하는 하얀 언덕에" },
					{ time: 110.06, text: "도닐며 나 기다릴 테니" },
					{ time: 115.47, text: "피워 내는 꽃망울처럼" },
					{ time: 121.17, text: "" },
					{ time: 143.88, text: "여우비 내려 보슬거린 소리에" },
					{ time: 149.58, text: "눈뜨면 쌓인 추억이 흘러갈때면" },
					{ time: 155.26, text: "서투른 그대 눈물 같아 보여서" },
					{ time: 160.91, text: "소첩도 마음이 아리네" },
					{ time: 166.34, text: "한아름 따다 엮은 꽃 타래처럼" },
					{ time: 172.11, text: "해맑던 그대의 모습을" },
					{ time: 177.55, text: "함초롬히 마음속에 담아뒀지만" },
					{ time: 183.49, text: "점점 더 아득해지노라" },
					{ time: 192.1, text: "다시 한번 웃어주거라" },
					{ time: 197.67, text: "미리내 꽃피던 날에는" },
					{ time: 203.14, text: "달무리 속 꼬리별이 손짓하듯이" },
					{ time: 208.89, text: "그리며 나 바라볼테니" },
					{ time: 214.48, text: "희 여울 가람을 넘어서" },
					{ time: 220.22, text: "오색 빛 다남 길 있던 곳" },
					{ time: 225.95, text: "도라지 꽃 피어나는 푸른 언덕에" },
					{ time: 231.57, text: "올라서 나 서약하노라" },
					{ time: 237.05, text: "그대와 나 이제 영원히" },
					{ time: 243.15, text: "" },
					{ time: 269.41, text: "돋을볕이 비추는 시에" },
					{ time: 275.18, text: "오색 빛 다남 길 지난 곳" },
					{ time: 280.86, text: "살사리꽃 인사하던 하얀 언덕에" },
					{ time: 286.71, text: "또 다시 나 돌아왔노라" },
					{ time: 292.2, text: "물 비늘 목소리 따라서" },
					{ time: 297.6, text: "저 멀리 그대가 보이네" },
					{ time: 303.3, text: "여전히 날 향해 누그럽게 웃노니" },
					{ time: 309.1, text: "이제는 떠나지 않으리" },
					{ time: 314.59, text: "영원히 그대의 품속에" },
					{ time: 320.33, text: "" },
					{ time: 337.38, text: "영원히 그대 꿈 속에" },
					{ time: 343.17, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track2",
				title: "MY LOVE",
				duration: 238,
				url: "x__gIBqOU28",
				lyrics: [
					{ time: 0, text: "My Love - 멸망의 메이" },
					{ time: 9.22, text: "" },
					{ time: 13.39, text: "유난히 빛난 너의 웃는 모습" },
					{ time: 20.66, text: "내겐 처음 느끼는 감정에" },
					{ time: 27.36, text: "창가에 비친 햇살처럼 따스한" },
					{ time: 34.32, text: "내 마음 너에게 어떻게 전할까" },
					{ time: 41.12, text: "파란 하늘에 너를 떠올려보고" },
					{ time: 45.39, text: "그 옆에는 나를 그려보는 걸" },
					{ time: 48.91, text: "하얀 구름 사이 속에 들어가" },
					{ time: 52.6, text: "우리만의 세상을 만들어" },
					{ time: 55.85, text: "너와 마주치는 그 순간들이" },
					{ time: 59.44, text: "내게는 너무나도 떨리는 걸" },
					{ time: 62.99, text: "아직 조금 서툰 나의 마음을" },
					{ time: 66.62, text: "언제쯤 너에게 고백할까" },
					{ time: 70.01, text: "My Love" },
					{ time: 76.23, text: "" },
					{ time: 98.07, text: "어느새 나는 널 바라만 봐도" },
					{ time: 104.75, text: "어쩜 이리도 설레이는지" },
					{ time: 111.84, text: "소중한 추억 하나둘 쌓여가는" },
					{ time: 119.25, text: "이 마음 너에게 표현해도 될까" },
					{ time: 125.78, text: "나도 모르게 웃음이 새어 나와" },
					{ time: 130.07, text: "커져 버린 마음이 자꾸만 날" },
					{ time: 133.56, text: "하루 온 종일 네 생각뿐인걸" },
					{ time: 137.43, text: "이제는 네게 말해도 될까" },
					{ time: 140.63, text: "바보처럼 망설이다 지나간" },
					{ time: 144.22, text: "긴긴 하루의 저녁 노을빛이" },
					{ time: 147.7, text: "어서 너에게 말을 건네라며" },
					{ time: 151.34, text: "환하게 나를 비춰주네" },
					{ time: 154.68, text: "My Love" },
					{ time: 156.21, text: "너도 날 같은 마음일까" },
					{ time: 161.61, text: "오직 너 하나뿐인 사랑" },
					{ time: 166.95, text: "My Love" },
					{ time: 170.26, text: "널 생각할 때마다 보고 싶은걸" },
					{ time: 174.14, text: "커져 버린 마음에 용기 내어" },
					{ time: 177.75, text: "하루 온종일 네 생각뿐인걸" },
					{ time: 181.38, text: "이제는 네게 말하고 싶어" },
					{ time: 184.64, text: "항상 너와 나 함께 있을 때면" },
					{ time: 188.2, text: "모든 세상을 다 가진 것 같아" },
					{ time: 191.84, text: "눈을 감아도 너만 보이는 걸" },
					{ time: 195.59, text: "살며시 너에게 다가갈게" },
					{ time: 199, text: "My Love" },
					{ time: 202.15, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track3",
				title: "FLIGHT AGAIN",
				duration: 262,
				url: "al2KUW6Tt80",
				lyrics: [
					{ time: 0, text: "FLIGHT AGAIN - B-11 나이트앤젤" },
					{ time: 0.83, text: "" },
					{ time: 1.35, text: "끝없는 어둠이 펼쳐져도" },
					{ time: 6.16, text: "힘에 한계는 없어" },
					{ time: 8.91, text: "이 출력은 OVER DRIVE" },
					{ time: 14.28, text: "" },
					{ time: 24.77, text: "바람이 잠드는 새벽에" },
					{ time: 29.03, text: "수많은 이들이 구원을 외치네" },
					{ time: 35.86, text: "희망을 갈구하던 불씨는" },
					{ time: 39.58, text: "빛을 서서히 잃어가지만" },
					{ time: 42.49, text: "시간은 기다리지 않네" },
					{ time: 46.11, text: "검게 물든 신념과 지쳐 버린 마음은" },
					{ time: 51.28, text: "제트 불길 속에 태워버리고" },
					{ time: 56.98, text: "이제 창공을 향해" },
					{ time: 59.92, text: "철의 날개 펼치며" },
					{ time: 62.2, text: "최고로 풀 스로틀" },
					{ time: 65.55, text: "끝없는 비상" },
					{ time: 67.74, text: "끓어오르는 열정으로" },
					{ time: 71.36, text: "타오르는 해처럼 빛처럼 박차 나아가" },
					{ time: 76.67, text: "성층권을 넘어 피워내는 붉은 불꽃은" },
					{ time: 82.36, text: "단 하나뿐인 무한한 의지" },
					{ time: 86.52, text: "이정표의 끝까지 Fly Away" },
					{ time: 93.93, text: "" },
					{ time: 96.55, text: "노을에 그을린 비행운" },
					{ time: 101.28, text: "은빛 바다 위를 뒤따라 바라봐" },
					{ time: 107.72, text: "타오르는 마음 품에 안고" },
					{ time: 111.89, text: "이글거리는 결의의 눈빛" },
					{ time: 114.44, text: "기세로는 절대 지지 않아" },
					{ time: 118.18, text: "반복되는 쟁명은 악몽 같은 신기루" },
					{ time: 123.31, text: "제트 엔진 속에 부숴 버리고" },
					{ time: 128.76, text: "지평선 끝을 향해" },
					{ time: 131.89, text: "활주로를 달리며" },
					{ time: 134.23, text: "전력으로 Take Off" },
					{ time: 137.71, text: "끝없는 비상" },
					{ time: 140.09, text: "넘쳐흐르는 에너지로" },
					{ time: 143.51, text: "타오르는 해처럼 빛처럼 박차 나아가" },
					{ time: 149.04, text: "빨라지는 고동 슈퍼노바처럼 눈부신" },
					{ time: 154.34, text: "단 하나뿐인 확고한 맹세" },
					{ time: 158.81, text: "하늘 끝에 맺히는 Burning Star" },
					{ time: 168.11, text: "" },
					{ time: 184.62, text: "간절한 소망과 절망 속에서" },
					{ time: 189.51, text: "유성처럼 사라지는 마지막 그날까지" },
					{ time: 195.71, text: "잠긴 열쇠를 부숴" },
					{ time: 198.17, text: "초월한 속력으로 소리쳐라 소닉붐" },
					{ time: 204.23, text: "고요한 새벽 가끔 길 잃어 헤매지만" },
					{ time: 210.15, text: "다시 한번 일어서 털어내 계속 나아가" },
					{ time: 215.55, text: "어릴 적의 꿈이 멈춰버린 풍경이라면" },
					{ time: 221.27, text: "더 늦기 전에 Fly to the Sky" },
					{ time: 225.39, text: "더 높은 비상" },
					{ time: 227.74, text: "저 먼빛의 궤적을 따라서" },
					{ time: 232.98, text: "강하고 굳세게 박차 나아가" },
					{ time: 236.53, text: "깊은 어둠 뒤에 종말의 불꽃이 피어도" },
					{ time: 242.63, text: "멈추지 않는 염원의 서약" },
					{ time: 246.84, text: "이뤄지는 날까지 FLIGHT AGAIN" },
					{ time: 254.93, text: "" }

				],
			},
		],
	},
	{
		id: "album_cafe_amor",
		title: "CAFE amor",
		author: "로열 아스널 & 해체자 아자즈 & CS 페로 & 호라이즌",
		image: "album_cafeamor",
		songs: [
			{
				type: "youtube",
				id: "track1",
				title: "GO UP",
				duration: 197,
				url: "Fph1MIh8JKU",
				lyrics: [
					{ time: 0, text: "GO UP - CAFE amor" },
					{ time: 0, text: "" },
					{ time: 8.2, text: "반짝이는 별" },
					{ time: 10.24, text: "저 우주 너머에 너의 소원을" },
					{ time: 13.21, text: "이루어 줄게 나에게 말해" },
					{ time: 16.12, text: "간절했던 꿈" },
					{ time: 18, text: "너의 마음속에 바라는 것을" },
					{ time: 21.02, text: "반드시 현실로 나타나" },
					{ time: 23.93, text: "이제부터 시작된 Game 주문을 걸어봐" },
					{ time: 28.78, text: "나만이 알 수 있는 주문으로" },
					{ time: 32.26, text: "눈 부신 미래의 널" },
					{ time: 34.19, text: "원하는 곳에 내가" },
					{ time: 36.2, text: "데려다 줄게 어디든" },
					{ time: 38.88, text: "" },
					{ time: 39.13, text: "GO UP 하늘 위로 GO UP 높이 올라" },
					{ time: 43.34, text: "GO UP 자유로운 바람에 너를 맡겨봐" },
					{ time: 47.09, text: "하얀 구름 따라 수평선 너머로" },
					{ time: 51.22, text: "Fly high 지금부터는 모든 게 바뀔거야" },
					{ time: 61.43, text: "I want to change" },
					{ time: 67.27, text: "원하는 대로 뭐든 해낼테니까" },
					{ time: 70.98, text: "" },
					{ time: 71.23, text: "Oh 네가 원하는 세상의 바램을" },
					{ time: 75.15, text: "하나부터 열까지 It will come true" },
					{ time: 79.1, text: "내 눈앞에 다가와 펼쳐지는 신기루" },
					{ time: 82.92, text: "Close your eyes and open them" },
					{ time: 85.69, text: "" },
					{ time: 85.87, text: "이제부터 시작된 Game 주문을 걸어봐" },
					{ time: 90.74, text: "우리 둘만이 아는 Secret" },
					{ time: 94.7, text: "눈 부신 태양 아래" },
					{ time: 96.66, text: "원하는 곳에 우리" },
					{ time: 98.62, text: "데려다줄게 어디든" },
					{ time: 101.7, text: "" },
					{ time: 101.94, text: "GO UP 하늘 위로 GO UP 높이 올라" },
					{ time: 105.81, text: "GO UP 자유로운 바람에 너를 맡겨봐" },
					{ time: 109.71, text: "하얀 구름 따라 수평선 너머로" },
					{ time: 113.65, text: "Fly high 지금부터는 모든 게 바뀔거야" },
					{ time: 123.92, text: "I want to change" },
					{ time: 129.67, text: "마음이 가는 대로 해낼테니까" },
					{ time: 133.48, text: "" },
					{ time: 133.7, text: "너의 소원을 하나의 빛에 담아" },
					{ time: 138.07, text: "작고 소중한 우리 둘의 시간들" },
					{ time: 141.56, text: "영원히 잊혀지지 않을 추억을 모아" },
					{ time: 145.38, text: "간절히 바랄 게 I want to change" },
					{ time: 150.38, text: "" },
					{ time: 164.26, text: "GO UP 하늘 위로 GO UP 높이 올라" },
					{ time: 168.23, text: "GO UP 자유로운 바람에 너를 맡겨봐" },
					{ time: 172.21, text: "하얀 구름 따라 수평선 너머로" },
					{ time: 176.05, text: "Fly high 지금부터는 모든 게 바뀔거야" },
					{ time: 186.25, text: "너의 마음대로 change" },
					{ time: 190.05, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track2",
				title: "이별의 끝",
				duration: 234,
				url: "mnunOkzpWuc",
				lyrics: [
					{ time: 0, text: "이별의 끝 - 해체자 아자즈" },
					{ time: 0, text: "" },
					{ time: 17.44, text: "가시 박힌 말들로" },
					{ time: 23.11, text: "서로에게 상처를 주고" },
					{ time: 31.48, text: "마음에도 없는 말들이" },
					{ time: 37.42, text: "자꾸만 나도 모르게 흘러" },
					{ time: 43.3, text: "" },
					{ time: 44.6, text: "우리 이대로 멀어진다면" },
					{ time: 51.93, text: "다가오는 이별의 끝에서" },
					{ time: 59.5, text: "너에게 건네는 마지막 인사를" },
					{ time: 66.58, text: "행복했던 우리의 모습에 no" },
					{ time: 73.86, text: "이젠 너에게 전화를 걸지는 못해도" },
					{ time: 80.93, text: "사랑했던 시간들 남겨주면 돼" },
					{ time: 88.31, text: "우리" },
					{ time: 91.4, text: "" },
					{ time: 92.23, text: "인연이 아닐지도" },
					{ time: 97.6, text: "모르는 생각에 잠겨" },
					{ time: 104.97, text: "기나긴 침묵 속에 남아" },
					{ time: 112.26, text: "또다시 눈물이 흘러" },
					{ time: 118, text: "" },
					{ time: 119.06, text: "우린 이대로 멀어진다면" },
					{ time: 126.5, text: "다가오는 이별의 끝에서" },
					{ time: 134.09, text: "너에게 건네는 마지막 인사를" },
					{ time: 141.2, text: "행복했던 우리의 모습에 no" },
					{ time: 148.58, text: "이젠 너에게 전화를 걸지는 못해도" },
					{ time: 155.39, text: "사랑했던 시간들 남겨주면 돼" },
					{ time: 162.8, text: "우리" },
					{ time: 166, text: "" },
					{ time: 166.76, text: "차가운 바람에 에어질 듯이 아파와" },
					{ time: 174.23, text: "시간이 해결해주지 못했던 만큼" },
					{ time: 180.97, text: "가슴 아픈 추억만" },
					{ time: 183.76, text: "계속 난 떠올라" },
					{ time: 189.98, text: "" },
					{ time: 192.59, text: "너에겐 진심을 다했던 것처럼" },
					{ time: 199.44, text: "나의 마음속 깊은 곳까지 널 no" },
					{ time: 206.72, text: "이젠 다시는 너를 볼 수 없을지라도" },
					{ time: 213.86, text: "행복했던 시간들 간직해주면 돼" },
					{ time: 221.11, text: "안녕" },
					{ time: 224.31, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track3",
				title: "Gray Clouds",
				duration: 251,
				url: "6cBLGWYG_Iw",
				lyrics: [
					{ time: 0, text: "Gray Clouds - 로열 아스널" },
					{ time: 0, text: "" },
					{ time: 12.12, text: "문득 내려 본 창문 틈 사이엔" },
					{ time: 17.36, text: "떨어진 빗방울 하나둘 번지고" },
					{ time: 23.56, text: "잠든 새벽엔 고요히 내려앉은" },
					{ time: 28.88, text: "하얀 먼지 위로 어둠을 감싸네" },
					{ time: 35.47, text: "입김을 불어 넣어 나만의 흔적을" },
					{ time: 40.58, text: "상상했었던 걸 지금 느낀 그대로" },
					{ time: 47.03, text: "조금만 더 나아가 내가 걸어왔던 street" },
					{ time: 52.35, text: "가로등 불빛 아래 텅 빈 그리움만 남아" },
					{ time: 58, text: "" },
					{ time: 58.57, text: "Always. I have so many" },
					{ time: 61.48, text: "the things to do. Does it?" },
					{ time: 63.74, text: "맘이 답답해 한숨만 내어 쉬어" },
					{ time: 70.36, text: "어떤 게 정답인지 넌 해답을 알고 있지" },
					{ time: 76.19, text: "Gray clouds Oh Gray clouds" },
					{ time: 79.84, text: "You know that answer, right?" },
					{ time: 84, text: "" },
					{ time: 85.14, text: "회색빛 하늘에 구름은" },
					{ time: 90.26, text: "내 맘을 적시고 어느새 내 앞에 멈춰" },
					{ time: 96.53, text: "비가 내리는 날에 차오르는 눈물 위로" },
					{ time: 102.8, text: "지나온 순간의 번지는 그리움" },
					{ time: 108.52, text: "나의 마음속에 점점 더 선명한" },
					{ time: 114.03, text: "아름다웠었던 추억에 잠시 잠겨" },
					{ time: 120.3, text: "조금씩 깊어져 간 나만의 계절은" },
					{ time: 125.67, text: "가로등 불빛 아래 텅 빈 외로움만 남아" },
					{ time: 131.68, text: "" },
					{ time: 131.93, text: "Always. I have so many" },
					{ time: 134.68, text: "the things to do. Does it?" },
					{ time: 137.03, text: "맘이 답답해 한숨만 내어 쉬어" },
					{ time: 143.44, text: "어떤 게 정답인지 넌 해답을 알고 있지" },
					{ time: 149.1, text: "Gray clouds Oh Gray clouds" },
					{ time: 153.2, text: "You know that answer, right?" },
					{ time: 155.8, text: "" },
					{ time: 155.97, text: "온 세상이 어둠에 잠드는 밤" },
					{ time: 160.84, text: "밝게 비추는 저 별이 내게 말을 해줘" },
					{ time: 167.17, text: "스쳐 지나간 구름 그 속에서" },
					{ time: 172.39, text: "나만의 별빛을 따라 Gray clouds" },
					{ time: 178.39, text: "" },
					{ time: 181.6, text: "Always. I have so many" },
					{ time: 184.47, text: "the things to do. Does it?" },
					{ time: 186.75, text: "맘이 답답해 한숨만 내어 쉬어" },
					{ time: 193.23, text: "어떤 게 정답인지 넌 해답을 알고 있지" },
					{ time: 199.08, text: "Gray clouds Oh Gray clouds" },
					{ time: 204.8, text: "" },
					{ time: 205.04, text: "쓸쓸한 기억 속에 벗어난 날 만나" },
					{ time: 209.79, text: "I find one light 한순간의 my dream" },
					{ time: 216.7, text: "어떤 선택이라도 내게는 하나뿐인" },
					{ time: 221.56, text: "Gray clouds Oh Gray clouds" },
					{ time: 226.83, text: "I know that answer, right" },
					{ time: 231.13, text: "" },
					{ time: 237.43, text: "Gray clouds" },
					{ time: 245, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track4",
				title: "사랑은 파르페처럼",
				duration: 241,
				url: "B4M-c_n2Fic",
				lyrics: [
					{ time: 0, text: "사랑은 파르페처럼 - CS 페로" },
					{ time: 0, text: "" },
					{ time: 0.82, text: "오래 동안 간직했던" },
					{ time: 4.2, text: "My Secret Recipe" },
					{ time: 6.54, text: "이제는 다 보여 줄게" },
					{ time: 8.91, text: "이 마음 담아서 사랑은 파르페처럼" },
					{ time: 15.06, text: "" },
					{ time: 24.48, text: "햇살이 가득 내린 아침" },
					{ time: 27.08, text: "오늘은 어떤 일이 일어날까" },
					{ time: 30.62, text: "설레는 마음으로 조금 빠르게" },
					{ time: 33.58, text: "리듬을 바꿔 웃으며 노래해" },
					{ time: 36.84, text: "바람의 부드러움 안고" },
					{ time: 39.01, text: "초콜릿 컬러 길을 걷다 보면" },
					{ time: 42.5, text: "수많은 구름들이 가득" },
					{ time: 45.02, text: "새하얀 슈크림 빵처럼 춤추네" },
					{ time: 48.61, text: "핑크 빛 스프링클 한가득" },
					{ time: 51.41, text: "와글와글 소리치는 팝핑캔디" },
					{ time: 54.51, text: "아이스크림 듬뿍 내 마음" },
					{ time: 57.55, text: "All For you" },
					{ time: 60.16, text: "" },
					{ time: 60.56, text: "오래 동안 간직했던" },
					{ time: 64.21, text: "My Secret Recipe" },
					{ time: 66.48, text: "널 위해 다 준비했어" },
					{ time: 69.21, text: "두 손 가득히 I'm ready for you." },
					{ time: 72.54, text: "네 모습 떠올릴 때면" },
					{ time: 76.24, text: "나는 두근두근" },
					{ time: 78.49, text: "조금 더 널 보고 싶어" },
					{ time: 81.27, text: "이 마음 담아서 사랑은 파르페처럼" },
					{ time: 87.47, text: "" },
					{ time: 96.83, text: "벚꽃이 흩날리는 저녁" },
					{ time: 99.09, text: "노을에 내 눈빛은 반짝반짝" },
					{ time: 102.8, text: "시나몬 향기 같은 이 밤거리를" },
					{ time: 105.73, text: "달콤하게 한 스푼에 채울래" },
					{ time: 108.67, text: "수줍게 구워지는 달빛" },
					{ time: 111.17, text: "쿠키를 바사삭 깨물어보면" },
					{ time: 114.74, text: "입 안에 퍼져 가는 너와" },
					{ time: 117.07, text: "나만의 특별한 감정이 느껴져" },
					{ time: 120.57, text: "오렌지 마시멜로 한 가득" },
					{ time: 123.47, text: "샤르르르 녹아내린 휘핑크림" },
					{ time: 126.8, text: "카페모카 같은 이 기분" },
					{ time: 129.49, text: "All For You" },
					{ time: 132.43, text: "I Love You" },
					{ time: 135, text: "" },
					{ time: 135.82, text: "오래 동안 간직했던" },
					{ time: 139.06, text: "My Secret Recipe" },
					{ time: 141.75, text: "널 위해 다 준비했어" },
					{ time: 144.44, text: "두 손 가득히 I'm ready for you" },
					{ time: 147.74, text: "네 목소리 들을 때면" },
					{ time: 151.24, text: "나는 두근두근" },
					{ time: 153.85, text: "조금 더 날 사랑해줘" },
					{ time: 156.03, text: "이 마음 담아서 사랑은 파르페처럼" },
					{ time: 162.67, text: "" },
					{ time: 186.53, text: "한번 맛보면 또 다시" },
					{ time: 190.21, text: "생각 나는 Recipe" },
					{ time: 192.61, text: "우리의 소중한 시간" },
					{ time: 195.26, text: "추억 가득히 I'll Remember you" },
					{ time: 199.1, text: "내 마음을 받아줄까" },
					{ time: 202.17, text: "나는 두근두근" },
					{ time: 204.51, text: "조금 더 널 사랑할게" },
					{ time: 206.94, text: "이 마음 담아서 사랑은 파르페처럼" },
					{ time: 213.66, text: "" },
					{ time: 215.73, text: "Long Forever" },
					{ time: 220, text: "" },
				],
			},
			{
				type: "placeholder",
				id: "track5",
				title: "어서오세요 라스트 파라다이스 (CAFE Horizon)",
				duration: 217,
				image: "album_cafeamor_cafehorizon",
				headers: [
					{
						text: `
							<span class="me-1" style="color:var(--bgm-color-yellow) !important">AG-2C 세이렌</span>
							<span class="me-1" style="color:var(--bgm-color-orange) !important">AG-1 네레이드</span>
							<span class="me-1" style="color:var(--bgm-color-purple) !important">P-3M 운디네</span>
							<span style="color:var(--bgm-color-pink) !important">MH-4 테티스</span>
						`,
						raw: true,
					},
				],
				lyrics: [
					{ time: 0, text: "어서오세요 라스트 파라다이스 - CAFE Horizon" },
					{ time: 0, text: "" },
					{ time: 0.01, text: "One, Two, Three, Four", color: "yellow" },
					{ time: 3.03, text: "" },
					{ time: 11.4, text: "달콤한 로망이 모이는 곳", color: "yellow" },
					{ time: 16.3, text: "낙원에 어서 오세요", color: "yellow" },
					{ time: 21.2, text: "어제도", color: "orange" },
					{ time: 22.3, text: "오늘도", color: "purple" },
					{ time: 23.4, text: "내일도", color: "pink" },
					{ time: 25.76, text: "시작된 Shiny Smile Again" },
					{ time: 30.36, text: "" },
					{ time: 30.84, text: "처음 느꼈던 설레임", color: "purple" },
					{ time: 35.53, text: "마음 한가득 채우고", color: "orange" },
					{ time: 39.98, text: "두근두근 반짝반짝 빛나는", color: "purple" },
					{ time: 42.12, text: "러버러버 사랑이 피어올라", color: "yellow" },
					{ time: 44.8, text: "다시 Jump!", color: "orange" },
					{ time: 45.87, text: "함께 달리자", color: "pink" },
					{ time: 48.46, text: "" },
					{ time: 49, text: "하나되어 부르는 빛의 하모니" },
					{ time: 54, text: "지난 추억은", color: "orange" },
					{ time: 55.3, text: "별이 되어", color: "purple" },
					{ time: 56.66, text: "은하수 길을 비추네" },
					{ time: 58.94, text: "매 순간이 새로운 시작", color: "yellow" },
					{ time: 63.34, text: "잊지 못할 라스트", color: "pink" },
					{ time: 65.36, text: "파라다이스" },
					{ time: 67.54, text: "" },
					{ time: 79.41, text: "조금씩 빛을 잃은 일상에", color: "orange" },
					{ time: 83.91, text: "지치고 힘이 들 때면", color: "orange" },
					{ time: 88.73, text: "언제든", color: "purple" },
					{ time: 89.91, text: "어디서든", color: "pink" },
					{ time: 91.09, text: "우리와", color: "yellow" },
					{ time: 93.59, text: "함께 해 Happy Pleasure Time", color: ["yellow", "purple", "pink"] },
					{ time: 97.5, text: "" },
					{ time: 97.9, text: "작게 내디딘 소망은", color: "yellow" },
					{ time: 103, text: "밝은 미소로 전해져", color: "pink" },
					{ time: 107.7, text: "빛나는 별의 노래를 부르며", color: "purple" },
					{ time: 110.1, text: "그대는 나에게 점점 다가와", color: "yellow" },
					{ time: 112.63, text: "잠시 Stay! 영원히", color: "orange" },
					{ time: 114.58, text: "WITH YOU" },
					{ time: 118.89, text: "" },
					{ time: 119.26, text: "하나되어 부르는 빛의 하모니" },
					{ time: 124.07, text: "지난 추억은", color: "yellow" },
					{ time: 125.49, text: "별이 되어", color: "purple" },
					{ time: 126.63, text: "은하수 길을 비추네" },
					{ time: 129.18, text: "수 놓여진 함께한 순간", color: "purple" },
					{ time: 133.34, text: "잊지 못할 라스트", color: "yellow" },
					{ time: 135.56, text: "파라다이스" },
					{ time: 137.54, text: "" },
					{ time: 137.97, text: "구름을 가르고", color: "pink" },
					{ time: 140.7, text: "하늘 높이 춤추던", color: "purple" },
					{ time: 142.76, text: "나비의 꿈처럼", color: "yellow" },
					{ time: 145.56, text: "자유롭게 FLIGHT AGAIN", color: "orange" },
					{ time: 148.17, text: "따스한", color: ["yellow", "purple"] },
					{ time: 149.15, text: "노을을", color: ["orange", "pink"] },
					{ time: 150.63, text: "품에 안고" },
					{ time: 154.88, text: "이 감정 기억해 My Love" },
					{ time: 160.71, text: "" },
					{ time: 178.81, text: "그대와 함께 새겨둔 Memory", color: "purple" },
					{ time: 183.23, text: "시간 흘러도 한결같이" },
					{ time: 186.11, text: "변하지 않는 Melody" },
					{ time: 188.53, text: "이 노래는 끝나지 않아", color: "purple" },
					{ time: 192.98, text: "우리의 시작은", color: "yellow" },
					{ time: 195.34, text: "언제나 이곳에", color: "orange" },
					{ time: 197.78, text: "어서오세요 라스트", color: "pink" },
					{ time: 200.96, text: "파라다이스" },
					{ time: 204.3, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track6",
				title: "어서오세요, 라스트 파라다이스 (CAFE amor x CAFE Horizon)",
				duration: 217,
				url: "_lGpNSYn53I",
				image: "album_cafeamor_cafehorizon",
				headers: [
					{
						text: `
							<span class="me-1" style="color:var(--bgm-color-yellow) !important">AG-2C 세이렌</span>
							<span class="me-1" style="color:var(--bgm-color-orange) !important">AG-1 네레이드</span>
							<span class="me-1" style="color:var(--bgm-color-purple) !important">P-3M 운디네</span>
							<span class="me-1" style="color:var(--bgm-color-pink) !important">MH-4 테티스</span>
							<span class="me-1" style="color:var(--bgm-color-green) !important">로열 아스널</span>
							<span class="me-1" style="color:var(--bgm-color-blue) !important">해체자 아자즈</span>
							<span style="color:var(--bgm-color-red) !important">CS 페로</span>
						`,
						raw: true,
					},

				],
				lyrics: [
					{ time: 0, text: "어서오세요, 라스트 파라다이스 - CAFE amor x CAFE Horizon" },
					{ time: 0, text: "" },
					{ time: 0.01, text: "One, Two, Three, Four", color: "yellow" },
					{ time: 3.03, text: "" },
					{ time: 11.4, text: "달콤한 로망이 모이는 곳", color: "yellow" },
					{ time: 16.3, text: "낙원에 어서 오세요", color: "yellow" },
					{ time: 21.2, text: "어제도", color: "green" },
					{ time: 22.3, text: "오늘도", color: "blue" },
					{ time: 23.4, text: "내일도", color: "red" },
					{ time: 25.76, text: "시작된 Shiny Smile Again", color: ["green", "blue", "red"] },
					{ time: 30.36, text: "" },
					{ time: 30.84, text: "처음 느꼈던 설레임", color: "purple" },
					{ time: 35.53, text: "마음 한가득 채우고", color: "orange" },
					{ time: 39.98, text: "두근두근 반짝반짝 빛나는", color: "red" },
					{ time: 42.12, text: "러버러버 사랑이 피어올라", color: "yellow" },
					{ time: 44.8, text: "다시 Jump!", color: "blue" },
					{ time: 45.87, text: "함께 달리자", color: "pink" },
					{ time: 48.46, text: "" },
					{ time: 49, text: "하나되어 부르는 빛의 하모니" },
					{ time: 54, text: "지난 추억은", color: "orange" },
					{ time: 55.3, text: "별이 되어", color: "purple" },
					{ time: 56.66, text: "은하수 길을 비추네" },
					{ time: 58.94, text: "매 순간이 새로운 시작", color: "green" },
					{ time: 63.34, text: "잊지 못할 라스트", color: "pink" },
					{ time: 65.36, text: "파라다이스" },
					{ time: 67.54, text: "" },
					{ time: 79.41, text: "조금씩 빛을 잃은 일상에", color: "blue" },
					{ time: 83.91, text: "지치고 힘이 들 때면", color: "blue" },
					{ time: 88.73, text: "언제든", color: "purple" },
					{ time: 89.91, text: "어디서든", color: "pink" },
					{ time: 91.09, text: "우리와", color: "yellow" },
					{ time: 93.59, text: "함께 해 Happy Pleasure Time", color: ["yellow", "purple", "pink", "blue"] },
					{ time: 97.5, text: "" },
					{ time: 97.9, text: "작게 내디딘 소망은", color: "green" },
					{ time: 103, text: "밝은 미소로 전해져", color: "red" },
					{ time: 107.7, text: "빛나는 별의 노래를 부르며", color: "purple" },
					{ time: 110.1, text: "그대는 나에게 점점 다가와", color: "blue" },
					{ time: 112.63, text: "잠시 Stay!", color: "pink" },
					{ time: 113.96, text: "영원히", color: "orange" },
					{ time: 114.58, text: "WITH YOU" },
					{ time: 118.89, text: "" },
					{ time: 119.26, text: "하나되어 부르는 빛의 하모니" },
					{ time: 124.07, text: "지난 추억은", color: "blue" },
					{ time: 125.49, text: "별이 되어", color: "green" },
					{ time: 126.63, text: "은하수 길을 비추네" },
					{ time: 129.18, text: "수 놓여진 함께한 순간", color: "orange" },
					{ time: 133.34, text: "잊지 못할 라스트", color: "purple" },
					{ time: 135.56, text: "파라다이스" },
					{ time: 137.54, text: "" },
					{ time: 137.97, text: "구름을 가르고", color: "green" },
					{ time: 140.7, text: "하늘 높이 춤추던", color: "yellow" },
					{ time: 142.76, text: "나비의 꿈처럼", color: "pink" },
					{ time: 145.56, text: "자유롭게 FLIGHT AGAIN", color: "red" },
					{ time: 148.17, text: "따스한", color: "orange" },
					{ time: 149.15, text: "노을을", color: "blue" },
					{ time: 150.63, text: "품에 안고", color: "purple" },
					{ time: 154.88, text: "이 감정 기억해 My Love" },
					{ time: 160.71, text: "" },
					{ time: 178.81, text: "그대와 함께 새겨둔 Memory", color: "green" },
					{ time: 183.23, text: "시간 흘러도 한결같이" },
					{ time: 186.11, text: "변하지 않는 Melody" },
					{ time: 188.53, text: "이 노래는 끝나지 않아", color: "pink" },
					{ time: 192.98, text: "우리의 시작은", color: ["green", "blue", "red"] },
					{ time: 195.34, text: "언제나 이곳에", color: ["yellow", "orange", "purple", "pink"] },
					{ time: 197.78, text: "어서오세요 라스트", color: "red" },
					{ time: 200.96, text: "파라다이스" },
					{ time: 204.3, text: "" },
				],
			},
		],
	},
	{
		id: "album_missorca_3rd",
		title: "MISS ORCA 3rd season",
		author: "이터니티 & 블랙 리리스 & 사멸의 세크메트",
		image: "album_missorca_3rd",
		songs: [
			{
				type: "youtube",
				id: "track1",
				title: "북극성",
				duration: 283,
				url: "S1Nv3KTNO-s",
				lyrics: [
					{ time: 0, text: "북극성 - 이터니티" },
					{ time: 0, text: "" },
					{ time: -1, text: "그대 손을 잡고 걸으면" },
					{ time: -1, text: "어디라도 갈 수 있을 것만 같았는데" },
					{ time: -1, text: "이제는 모두 지나간" },
					{ time: -1, text: "이야기가 되어버렸네요" },
					{ time: -1, text: "" },
					{ time: -1, text: "그대가 이 세상에 왔던 그 순간을" },
					{ time: -1, text: "처음부터 함께하진 못했지만 괜찮아요" },
					{ time: -1, text: "마지막은 내가 지킬 테니까" },
					{ time: -1, text: "" },
					{ time: -1, text: "이 세상이 그대를 멀리 데려간다면" },
					{ time: -1, text: "그대에게 꼭 하고 싶은 야기가 있죠" },
					{ time: -1, text: "언젠가 이 세상의 끝에서 영원의 끝이 오면" },
					{ time: -1, text: "내가 그대 곁에 있을 테니" },
					{ time: -1, text: "이제는 그대 눈을 감아요" },
					{ time: -1, text: "" },
					{ time: -1, text: "그대 눈을 바라볼 때면" },
					{ time: -1, text: "무엇이든 할 수 있을 것만 같았는데 이젠" },
					{ time: -1, text: "다 지나간 이야기가 되어버렸죠" },
					{ time: -1, text: "" },
					{ time: -1, text: "길을 잃어버리고 그대가 헤매게 된다면" },
					{ time: -1, text: "다시 한번 그대의 곁으로" },
					{ time: -1, text: "저 하늘의 별처럼" },
					{ time: -1, text: "언제 어디서라도 분명" },
					{ time: -1, text: "서로를 찾아낼 수 있어요" },
					{ time: -1, text: "" },
					{ time: -1, text: "이 세상이 내게서 그댈 데려간대도" },
					{ time: -1, text: "보이지 않는 곳에 멀리 그대를 숨겨도" },
					{ time: -1, text: "언제라도 그대를 찾아내 마지막 순간까지" },
					{ time: -1, text: "서로를 영원히 지킬 테니 그대는 부디 눈을 감아요" },
					{ time: -1, text: "" },
					{ time: -1, text: "따스한 그대의 마음을 알죠" },
					{ time: -1, text: "누구보다도 상냥한 강한 그 맘 알고 있죠" },
					{ time: -1, text: "눈부시게 빛이 나던 그대의 모습을" },
					{ time: -1, text: "영원히 나는 선명하게 기억해" },
					{ time: -1, text: "" },
					{ time: -1, text: "이 날이 온다는 걸 알고 있었는데도" },
					{ time: -1, text: "전할 수 없는 이 마음을 그대 아시나요" },
					{ time: -1, text: "" },
					{ time: -1, text: "돌아올 수 없는 이 길에서" },
					{ time: -1, text: "나 그대의 손을 잡고 영원히" },
					{ time: -1, text: "이렇게 머무를 테니까" },
					{ time: -1, text: "마지막은 그대 곁에 함께할 테니까" },
					{ time: -1, text: "그대는 두 눈을 감아요" },
					{ time: -1, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track2",
				title: "주인님 Overdose",
				duration: 187,
				url: "VWiC3twzVyA",
				lyrics: [
					{ time: 0, text: "주인님 Overdose - 블랙 리리스" },
					{ time: 0, text: "" },
					{ time: -1, text: "빠져들어가는" },
					{ time: -1, text: "날 멈출 수는 없어" },
					{ time: -1, text: "My heart is like a starlight" },
					{ time: -1, text: "My love is like a moonlight" },
					{ time: -1, text: "또 그댈 생각하는 그런 밤" },
					{ time: -1, text: "그댈 향한 이런 마음" },
					{ time: -1, text: "나 진짜 미친 것 같아" },
					{ time: -1, text: "이런 내 맘 아실까" },
					{ time: -1, text: "나홀로 상상의 끝엔" },
					{ time: -1, text: "시작된 overdose" },
					{ time: -1, text: "나 하나만은 아닐 테니까" },
					{ time: -1, text: "기다리고 싶지 않죠" },
					{ time: -1, text: "아직도 그대와" },
					{ time: -1, text: "가까워지고 싶어" },
					{ time: -1, text: "사실은 조금 더" },
					{ time: -1, text: "특별해지고 싶어" },
					{ time: -1, text: "내가 그대를 더 알게될 수록" },
					{ time: -1, text: "그대 마음도 내맘과" },
					{ time: -1, text: "같길 바라죠" },
					{ time: -1, text: "이런 맘 들키고 싶지 않지만" },
					{ time: -1, text: "말하지 않아도 나를 안아주세요" },
					{ time: -1, text: "이런내맘을" },
					{ time: -1, text: "알아주기를" },
					{ time: -1, text: "그대만큼은 안아주세요" },
					{ time: -1, text: "" },
					{ time: -1, text: "사실은 이미 느끼고 있지 True love" },
					{ time: -1, text: "뭔가 홀려 빠져버릴 것 같은 기분" },
					{ time: -1, text: "내 모든것을 바쳐" },
					{ time: -1, text: "당신을 향한 충성" },
					{ time: -1, text: "조금 더 손을 뻗어" },
					{ time: -1, text: "너의마음속에 gunshoot" },
					{ time: -1, text: "나 홀로 그대를" },
					{ time: -1, text: "가질 순" },
					{ time: -1, text: "없다는 걸" },
					{ time: -1, text: "알고는 있지만" },
					{ time: -1, text: "기다릴 순 없어요" },
					{ time: -1, text: "내가 그대에게 다가갈수록" },
					{ time: -1, text: "날 안아주길 바라도" },
					{ time: -1, text: "말할 순 없죠" },
					{ time: -1, text: "그댈 조금씩 더 알아갈수록" },
					{ time: -1, text: "커져가는 이런 맘을 알아주기를" },
					{ time: -1, text: "" },
					{ time: -1, text: "있는 그대로 모든 모습을" },
					{ time: -1, text: "사랑해주는 그대가 좋아" },
					{ time: -1, text: "그대 곁에 한 걸음 가까이" },
					{ time: -1, text: "다가갈래" },
					{ time: -1, text: "누구-에게라도 잠깐이라도" },
					{ time: -1, text: "진짜 사랑을 담아" },
					{ time: -1, text: "선물을 드릴게요" },
					{ time: -1, text: "사실 양보하고 싶지 않지만" },
					{ time: -1, text: "숨길수없는 Fanatic Love" },
					{ time: -1, text: "" },
					{ time: -1, text: "정말 가끔씩은 나쁜 아이가" },
					{ time: -1, text: "되고싶다 생각해도 말할 순 없죠" },
					{ time: -1, text: "이런 맘 들키고 싶지 않지만" },
					{ time: -1, text: "말하지 않아도 나를 안아주세요.그대꿈속에" },
					{ time: -1, text: "이런내마음" },
					{ time: -1, text: "알아주기를" },
					{ time: -1, text: "그대만큼은" },
					{ time: -1, text: "안아주세요" },
					{ time: -1, text: "" },
				],
			},
			{
				type: "youtube",
				id: "track3",
				title: "들려주고픈 이야기",
				duration: 275,
				url: "ABCuAo3-Co8",
				lyrics: [
					{ time: 0, text: "들려주고픈 이야기 - 사멸의 세크메트" },
					{ time: 0, text: "" },
					{ time: -1, text: "깊은 밤이 찾아와" },
					{ time: -1, text: "별들이 모두 잠들때면" },
					{ time: -1, text: "눈을 감고 들어봐" },
					{ time: -1, text: "오래전부터 준비했던" },
					{ time: -1, text: "이야기" },
					{ time: -1, text: "생명을 거두며" },
					{ time: -1, text: "알게된 것은" },
					{ time: -1, text: "운명이면 분명" },
					{ time: -1, text: "돌아올 테니" },
					{ time: -1, text: "지나간 일들은" },
					{ time: -1, text: "마음에 묻어버리고" },
					{ time: -1, text: "그대는 빛을 따라가면 돼" },
					{ time: -1, text: "그대 가는 길이 어두워" },
					{ time: -1, text: "헤매게 될 때" },
					{ time: -1, text: "진실이 그대를 이끌어 줄 거야" },
					{ time: -1, text: "세상이 꼭 그대를" },
					{ time: -1, text: "속이려 하는 것 같을 땐" },
					{ time: -1, text: "선명한 마음을 따라가" },
					{ time: -1, text: "내가 곁에 있으니" },
					{ time: -1, text: "더는 두려워 말아" },
					{ time: -1, text: "" },
					{ time: -1, text: "궂은 날을 지나서" },
					{ time: -1, text: "시간이 점점 흘러가고" },
					{ time: -1, text: "새벽 달이 비추면" },
					{ time: -1, text: "그대에게만 들려주는" },
					{ time: -1, text: "이야기" },
					{ time: -1, text: "보이는 모든 게" },
					{ time: -1, text: "전부가 아니듯" },
					{ time: -1, text: "언제나 기억해" },
					{ time: -1, text: "기쁨 슬픔까지" },
					{ time: -1, text: "지금 이 모든 게" },
					{ time: -1, text: "영원하진 않을 테니까" },
					{ time: -1, text: "그대는 계속 나아가면 돼" },
					{ time: -1, text: "그대 가는 길이 멀어서" },
					{ time: -1, text: "지치게 될 때" },
					{ time: -1, text: "사랑이 그대를 일으켜 줄 거야" },
					{ time: -1, text: "세상이 꼭 그대를" },
					{ time: -1, text: "막아서는 것만 같을 땐" },
					{ time: -1, text: "그대의 마음을 따라가" },
					{ time: -1, text: "내가 곁에 있으니" },
					{ time: -1, text: "더는 두려워 말아" },
					{ time: -1, text: "누구보다 강한 그대가 되기를" },
					{ time: -1, text: "그 누구보다 그대가" },
					{ time: -1, text: "행복하기를" },
					{ time: -1, text: "세상이 그대를 괴롭게 한다면" },
					{ time: -1, text: "아픔까지 모두 다" },
					{ time: -1, text: "끌어안아줄 수 있도록" },
					{ time: -1, text: "언제까지나 이렇게" },
					{ time: -1, text: "나의 품에 기대길" },
					{ time: -1, text: "기다리고 있으니" },
					{ time: -1, text: "내게 그대의 영원이란 순간이지만" },
					{ time: -1, text: "희망을 그려가고 있는 그대가" },
					{ time: -1, text: "언젠가 이 세상에" },
					{ time: -1, text: "혼자 남겨진 것 같을 땐" },
					{ time: -1, text: "그대의 곁에는 언제나" },
					{ time: -1, text: "내가 있을 테니까" },
					{ time: -1, text: "다시 나아가면 돼" },
					{ time: -1, text: "그대가" },
					{ time: -1, text: "행복해지기를" },
					{ time: -1, text: "" },
				],
			},
		],
	}
];
export default BGMAlbums;
