import { BGMAlbum } from "@/types/BGM";

const BGMAlbums: BGMAlbum[] = [
	{
		id: "album01",
		title: "LastOrigin Original Sound Track",
		author: "LastOrigin",
		image: "album01",
		songs: [],
	},
	{
		id: "album02",
		title: "지고의 저녁식사",
		author: "LastOrigin",
		image: "album02",
		songs: [],
	},
	{
		id: "album03",
		title: "리오보로스의 유산",
		author: "LastOrigin",
		image: "album03",
		songs: [],
	},
	{
		id: "album04",
		title: "만월의 야상곡",
		author: "LastOrigin",
		image: "album04",
		songs: [],
	},
	{
		id: "album05",
		title: "할로윈 파크 패닉!",
		author: "LastOrigin",
		image: "album05",
		songs: [],
	},
	{
		id: "album06",
		title: "세인트 오르카의 비밀작전",
		author: "LastOrigin",
		image: "album06",
		songs: [],
	},
	{
		id: "album_projectorca_kr",
		title: "Project ORCA",
		author: "스카이나이츠 & 뮤즈",
		image: "album_projectorca",
		songs: [
			{
				type: "youtube",
				id: "track1",
				title: "Lover Lover",
				duration: 201,
				url: "https://www.youtube.com/watch?v=WVm7nZ9wz3M",
			},
			{
				type: "youtube",
				id: "track2",
				title: "두근☆두근 반짝★반짝",
				duration: 227,
				url: "https://www.youtube.com/watch?v=1aTx4aofCbg",
			},
			{
				type: "youtube",
				id: "track3",
				title: "외로운 별의 노래",
				duration: 261,
				url: "https://www.youtube.com/watch?v=gCpaVcP_QA0",
			},
			{
				type: "youtube",
				id: "track4",
				title: "그대는 나에게",
				duration: 247,
				url: "https://www.youtube.com/watch?v=WNx0wMHZY5I",
			},
			{
				type: "youtube",
				id: "track5",
				title: "With You",
				duration: 270,
				url: "https://www.youtube.com/watch?v=WSkk61cBSTM",
			},
			{
				type: "youtube",
				id: "track6",
				title: "잠시",
				duration: 295,
				url: "https://www.youtube.com/watch?v=FJHuhO77YWU",
				lyrics: [
					{ time: 1, text: "사실은 아직도 잘 모르는 길처럼 헤매이고 있어" },
					{ time: 16, text: "여전히 나에게는 해야만 한 것들을 짊어진 채 서있어" },
					{ time: 30, text: "" },
					{ time: 32, text: "가끔은 서러운 마음에 부딪쳐서" },
					{ time: 41, text: "아픈 기억들이 눈앞에 다가오면" },
					{ time: 51.5, text: "알 수 없는 현실이 내게 상처를 주곤해" },
					{ time: 62.5, text: "" },
					{ time: 63.5, text: "떨어지는 소나기에 오랜 시간 버텨왔던" },
					{ time: 70.5, text: "내 눈물로 물들어가 나를 지켜주던 " },
					{ time: 78.5, text: "너의 모습마저 희미해져" },
					{ time: 83.5, text: "그럴 땐 눈을 감아 슬픈 기억 속에서" },
					{ time: 94, text: "잠시 쉬어도 돼" },
					{ time: 102, text: "" },
					{ time: 128, text: "차가운 바람이 찾아오는 슬픔에 문득 혼자 있어" },
					{ time: 143, text: "한없이 외로운 걸 너무나 잘 알아서" },
					{ time: 153.5, text: "무너지는 어느 날" },
					{ time: 158.5, text: "" },
					{ time: 160, text: "떨어지는 소나기에 오랜 시간 버텨왔던" },
					{ time: 167, text: "내 눈물로 물들어가 나를 지켜주던" },
					{ time: 175.5, text: "너의 모습마저 희미해져" },
					{ time: 180, text: "그럴 땐 눈을 감아 슬픈 기억 속에서" },
					{ time: 189, text: "잠시 넘어질 듯이 힘겹게 내딛어" },
					{ time: 198, text: "한 걸음 한 걸음 그대로 나아가" },
					{ time: 205, text: "" },
					{ time: 206.5, text: "더 이상은 주저하지마" },
					{ time: 211, text: "고여버린 마음 위에 돌아가도" },
					{ time: 218, text: "놓치지는 않아" },
					{ time: 220.5, text: "" },
					{ time: 222, text: "행복했던 추억 바라보며" },
					{ time: 227, text: "그대로 눈을 감아" },
					{ time: 233, text: "모든 바램속에서" },
					{ time: 239, text: "멈춰 잠시" },
				],
			},
		],
	},
];
export default BGMAlbums;
