export * from "./Const.1";

export const WorldIds: string[] = [
	"Story", "Sub", "Cha",
	"Ev1", "Ev2", "Ev3", "Ev4", "Ev5", "Ev6", "EvA0", "Ev7", "Ev8", "Ev9", "Ev10",
	"Ev11", "Ev12", "Ev13", "Ev14", "Ev15", "Ev16", "Ev17", "Ev18", "Ev19", "Ev20",
];
export const SubStoryUnit: Record<string, string> = {
	"S1-1": "AGS_Rampart",
	"S1-2": "3P_ConstantiaS2",
	"S2-1": "3P_Sowan",
	"S5-1": "DS_Faucre",
	"S6-1": "DS_Baekto",
	"S7-1": "3P_Fenrir",
	"S8-1": "PECS_Circe",
	"S9-1": "3P_Hachiko",
	"S10-1": "AGS_Rampart",
	"S11-1": "3P_Aurora",
	"S12-1": "3P_CSPerrault",
	"S13-1": "3P_BlackLilith",
	"S14-1": "BR_Brownie",
	"S15-1": "AGS_RheinRitter",
	"S15-2": "AGS_RheinRitter",
};

export const PermanentEvents: string[] = ["Ev1", "Ev2", "Ev3", "Ev4", "Ev5", "Ev6", "Ev7", "Ev8", "Ev9"];
export const NewMapList: string[] = [];
export const CurrentEvent = "Ev21";
export const EventFrom = new Date(2023, 9 - 1, 5);
export const EventTo = new Date(2023, 10 - 1, 4);

export const SkinBanners: string[] = [
	"3P_Ajax_1",
	"3P_Amphitrite_1",
	"3P_Aqua_1",
	"3P_Aurora_2", "3P_Aurora_3",
	"3P_BlackLilith_3",
	"3P_ConstantiaS2_3",
	"3P_CSPerrault_3",
	"3P_Eternity_3",
	"3P_Fenrir_2",
	"3P_Frigga_1",
	"3P_Hachiko_3",
	"3P_Hirume_2", "3P_Hirume_3",
	"3P_Maria_2",
	"3P_Melite_1",
	"3P_Ran_2",
	"3P_Salacia_1",
	"3P_ScissorsLise_3",
	"3P_Titania_3",
	"AGS_Arachne_1",
	"AGS_Tyrant_1",
	"BR_ALWraith_2",
	"BR_Andvari_3",
	"BR_AS12TurtleDragon_2",
	"BR_Bheur_2",
	"BR_Brunhild_1",
	"BR_Bulgasari_2",
	"BR_Cheona_1",
	"BR_Djinnia_1",
	"BR_Echidna_3",
	"BR_Ellie_1",
	"BR_Habetrot_1",
	"BR_HongRyun_3",
	"BR_Hraesvelgr_2",
	"BR_InvDragon_3",
	"BR_JangHwa_1", "BR_JangHwa_2",
	"BR_Khan_3",
	"BR_Kheshig_1",
	"BR_Leona_4",
	"BR_Marie_3",
	"BR_Nashorn_1",
	"BR_Phantom_1",
	"BR_Raven_1",
	"BR_RoyalArsenal_2",
	"BR_SandMan_2",
	"BR_Scarabya_1",
	"BR_StratoAngel_1", "BR_StratoAngel_2",
	"BR_Sylphid_1",
	"BR_TalonFeather_2",
	"BR_Valkyrie_4",
	"BR_Vargr_1", "BR_Vargr_2",
	"BR_WarWolf_2",
	"BR_Wraithy_2",
	"DS_Angel_1",
	"DS_Arman_2",
	"DS_Baekto_2",
	"DS_BunnySlayer_1",
	"DS_Charlotte_3",
	"DS_Faucre_3",
	"DS_Johanna_1",
	"DS_MoMo_3",
	"DS_Saraqael_2",
	"PECS_Azaz_2",
	"PECS_Babariana_2",
	"PECS_CyclopsePrincess_1", "PECS_CyclopsePrincess_2",
	"PECS_Empress_1",
	"PECS_Erato_1",
	"PECS_Machina_1",
	"PECS_Merlin_1",
	"PECS_Mery_1",
	"PECS_MightyR_1",
	"PECS_Mnemosyne_2",
	"PECS_Muse_2",
	"PECS_Olivia_1",
	"PECS_Orangeade_1",
	"PECS_QueenMane_2",
	"PECS_Rena_1",
	"PECS_Saetti_2",
	"PECS_Sekhmet_1",
	"PECS_Spartoia_1",
	"PECS_TaylorClothcut_1",
	"PECS_Tiequan_2",
	"ST_Mercury_1",
	"ST_Tiamat_2",
	"ST_Ullr_1",
	"BR_RoyalArsenal_3", "PECS_Sadius_2",
	"BR_Leprechaun_2", "PECS_Hathor_1",
	"PECS_LRL_4", "ST_Lancer_2",
	"BR_Neodym_3", "PECS_Hussar_2",
	"BR_BeastHunter_2",
];

export const SkillVideo: Record<string, number[]> = {
	DS_Koyori: [2],
};
