export const SkinBanners: string[] = [
	"3P_Ajax_1",
	"3P_Amphitrite_1",
	"3P_Aqua_1",
	"3P_Aurora_2", "3P_Aurora_3",
	"3P_BlackLilith_3",
	"3P_ConstantiaS2_3",
	"3P_CSPerrault_3",
	"3P_Eternity_3",
	"3P_Fenrir_2",
	"3P_Frigga_1",
	"3P_Hachiko_3",
	"3P_Hirume_2", "3P_Hirume_3",
	"3P_Maria_2",
	"3P_Melite_1",
	"3P_Ran_2",
	"3P_Salacia_1",
	"3P_ScissorsLise_3",
	"3P_Titania_3",
	"AGS_Arachne_1",
	"AGS_Tyrant_1",
	"BR_ALWraith_2",
	"BR_Andvari_3",
	"BR_AS12TurtleDragon_2",
	"BR_Bheur_2",
	"BR_Brunhild_1",
	"BR_Bulgasari_2",
	"BR_Cheona_1",
	"BR_Djinnia_1",
	"BR_Echidna_3",
	"BR_Ellie_1",
	"BR_Habetrot_1",
	"BR_HongRyun_3",
	"BR_Hraesvelgr_2",
	"BR_InvDragon_3",
	"BR_JangHwa_1", "BR_JangHwa_2",
	"BR_Khan_3",
	"BR_Kheshig_1",
	"BR_Leona_4",
	"BR_Marie_3",
	"BR_Nashorn_1",
	"BR_Phantom_1",
	"BR_Raven_1",
	"BR_RoyalArsenal_2",
	"BR_SandMan_2",
	"BR_Scarabya_1",
	"BR_StratoAngel_1", "BR_StratoAngel_2",
	"BR_Sylphid_1",
	"BR_TalonFeather_2",
	"BR_Valkyrie_4",
	"BR_Vargr_1", "BR_Vargr_2",
	"BR_WarWolf_2",
	"BR_Wraithy_2",
	"DS_Angel_1",
	"DS_Arman_2",
	"DS_Baekto_2",
	"DS_BunnySlayer_1",
	"DS_Charlotte_3",
	"DS_Faucre_3",
	"DS_Johanna_1",
	"DS_MoMo_3",
	"DS_Saraqael_2",
	"PECS_Azaz_2",
	"PECS_Babariana_2",
	"PECS_CyclopsePrincess_1", "PECS_CyclopsePrincess_2",
	"PECS_Empress_1",
	"PECS_Erato_1",
	"PECS_Machina_1",
	"PECS_Merlin_1",
	"PECS_Mery_1",
	"PECS_MightyR_1",
	"PECS_Mnemosyne_2",
	"PECS_Muse_2",
	"PECS_Olivia_1",
	"PECS_Orangeade_1",
	"PECS_QueenMane_2",
	"PECS_Rena_1",
	"PECS_Saetti_2",
	"PECS_Sekhmet_1",
	"PECS_Spartoia_1",
	"PECS_TaylorClothcut_1",
	"PECS_Tiequan_2",
	"ST_Mercury_1",
	"ST_Tiamat_2",
	"ST_Ullr_1",
	"BR_RoyalArsenal_3", "PECS_Sadius_2",
	"BR_Leprechaun_2", "PECS_Hathor_1",
	"PECS_LRL_4", "ST_Lancer_2",
	"BR_Neodym_3", "PECS_Hussar_2",
	"BR_BeastHunter_2",
	"PECS_Boryeon_2", "BR_Nymph_2",
	"3P_Galatea_2",
	"3P_Frigga_2",
	"PECS_Draculina_2", "PECS_Serpent_2",
	"PECS_BlindPrincess_1", "PECS_Ignis_2",
	"BR_HongRyun_4", "3P_Alice_3",
	"3P_Alcyone_1",
	"3P_Rhea_3",
];

export const SkillVideo: Record<string, number[]> = {
	DS_Koyori: [2],
};
