- key: TRStage_01_01
  chapter: Ch_TR01
  icon: BR_Miho_N
  sort: 0
- key: TRStage_01_02
  chapter: Ch_TR01
  icon: BR_AS12TurtleDragon_N
  sort: 1
- key: TRStage_01_03
  chapter: Ch_TR01
  icon: BR_Bulgasari_N
  sort: 2
- key: TRStage_01_04
  chapter: Ch_TR01
  icon: BR_PoniesAnger_N
  sort: 3
- key: TRStage_01_05
  chapter: Ch_TR01
  icon: BR_HongRyun_N
  sort: 4
- key: TRStage_01_06
  chapter: Ch_TR01
  icon: BR_HongRyun_N
  sort: 5
- key: TRStage_01_07
  chapter: Ch_TR01
  icon: BR_Miho_N
  sort: 6
- key: TRStage_01_08
  chapter: Ch_TR01
  icon: BR_AS12TurtleDragon_N
  sort: 7
- key: TRStage_01_09
  chapter: Ch_TR01
  icon: BR_HongRyun_N
  sort: 8
- key: TRStage_01_10
  chapter: Ch_TR01
  icon: BR_PoniesAnger_N
  sort: 9
- key: TRStage_01_11
  chapter: Ch_TR01
  icon: BR_Miho_N
  sort: 10
- key: TRStage_01_12
  chapter: Ch_TR01
  icon: BR_PoniesAnger_N
  sort: 11
- key: TRStage_01_13
  chapter: Ch_TR01
  icon: BR_AS12TurtleDragon_N
  sort: 12
- key: TRStage_01_14
  chapter: Ch_TR01
  icon: BR_Bulgasari_N
  sort: 13
- key: TRStage_01_15
  chapter: Ch_TR01
  icon: BR_HongRyun_N
  sort: 14
- key: TRStage_00_01
  chapter: Ch_TR00
  icon: DS_Johanna_N
  sort: 15
- key: TRStage_00_02
  chapter: Ch_TR00
  icon: BR_Wraithy_N
  sort: 16
- key: TRStage_00_03
  chapter: Ch_TR00
  icon: AGS_SpartanB_N
  sort: 17
- key: TRStage_00_04
  chapter: Ch_TR00
  icon: BR_Brownie_N
  sort: 18
- key: TRStage_00_05
  chapter: Ch_TR00
  icon: BR_Harpy_N
  sort: 19
