uid: TrainingSupport1
type: EXP
image: TrainingSupport
size: 2
duration: 0
list:
  - level: 1
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 9
      count: 2
    upgradeTime: 0
    upgradeRequired:
      Wood: 0
      Stone: 0
      Iron: 0
      Material: null
    produceItem:
      - type: exp
        bonus: 1.25
  - level: 2
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 10
      count: 2
    upgradeTime: 957
    upgradeRequired:
      Wood: 1
      Stone: 1
      Iron: 0
      Material: null
    produceItem:
      - type: exp
        bonus: 1.37
  - level: 3
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 11
      count: 2
    upgradeTime: 1352
    upgradeRequired:
      Wood: 1
      Stone: 1
      Iron: 1
      Material: null
    produceItem:
      - type: exp
        bonus: 1.5
  - level: 4
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 12
      count: 2
    upgradeTime: 1896
    upgradeRequired:
      Wood: 2
      Stone: 2
      Iron: 2
      Material: null
    produceItem:
      - type: exp
        bonus: 1.63
  - level: 5
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 13
      count: 2
    upgradeTime: 2639
    upgradeRequired:
      Wood: 3
      Stone: 3
      Iron: 3
      Material: null
    produceItem:
      - type: exp
        bonus: 1.75
  - level: 6
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 14
      count: 2
    upgradeTime: 3636
    upgradeRequired:
      Wood: 4
      Stone: 4
      Iron: 4
      Material: null
    produceItem:
      - type: exp
        bonus: 1.88
  - level: 7
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 15
      count: 2
    upgradeTime: 4952
    upgradeRequired:
      Wood: 7
      Stone: 7
      Iron: 7
      Material: null
    produceItem:
      - type: exp
        bonus: 2
  - level: 8
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 16
      count: 2
    upgradeTime: 6651
    upgradeRequired:
      Wood: 8
      Stone: 8
      Iron: 8
      Material: null
    produceItem:
      - type: exp
        bonus: 2.13
  - level: 9
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 19
      count: 2
    upgradeTime: 8150
    upgradeRequired:
      Wood: 10
      Stone: 10
      Iron: 10
      Material: null
    produceItem:
      - type: exp
        bonus: 2.25
  - level: 10
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 32
      count: 3
    upgradeTime: 20758
    upgradeRequired:
      Wood: 15
      Stone: 15
      Iron: 15
      Material:
        type: Training
        grade: T1
        value: 20
    produceItem:
      - type: exp
        bonus: 2.38
  - level: 11
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 34
      count: 3
    upgradeTime: 28339
    upgradeRequired:
      Wood: 20
      Stone: 20
      Iron: 20
      Material:
        type: Training
        grade: T1
        value: 30
    produceItem:
      - type: exp
        bonus: 2.5
  - level: 12
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 37
      count: 3
    upgradeTime: 33961
    upgradeRequired:
      Wood: 25
      Stone: 25
      Iron: 25
      Material:
        type: Training
        grade: T1
        value: 40
    produceItem:
      - type: exp
        bonus: 2.63
  - level: 13
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 39
      count: 3
    upgradeTime: 41219
    upgradeRequired:
      Wood: 40
      Stone: 40
      Iron: 40
      Material:
        type: Training
        grade: T1
        value: 50
    produceItem:
      - type: exp
        bonus: 2.75
  - level: 14
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 42
      count: 3
    upgradeTime: 47215
    upgradeRequired:
      Wood: 55
      Stone: 55
      Iron: 55
      Material:
        type: Training
        grade: T1
        value: 60
    produceItem:
      - type: exp
        bonus: 2.88
  - level: 15
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 45
      count: 3
    upgradeTime: 56048
    upgradeRequired:
      Wood: 80
      Stone: 80
      Iron: 80
      Material:
        type: Training
        grade: T1
        value: 70
    produceItem:
      - type: exp
        bonus: 3
  - level: 16
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 48
      count: 3
    upgradeTime: 62124
    upgradeRequired:
      Wood: 100
      Stone: 100
      Iron: 100
      Material:
        type: Training
        grade: T1
        value: 80
    produceItem:
      - type: exp
        bonus: 3.13
  - level: 17
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 61
      count: 3
    upgradeTime: 137079
    upgradeRequired:
      Wood: 150
      Stone: 150
      Iron: 150
      Material:
        type: Training
        grade: T2
        value: 30
    produceItem:
      - type: exp
        bonus: 3.25
  - level: 18
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 62
      count: 3
    upgradeTime: 155996
    upgradeRequired:
      Wood: 165
      Stone: 165
      Iron: 165
      Material:
        type: Training
        grade: T2
        value: 40
    produceItem:
      - type: exp
        bonus: 3.38
  - level: 19
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 68
      count: 3
    upgradeTime: 168490
    upgradeRequired:
      Wood: 175
      Stone: 175
      Iron: 175
      Material:
        type: Training
        grade: T2
        value: 50
    produceItem:
      - type: exp
        bonus: 3.63
  - level: 20
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 74
      count: 3
    upgradeTime: 187043
    upgradeRequired:
      Wood: 235
      Stone: 235
      Iron: 235
      Material:
        type: Training
        grade: T2
        value: 60
    produceItem:
      - type: exp
        bonus: 3.75
  - level: 21
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 77
      count: 4
    upgradeTime: 200635
    upgradeRequired:
      Wood: 290
      Stone: 290
      Iron: 290
      Material:
        type: Training
        grade: T2
        value: 70
    produceItem:
      - type: exp
        bonus: 4
  - level: 22
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 83
      count: 4
    upgradeTime: 378408
    upgradeRequired:
      Wood: 575
      Stone: 575
      Iron: 575
      Material:
        type: Training
        grade: T3
        value: 30
    produceItem:
      - type: exp
        bonus: 4.25
  - level: 23
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 90
      count: 4
    upgradeTime: 409133
    upgradeRequired:
      Wood: 740
      Stone: 740
      Iron: 740
      Material:
        type: Training
        grade: T3
        value: 35
    produceItem:
      - type: exp
        bonus: 4.5
  - level: 24
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 98
      count: 4
    upgradeTime: 434072
    upgradeRequired:
      Wood: 930
      Stone: 930
      Iron: 930
      Material:
        type: Training
        grade: T3
        value: 40
    produceItem:
      - type: exp
        bonus: 4.75
  - level: 25
    cost:
      - 0
      - 0
      - 0
    requiredCombatant:
      type: ""
      level: 100
      count: 4
    upgradeTime: 484000
    upgradeRequired:
      Wood: 1120
      Stone: 1120
      Iron: 1120
      Material:
        type: Training
        grade: T3
        value: 50
    produceItem:
      - type: exp
        bonus: 5
